<?php

declare(strict_types=1);

use AIArmada\Docs\Enums\DocType;
use AIArmada\Docs\Models\Doc;
use AIArmada\Docs\Numbering\NumberStrategyRegistry;
use AIArmada\Docs\Services\DocService;
use AIArmada\Docs\Services\SequenceManager;
use AIArmada\Docs\States\Draft;
use AIArmada\Docs\States\Paid;
use AIArmada\Docs\States\PartiallyPaid;
use AIArmada\Docs\States\Sent;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

beforeEach(function (): void {
    $this->sequenceManager = new SequenceManager;
    $this->numberRegistry = new NumberStrategyRegistry;
    $this->service = new DocService($this->numberRegistry, $this->sequenceManager);
});

test('can create a document from type', function (): void {
    $data = [
        'issue_date' => now(),
        'currency' => 'USD',
        'items' => [
            [
                'quantity' => 2,
                'unit_price_minor' => 100,
                'tax_amount_minor' => 10,
            ],
        ],
    ];

    $doc = $this->service->createFromType(DocType::Invoice, $data);

    expect($doc)
        ->toBeInstanceOf(Doc::class)
        ->doc_number->not->toBeNull() // Generated by real sequence
        ->doc_type->toBe(DocType::Invoice->value)
        ->subtotal_minor->toBe(200)
        ->tax_amount_minor->toBe(10)
        ->total_minor->toBe(210);

    expect($doc->status->equals(Draft::class))->toBeTrue();

    // Verify version created
    expect($doc->versions)->toHaveCount(1);
    expect($doc->versions->first()->change_summary)->toBe('Initial creation');
});

test('can update a document', function (): void {
    $doc = Doc::factory()->create([
        'doc_number' => 'INV-OLD',
        'subtotal_minor' => 100,
        'total_minor' => 110,
    ]);

    $data = [
        'notes' => 'Updated notes',
        'items' => [
            [
                'quantity' => 1,
                'unit_price_minor' => 200,
                'tax_amount_minor' => 20,
            ],
        ],
    ];

    $updatedDoc = $this->service->update($doc, $data);

    expect($updatedDoc->fresh())
        ->notes->toBe('Updated notes')
        ->subtotal_minor->toBe(200)
        ->total_minor->toBe(220);

    // Verify new version created
    expect($doc->versions)->toHaveCount(1); // Factory might not create one, service creates one
    expect($doc->versions->last()->change_summary)->toBe('Document updated');
});

test('can calculate totals', function (): void {
    $items = [
        [
            'quantity' => 2,
            'unit_price_minor' => 50,
            'tax_amount_minor' => 5,
        ],
        [
            'quantity' => 1,
            'unit_price_minor' => 100,
            'tax_amount_minor' => 10,
        ],
    ];

    $totals = $this->service->calculateTotals($items, 10); // 10 discount

    // Subtotal: (2*50) + (1*100) = 200
    // Tax: (2*5) + (1*10) = 15 (assuming tax_amount is per-line total tax)
    // Total: 200 + 15 - 10 = 205

    expect($totals['subtotal_minor'])->toBe(200)
        ->and($totals['tax_amount_minor'])->toBe(15)
        ->and($totals['total_minor'])->toBe(205);
});

test('can record payment', function (): void {
    $doc = Doc::factory()->create([
        'total_minor' => 100,
        'status' => Sent::class,
    ]);

    $payment = $this->service->recordPayment($doc, [
        'amount_minor' => 50,
        'payment_method' => 'bank_transfer',
        'reference' => 'REF123',
    ]);

    expect($payment->amount_minor)->toBe(50);
    expect($doc->fresh()->status->equals(PartiallyPaid::class))->toBeTrue();

    // Pay remaining
    $this->service->recordPayment($doc, [
        'amount_minor' => 50,
        'payment_method' => 'bank_transfer',
    ]);

    expect($doc->fresh()->status->equals(Paid::class))->toBeTrue();
});

test('can clone a document', function (): void {
    $original = Doc::factory()->create([
        'doc_type' => DocType::Invoice,
        'currency' => 'USD',
        'items' => [['name' => 'Item 1']],
    ]);

    $clone = $this->service->clone($original);

    expect($clone->currency)->toBe('USD')
        ->and($clone->doc_number)->not->toBe($original->doc_number)
        ->and($clone->metadata['cloned_from'])->toBe($original->id);
});

test('can convert a document', function (): void {
    $source = Doc::factory()->create([
        'doc_type' => DocType::Quotation,
        'doc_number' => 'QUO-123',
        'subtotal_minor' => 100,
        'total_minor' => 110,
        'items' => [['name' => 'Item 1', 'quantity' => 1, 'unit_price_minor' => 100]],
    ]);

    $converted = $this->service->convert($source, DocType::Invoice);

    expect($converted)
        ->toBeInstanceOf(Doc::class)
        ->doc_type->toBe(DocType::Invoice->value)
        ->subtotal_minor->toBe(100)
        ->total_minor->toBe(100)
        ->metadata->toHaveKey('converted_from')
        ->metadata->converted_from->doc_number->toBe('QUO-123');
});
