<?php

declare(strict_types=1);

namespace AIArmada\FilamentEvents\Resources\OccurrenceResource\Schemas;

use AIArmada\Events\Data\OccurrenceDetailData;
use AIArmada\Events\Enums\OccurrenceParticipationMode;
use AIArmada\Events\Enums\OccurrenceStatus;
use AIArmada\Events\Models\Occurrence;
use AIArmada\Events\Services\EventQueryService;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

final class OccurrenceInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->schema([
                Section::make('Occurrence')
                    ->schema([
                        TextEntry::make('event.name')
                            ->label('Event'),
                        TextEntry::make('name')
                            ->placeholder('Unnamed run'),
                        TextEntry::make('status')
                            ->badge()
                            ->formatStateUsing(fn (OccurrenceStatus $state): string => $state->label())
                            ->color(fn (OccurrenceStatus $state): string => $state->color()),
                        TextEntry::make('participation_mode')
                            ->label('Participation Mode')
                            ->badge()
                            ->formatStateUsing(fn (OccurrenceParticipationMode $state): string => $state->label())
                            ->color(fn (OccurrenceParticipationMode $state): string => $state->color()),
                        TextEntry::make('starts_at')
                            ->dateTime('d M Y H:i'),
                        TextEntry::make('ends_at')
                            ->dateTime('d M Y H:i')
                            ->placeholder('Not set'),
                        TextEntry::make('timezone'),
                        TextEntry::make('location_label')
                            ->label('Location')
                            ->placeholder('No address'),
                        TextEntry::make('registrations_count')
                            ->label('Registrations')
                            ->state(fn (Occurrence $record): int => $record->registrations()->count()),
                    ])
                    ->columns(4),

                Section::make('Registration Window')
                    ->schema([
                        TextEntry::make('registration_opens_at')
                            ->dateTime()
                            ->placeholder('Not set'),
                        TextEntry::make('registration_closes_at')
                            ->dateTime()
                            ->placeholder('Not set'),
                        TextEntry::make('check_in_opens_at')
                            ->dateTime()
                            ->placeholder('Not set'),
                        TextEntry::make('check_in_closes_at')
                            ->dateTime()
                            ->placeholder('Not set'),
                    ])
                    ->columns(4),

                Section::make('Registration Policy')
                    ->schema([
                        TextEntry::make('waitlist_enabled')
                            ->label('Waitlist')
                            ->badge()
                            ->formatStateUsing(fn (bool $state): string => $state ? 'Enabled' : 'Disabled')
                            ->color(fn (bool $state): string => $state ? 'info' : 'gray'),
                        TextEntry::make('approval_required')
                            ->label('Approval')
                            ->badge()
                            ->formatStateUsing(fn (bool $state): string => $state ? 'Required' : 'Open')
                            ->color(fn (bool $state): string => $state ? 'warning' : 'success'),
                    ])
                    ->columns(2),

                Section::make('Read Model Snapshot')
                    ->description('Projections generated by the package EventQueryService from the OccurrenceDetailData DTO.')
                    ->schema([
                        TextEntry::make('snapshot.addressLines')
                            ->label('Address Lines')
                            ->state(fn (Occurrence $record): string => self::formatStringList(self::snapshot($record)->addressLines))
                            ->placeholder('No address lines')
                            ->columnSpanFull(),

                        TextEntry::make('snapshot.coordinates')
                            ->label('Coordinates')
                            ->state(fn (Occurrence $record): string => self::formatCoordinates(self::snapshot($record)))
                            ->placeholder('No coordinates')
                            ->columnSpanFull(),

                        TextEntry::make('snapshot.agendaItems')
                            ->label('Agenda Items')
                            ->state(function (Occurrence $record): string {
                                $items = self::snapshot($record)->agendaItems;

                                return implode("\n", array_map(
                                    static fn ($item): string => sprintf(
                                        '%s (%s — %s)',
                                        (string) ($item->title ?? $item->segmentKey),
                                        (string) ($item->startsAt ?? '—'),
                                        (string) ($item->endsAt ?? '—'),
                                    ),
                                    $items,
                                ));
                            })
                            ->placeholder('No agenda items')
                            ->columnSpanFull(),

                        TextEntry::make('snapshot.references')
                            ->label('Reference Materials')
                            ->state(fn (Occurrence $record): string => self::formatJsonState(self::snapshot($record)->references))
                            ->placeholder('No references')
                            ->columnSpanFull(),

                        TextEntry::make('snapshot.metadata')
                            ->label('Metadata')
                            ->state(fn (Occurrence $record): string => self::formatJsonState(self::snapshot($record)->metadata))
                            ->placeholder('No metadata')
                            ->columnSpanFull(),
                    ])
                    ->columns(1)
                    ->collapsible(),
            ]);
    }

    private static function snapshot(Occurrence $occurrence): OccurrenceDetailData
    {
        return app(EventQueryService::class)->occurrence($occurrence);
    }

    /**
     * @param  array<int, string>  $items
     */
    private static function formatStringList(array $items): string
    {
        $filtered = array_values(array_filter(
            $items,
            static fn (mixed $item): bool => is_string($item) && mb_trim($item) !== '',
        ));

        return $filtered === [] ? '' : implode(', ', $filtered);
    }

    private static function formatCoordinates(OccurrenceDetailData $dto): string
    {
        $lat = $dto->addressLatitude;
        $lng = $dto->addressLongitude;

        if ($lat === null && $lng === null) {
            return '';
        }

        return mb_trim(sprintf('%s, %s', (string) ($lat ?? '—'), (string) ($lng ?? '—')));
    }

    private static function formatJsonState(mixed $state): string
    {
        if (! is_array($state)) {
            return '';
        }

        return json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) ?: '';
    }
}
