import csv, sys
# El Salvador gate. B9 revisit: fix-and-fill, 12 parent cells
# (La Libertad x6 + La Paz x3 were mis-parented to Cuscatlán;
# San Miguel x3 to Morazán — copy-paste errors; names carry
# their department). Tree 14 departments + 44 municipalities
# (2024 reform: 262->44). Codes 262/262: full per-code mapping
# pins come from the SV worker crosswalk (Correos + reform
# mapping); this gate pins areas + code/link counts + set
# shape. Run from repo root:
# python3 docs/agents/audit/gate_sv.py
A = './packages/addressing/resources/geography/el-salvador-address-areas.csv'
C = './packages/addressing/resources/geography/el-salvador-postal-codes.csv'
L = './packages/addressing/resources/geography/el-salvador-postal-code-areas.csv'
DEPTS = {'AH': 'Ahuachapán', 'CA': 'Cabañas', 'CH': 'Chalatenango',
         'CU': 'Cuscatlán', 'LI': 'La Libertad', 'PA': 'La Paz',
         'UN': 'La Unión', 'MO': 'Morazán', 'SM': 'San Miguel',
         'SS': 'San Salvador', 'SV': 'San Vicente', 'SA': 'Santa Ana',
         'SO': 'Sonsonate', 'US': 'Usulután'}
MUNIC = {'sv:department:ahuachapan': 3, 'sv:department:cabanas': 2,
         'sv:department:chalatenango': 3, 'sv:department:cuscatlan': 2,
         'sv:department:la-libertad': 6, 'sv:department:la-paz': 3,
         'sv:department:la-union': 2, 'sv:department:morazan': 2,
         'sv:department:san-miguel': 3, 'sv:department:san-salvador': 5,
         'sv:department:san-vicente': 2, 'sv:department:santa-ana': 4,
         'sv:department:sonsonate': 4, 'sv:department:usulutan': 3}
fails = []


def check(name, cond, detail=''):
    print(('PASS' if cond else 'FAIL'), name, detail)
    if not cond:
        fails.append(name)


raw_a = open(A, 'rb').read()
check('areas-lf', b'\r' not in raw_a)
check('areas-trailing-nl', raw_a.endswith(b'\n'))
for label, path in (('codes', C), ('links', L)):
    raw = open(path, 'rb').read()
    check(f'{label}-crlf', raw.count(b'\r') == raw.count(b'\n') and raw.count(b'\r') > 0)
    check(f'{label}-trailing-crlf', raw.endswith(b'\r\n'))
areas = list(csv.DictReader(open(A, newline='')))
check('areas-58', len(areas) == 58, str(len(areas)))
got_d = {r['code']: r['name'] for r in areas if r['level'] == '1'}
check('depts-14', got_d == DEPTS, str({k for k in DEPTS if got_d.get(k) != DEPTS[k]}))
got_m = {}
for r in areas:
    if r['level'] == '2':
        got_m[r['parent_source_id']] = got_m.get(r['parent_source_id'], 0) + 1
check('munic-44', got_m == MUNIC, str({k for k in MUNIC if got_m.get(k) != MUNIC[k]}))
codes = [r['code'] for r in csv.DictReader(open(C, newline=''))]
check('codes-262', len(codes) == 262, str(len(codes)))
check('codes-4digit', all(len(c) == 4 and c.isdigit() for c in codes))
links = list(csv.DictReader(open(L, newline='')))
check('links-262', len(links) == 262, str(len(links)))
check('all-primary', all(r['is_primary'] == 'true' for r in links))
# --- B9 SV worker crosswalk (SUPERSET addition) ---
# code -> (old pre-2024 municipality/district per mapanet.eu, new-44 area_source_id).
# Cross-checked: mapanet full 262 scrape (2026-10-03) + es-wiki reform annex
# (Anexo:Municipios y distritos, citing DL reform D.O. 14/06/2023) +
# worldpostalcodes spot profiles. Aliases: Ciudad Delgado=Delgado,
# San Jose de la Fuente=San Jose (La Union), San Antonio del Mosco=
# San Antonio (San Miguel), San Jose Cancasque=Cancasque.
XMAP = {
    '1101': ('San Salvador', 'sv:municipality:central-san-salvador'),
    '1115': ('San Marcos', 'sv:municipality:southern-san-salvador'),
    '1116': ('Soyapango', 'sv:municipality:eastern-san-salvador'),
    '1117': ('Ilopango', 'sv:municipality:eastern-san-salvador'),
    '1118': ('Ciudad Delgado', 'sv:municipality:central-san-salvador'),
    '1119': ('Cuscatancingo', 'sv:municipality:central-san-salvador'),
    '1120': ('Mejicanos', 'sv:municipality:central-san-salvador'),
    '1121': ('Ayutuxtepeque', 'sv:municipality:central-san-salvador'),
    '1122': ('Aguilares', 'sv:municipality:northern-san-salvador'),
    '1123': ('Apopa', 'sv:municipality:western-san-salvador'),
    '1124': ('El Paisnal', 'sv:municipality:northern-san-salvador'),
    '1125': ('Guazapa', 'sv:municipality:northern-san-salvador'),
    '1126': ('Nejapa', 'sv:municipality:western-san-salvador'),
    '1127': ('Panchimalco', 'sv:municipality:southern-san-salvador'),
    '1128': ('Rosario de Mora', 'sv:municipality:southern-san-salvador'),
    '1129': ('San Martín', 'sv:municipality:eastern-san-salvador'),
    '1130': ('Santiago Texacuangos', 'sv:municipality:southern-san-salvador'),
    '1131': ('Santo Tomás', 'sv:municipality:southern-san-salvador'),
    '1132': ('Tonacatepeque', 'sv:municipality:eastern-san-salvador'),
    '1201': ('Sensuntepeque', 'sv:municipality:eastern-cabanas'),
    '1202': ('Cinquera', 'sv:municipality:western-cabanas'),
    '1203': ('Guacotecti', 'sv:municipality:eastern-cabanas'),
    '1204': ('Ilobasco', 'sv:municipality:western-cabanas'),
    '1206': ('Jutiapa', 'sv:municipality:western-cabanas'),
    '1207': ('San Isidro', 'sv:municipality:eastern-cabanas'),
    '1208': ('Tejutepeque', 'sv:municipality:western-cabanas'),
    '1209': ('Dolores', 'sv:municipality:eastern-cabanas'),
    '1210': ('Victoria', 'sv:municipality:eastern-cabanas'),
    '1301': ('Chalatenango', 'sv:municipality:southern-chalatenango'),
    '1302': ('Agua Caliente', 'sv:municipality:central-chalatenango'),
    '1303': ('Arcatao', 'sv:municipality:southern-chalatenango'),
    '1304': ('Azacualpa', 'sv:municipality:southern-chalatenango'),
    '1305': ('San José Cancasque', 'sv:municipality:southern-chalatenango'),
    '1306': ('Citalá', 'sv:municipality:northern-chalatenango'),
    '1307': ('Comalapa', 'sv:municipality:southern-chalatenango'),
    '1308': ('Concepción Quezaltepeque', 'sv:municipality:southern-chalatenango'),
    '1309': ('Dulce Nombre de María', 'sv:municipality:central-chalatenango'),
    '1311': ('El Carrizal', 'sv:municipality:southern-chalatenango'),
    '1312': ('El Paraíso', 'sv:municipality:central-chalatenango'),
    '1313': ('La Laguna', 'sv:municipality:southern-chalatenango'),
    '1314': ('La Palma', 'sv:municipality:northern-chalatenango'),
    '1315': ('La Reina', 'sv:municipality:central-chalatenango'),
    '1316': ('Las Flores', 'sv:municipality:southern-chalatenango'),
    '1317': ('Las Vueltas', 'sv:municipality:southern-chalatenango'),
    '1318': ('Nombre de Jesús', 'sv:municipality:southern-chalatenango'),
    '1319': ('Nueva Concepción', 'sv:municipality:central-chalatenango'),
    '1320': ('Nueva Trinidad', 'sv:municipality:southern-chalatenango'),
    '1321': ('Ojos de Agua', 'sv:municipality:southern-chalatenango'),
    '1322': ('Potonico', 'sv:municipality:southern-chalatenango'),
    '1324': ('San Antonio de la Cruz', 'sv:municipality:southern-chalatenango'),
    '1325': ('San Antonio Los Ranchos', 'sv:municipality:southern-chalatenango'),
    '1326': ('San Fernando', 'sv:municipality:central-chalatenango'),
    '1327': ('San Francisco Lempa', 'sv:municipality:southern-chalatenango'),
    '1328': ('San Francisco Morazán', 'sv:municipality:central-chalatenango'),
    '1329': ('San Ignacio', 'sv:municipality:northern-chalatenango'),
    '1330': ('San Isidro Labrador', 'sv:municipality:southern-chalatenango'),
    '1331': ('San Luís del Carmen', 'sv:municipality:southern-chalatenango'),
    '1332': ('San Miguel de Mercedes', 'sv:municipality:southern-chalatenango'),
    '1333': ('San Rafael', 'sv:municipality:central-chalatenango'),
    '1334': ('Santa Rita', 'sv:municipality:central-chalatenango'),
    '1335': ('Tejutla', 'sv:municipality:central-chalatenango'),
    '1401': ('Cojutepeque', 'sv:municipality:southern-cuscatlan'),
    '1402': ('Candelaria', 'sv:municipality:southern-cuscatlan'),
    '1403': ('El Carmen', 'sv:municipality:southern-cuscatlan'),
    '1404': ('El Rosario', 'sv:municipality:southern-cuscatlan'),
    '1405': ('Monte San Juan', 'sv:municipality:southern-cuscatlan'),
    '1406': ('Oratorio de Concepción', 'sv:municipality:northern-cuscatlan'),
    '1407': ('San Bartolomé Perulapía', 'sv:municipality:northern-cuscatlan'),
    '1408': ('San Cristóbal', 'sv:municipality:southern-cuscatlan'),
    '1409': ('San José Guayabal', 'sv:municipality:northern-cuscatlan'),
    '1410': ('San Pedro Perulapán', 'sv:municipality:northern-cuscatlan'),
    '1411': ('San Rafael Cedros', 'sv:municipality:southern-cuscatlan'),
    '1412': ('San Ramón', 'sv:municipality:southern-cuscatlan'),
    '1413': ('Santa Cruz Analquito', 'sv:municipality:southern-cuscatlan'),
    '1414': ('Santa Cruz Michapa', 'sv:municipality:southern-cuscatlan'),
    '1415': ('Suchitoto', 'sv:municipality:northern-cuscatlan'),
    '1416': ('Tenancingo', 'sv:municipality:southern-cuscatlan'),
    '1501': ('Santa Tecla', 'sv:municipality:southern-la-libertad'),
    '1502': ('Antiguo Cuscatlán', 'sv:municipality:eastern-la-libertad'),
    '1504': ('Ciudad Arce', 'sv:municipality:central-la-libertad'),
    '1506': ('Comasagua', 'sv:municipality:southern-la-libertad'),
    '1507': ('Chiltiupán', 'sv:municipality:coastal-la-libertad'),
    '1508': ('Huizúcar', 'sv:municipality:eastern-la-libertad'),
    '1509': ('Jayaqué', 'sv:municipality:western-la-libertad'),
    '1510': ('Jicalapa', 'sv:municipality:coastal-la-libertad'),
    '1511': ('La Libertad', 'sv:municipality:coastal-la-libertad'),
    '1512': ('Colón', 'sv:municipality:western-la-libertad'),
    '1513': ('Nuevo Cuscatlán', 'sv:municipality:eastern-la-libertad'),
    '1514': ('San Juan Opico', 'sv:municipality:central-la-libertad'),
    '1515': ('Quezaltepeque', 'sv:municipality:northern-la-libertad'),
    '1516': ('Sacacoyo', 'sv:municipality:western-la-libertad'),
    '1517': ('San José Villanueva', 'sv:municipality:eastern-la-libertad'),
    '1518': ('San Matías', 'sv:municipality:northern-la-libertad'),
    '1519': ('San Pablo Tacachico', 'sv:municipality:northern-la-libertad'),
    '1521': ('Talnique', 'sv:municipality:western-la-libertad'),
    '1522': ('Tamanique', 'sv:municipality:coastal-la-libertad'),
    '1523': ('Teotepeque', 'sv:municipality:coastal-la-libertad'),
    '1524': ('Tepecoyo', 'sv:municipality:western-la-libertad'),
    '1525': ('Zaragoza', 'sv:municipality:eastern-la-libertad'),
    '1601': ('Zacatecoluca', 'sv:municipality:eastern-la-paz'),
    '1603': ('Cuyultitán', 'sv:municipality:western-la-paz'),
    '1604': ('El Rosario', 'sv:municipality:central-la-paz'),
    '1605': ('Jerusalén', 'sv:municipality:central-la-paz'),
    '1606': ('San Luís La Herradura', 'sv:municipality:central-la-paz'),
    '1607': ('Mercedes La Ceiba', 'sv:municipality:central-la-paz'),
    '1608': ('Olocuilta', 'sv:municipality:western-la-paz'),
    '1609': ('Paraíso de Osorio', 'sv:municipality:central-la-paz'),
    '1610': ('San Antonio Masahuat', 'sv:municipality:central-la-paz'),
    '1611': ('San Emigdio', 'sv:municipality:central-la-paz'),
    '1612': ('San Francisco Chinameca', 'sv:municipality:western-la-paz'),
    '1613': ('San Juan Nonualco', 'sv:municipality:eastern-la-paz'),
    '1614': ('San Juan Talpa', 'sv:municipality:western-la-paz'),
    '1615': ('San Juan Tepezontes', 'sv:municipality:central-la-paz'),
    '1616': ('San Luís Talpa', 'sv:municipality:western-la-paz'),
    '1617': ('San Miguel Tepezontes', 'sv:municipality:central-la-paz'),
    '1618': ('San Pedro Masahuat', 'sv:municipality:western-la-paz'),
    '1619': ('San Pedro Nonualco', 'sv:municipality:central-la-paz'),
    '1620': ('San Rafael Obrajuelo', 'sv:municipality:eastern-la-paz'),
    '1621': ('Santa María Ostuma', 'sv:municipality:central-la-paz'),
    '1622': ('Santiago Nonualco', 'sv:municipality:central-la-paz'),
    '1623': ('Tapalhuaca', 'sv:municipality:western-la-paz'),
    '1701': ('San Vicente', 'sv:municipality:southern-san-vicente'),
    '1702': ('Apastepeque', 'sv:municipality:northern-san-vicente'),
    '1703': ('Guadalupe', 'sv:municipality:southern-san-vicente'),
    '1704': ('San Cayetano Istepeque', 'sv:municipality:southern-san-vicente'),
    '1705': ('San Estéban Catarina', 'sv:municipality:northern-san-vicente'),
    '1706': ('San Ildefonso', 'sv:municipality:northern-san-vicente'),
    '1707': ('San Lorenzo', 'sv:municipality:northern-san-vicente'),
    '1708': ('San Sebastián', 'sv:municipality:northern-san-vicente'),
    '1709': ('Santa Clara', 'sv:municipality:northern-san-vicente'),
    '1710': ('Santo Domingo', 'sv:municipality:northern-san-vicente'),
    '1711': ('Tecoluca', 'sv:municipality:southern-san-vicente'),
    '1712': ('Tepetitán', 'sv:municipality:southern-san-vicente'),
    '1713': ('Verapaz', 'sv:municipality:southern-san-vicente'),
    '2101': ('Ahuachapán', 'sv:municipality:central-ahuachapan'),
    '2102': ('Apaneca', 'sv:municipality:central-ahuachapan'),
    '2103': ('Atiquizaya', 'sv:municipality:northern-ahuachapan'),
    '2106': ('Concepción de Ataco', 'sv:municipality:central-ahuachapan'),
    '2107': ('El Refugio', 'sv:municipality:northern-ahuachapan'),
    '2108': ('Guaymango', 'sv:municipality:southern-ahuachapan'),
    '2109': ('Jujutla', 'sv:municipality:southern-ahuachapan'),
    '2113': ('San Francisco Menéndez', 'sv:municipality:southern-ahuachapan'),
    '2115': ('San Lorenzo', 'sv:municipality:northern-ahuachapan'),
    '2116': ('San Pedro Puxtla', 'sv:municipality:southern-ahuachapan'),
    '2117': ('Tacuba', 'sv:municipality:central-ahuachapan'),
    '2118': ('Turín', 'sv:municipality:northern-ahuachapan'),
    '2201': ('Santa Ana', 'sv:municipality:santa-ana-el-salvador-central-santa-ana'),
    '2203': ('Candelaria de la Frontera', 'sv:municipality:western-santa-ana'),
    '2204': ('Coatepeque', 'sv:municipality:eastern-santa-ana'),
    '2205': ('Chalchuapa', 'sv:municipality:western-santa-ana'),
    '2207': ('El Congo', 'sv:municipality:eastern-santa-ana'),
    '2208': ('El Porvenir', 'sv:municipality:western-santa-ana'),
    '2210': ('Masahuat', 'sv:municipality:northern-santa-ana'),
    '2211': ('Metapán', 'sv:municipality:northern-santa-ana'),
    '2212': ('San Antonio Pajonal', 'sv:municipality:western-santa-ana'),
    '2215': ('San Sebastián Salitrillo', 'sv:municipality:western-santa-ana'),
    '2216': ('Santa Rosa Guachipilín', 'sv:municipality:northern-santa-ana'),
    '2217': ('Santiago de la Frontera', 'sv:municipality:western-santa-ana'),
    '2218': ('Texistepeque', 'sv:municipality:northern-santa-ana'),
    '2301': ('Sonsonate', 'sv:municipality:central-sonsonate'),
    '2302': ('Acajutla', 'sv:municipality:acajutla-acajutla-western-sonsonate'),
    '2303': ('Armenia', 'sv:municipality:eastern-sonsonate'),
    '2304': ('Caluco', 'sv:municipality:eastern-sonsonate'),
    '2305': ('Cuisnahuat', 'sv:municipality:eastern-sonsonate'),
    '2306': ('Izalco', 'sv:municipality:eastern-sonsonate'),
    '2307': ('Juayúa', 'sv:municipality:northern-sonsonate'),
    '2311': ('Nahuizalco', 'sv:municipality:northern-sonsonate'),
    '2312': ('Nahulingo', 'sv:municipality:central-sonsonate'),
    '2313': ('Salcoatitán', 'sv:municipality:northern-sonsonate'),
    '2314': ('San Antonio del Monte', 'sv:municipality:central-sonsonate'),
    '2316': ('San Julián', 'sv:municipality:eastern-sonsonate'),
    '2317': ('Santa Catarina Masahuat', 'sv:municipality:northern-sonsonate'),
    '2318': ('Santa Isabel Ishuatán', 'sv:municipality:eastern-sonsonate'),
    '2319': ('Santo Domingo de Guzmán', 'sv:municipality:central-sonsonate'),
    '2320': ('Sonzacate', 'sv:municipality:central-sonsonate'),
    '3101': ('La Unión', 'sv:municipality:southern-la-union'),
    '3104': ('Anamorós', 'sv:municipality:northern-la-union'),
    '3105': ('Bolívar', 'sv:municipality:northern-la-union'),
    '3106': ('Concepción de Oriente', 'sv:municipality:northern-la-union'),
    '3107': ('Conchagua', 'sv:municipality:southern-la-union'),
    '3108': ('El Carmen', 'sv:municipality:southern-la-union'),
    '3109': ('El Sauce', 'sv:municipality:northern-la-union'),
    '3111': ('Intipucá', 'sv:municipality:southern-la-union'),
    '3112': ('Lislique', 'sv:municipality:northern-la-union'),
    '3113': ('Meanguera del Golfo', 'sv:municipality:southern-la-union'),
    '3114': ('Nueva Esparta', 'sv:municipality:northern-la-union'),
    '3116': ('Pasaquina', 'sv:municipality:northern-la-union'),
    '3117': ('Polorós', 'sv:municipality:northern-la-union'),
    '3119': ('San Alejo', 'sv:municipality:southern-la-union'),
    '3120': ('San José de la Fuente', 'sv:municipality:northern-la-union'),
    '3121': ('Santa Rosa de Lima', 'sv:municipality:northern-la-union'),
    '3122': ('Yayantique', 'sv:municipality:southern-la-union'),
    '3123': ('Yucuaiquín', 'sv:municipality:southern-la-union'),
    '3201': ('San Francisco Gotera', 'sv:municipality:southern-morazan'),
    '3202': ('Arambala', 'sv:municipality:northern-morazan'),
    '3203': ('Cacaopera', 'sv:municipality:northern-morazan'),
    '3204': ('Corinto', 'sv:municipality:northern-morazan'),
    '3205': ('Chilanga', 'sv:municipality:southern-morazan'),
    '3206': ('Delicias de Concepción', 'sv:municipality:southern-morazan'),
    '3207': ('El Divisadero', 'sv:municipality:southern-morazan'),
    '3208': ('El Rosario', 'sv:municipality:northern-morazan'),
    '3209': ('Gualococti', 'sv:municipality:southern-morazan'),
    '3210': ('Guatajiagua', 'sv:municipality:southern-morazan'),
    '3211': ('Joateca', 'sv:municipality:northern-morazan'),
    '3212': ('Jocoaitique', 'sv:municipality:northern-morazan'),
    '3213': ('Jocoro', 'sv:municipality:southern-morazan'),
    '3214': ('Lolotiquillo', 'sv:municipality:southern-morazan'),
    '3215': ('Meanguera', 'sv:municipality:northern-morazan'),
    '3216': ('Osicala', 'sv:municipality:southern-morazan'),
    '3217': ('Perquín', 'sv:municipality:northern-morazan'),
    '3218': ('San Carlos', 'sv:municipality:southern-morazan'),
    '3219': ('San Fernando', 'sv:municipality:northern-morazan'),
    '3220': ('San Isidro', 'sv:municipality:northern-morazan'),
    '3221': ('San Simón', 'sv:municipality:southern-morazan'),
    '3222': ('Sensembra', 'sv:municipality:southern-morazan'),
    '3223': ('Sociedad', 'sv:municipality:southern-morazan'),
    '3224': ('Torola', 'sv:municipality:northern-morazan'),
    '3225': ('Yamabal', 'sv:municipality:southern-morazan'),
    '3226': ('Yoloaiquín', 'sv:municipality:southern-morazan'),
    '3301': ('San Miguel', 'sv:municipality:central-san-miguel'),
    '3302': ('Carolina', 'sv:municipality:northern-san-miguel'),
    '3303': ('Ciudad Barrios', 'sv:municipality:northern-san-miguel'),
    '3304': ('Comacarán', 'sv:municipality:central-san-miguel'),
    '3305': ('Chapeltique', 'sv:municipality:northern-san-miguel'),
    '3306': ('Chinameca', 'sv:municipality:western-san-miguel'),
    '3307': ('Chirilagua', 'sv:municipality:central-san-miguel'),
    '3309': ('El Tránsito', 'sv:municipality:western-san-miguel'),
    '3311': ('Lolotique', 'sv:municipality:western-san-miguel'),
    '3312': ('Moncagua', 'sv:municipality:central-san-miguel'),
    '3313': ('Nueva Guadalupe', 'sv:municipality:western-san-miguel'),
    '3314': ('Nuevo Edén de San Juan', 'sv:municipality:northern-san-miguel'),
    '3315': ('Quelepa', 'sv:municipality:central-san-miguel'),
    '3316': ('San Antonio del Mosco', 'sv:municipality:northern-san-miguel'),
    '3318': ('San Gerardo', 'sv:municipality:northern-san-miguel'),
    '3319': ('San Jorge', 'sv:municipality:western-san-miguel'),
    '3320': ('San Luís de la Reina', 'sv:municipality:northern-san-miguel'),
    '3322': ('San Rafael Oriente', 'sv:municipality:western-san-miguel'),
    '3323': ('Sesori', 'sv:municipality:northern-san-miguel'),
    '3324': ('Uluazapa', 'sv:municipality:central-san-miguel'),
    '3401': ('Usulután', 'sv:municipality:eastern-usulutan'),
    '3402': ('Alegría', 'sv:municipality:northern-usulutan'),
    '3403': ('Berlín', 'sv:municipality:northern-usulutan'),
    '3404': ('California', 'sv:municipality:eastern-usulutan'),
    '3405': ('Concepción Batres', 'sv:municipality:eastern-usulutan'),
    '3406': ('El Triunfo', 'sv:municipality:northern-usulutan'),
    '3407': ('Ereguayquín', 'sv:municipality:eastern-usulutan'),
    '3408': ('Estanzuelas', 'sv:municipality:northern-usulutan'),
    '3409': ('Jiquilisco', 'sv:municipality:western-usulutan'),
    '3410': ('Jucuapa', 'sv:municipality:northern-usulutan'),
    '3411': ('Jucuarán', 'sv:municipality:eastern-usulutan'),
    '3412': ('Mercedes Umaña', 'sv:municipality:northern-usulutan'),
    '3413': ('Nueva Granada', 'sv:municipality:northern-usulutan'),
    '3415': ('Ozatlán', 'sv:municipality:eastern-usulutan'),
    '3417': ('Puerto El Triunfo', 'sv:municipality:western-usulutan'),
    '3418': ('San Agustín', 'sv:municipality:western-usulutan'),
    '3419': ('San Buenaventura', 'sv:municipality:northern-usulutan'),
    '3420': ('San Dionisio', 'sv:municipality:eastern-usulutan'),
    '3421': ('San Francisco Javier', 'sv:municipality:western-usulutan'),
    '3422': ('Santa Elena', 'sv:municipality:eastern-usulutan'),
    '3423': ('Santa María', 'sv:municipality:eastern-usulutan'),
    '3424': ('Santiago de María', 'sv:municipality:northern-usulutan'),
    '3426': ('Tecapán', 'sv:municipality:eastern-usulutan'),
}
MUNI_CODE_COUNTS = {
    'sv:municipality:acajutla-acajutla-western-sonsonate': 1,
    'sv:municipality:central-ahuachapan': 4,
    'sv:municipality:central-chalatenango': 10,
    'sv:municipality:central-la-libertad': 2,
    'sv:municipality:central-la-paz': 12,
    'sv:municipality:central-san-miguel': 6,
    'sv:municipality:central-san-salvador': 5,
    'sv:municipality:central-sonsonate': 5,
    'sv:municipality:coastal-la-libertad': 5,
    'sv:municipality:eastern-cabanas': 5,
    'sv:municipality:eastern-la-libertad': 5,
    'sv:municipality:eastern-la-paz': 3,
    'sv:municipality:eastern-san-salvador': 4,
    'sv:municipality:eastern-santa-ana': 2,
    'sv:municipality:eastern-sonsonate': 6,
    'sv:municipality:eastern-usulutan': 10,
    'sv:municipality:northern-ahuachapan': 4,
    'sv:municipality:northern-chalatenango': 3,
    'sv:municipality:northern-cuscatlan': 5,
    'sv:municipality:northern-la-libertad': 3,
    'sv:municipality:northern-la-union': 10,
    'sv:municipality:northern-morazan': 11,
    'sv:municipality:northern-san-miguel': 8,
    'sv:municipality:northern-san-salvador': 3,
    'sv:municipality:northern-san-vicente': 7,
    'sv:municipality:northern-santa-ana': 4,
    'sv:municipality:northern-sonsonate': 4,
    'sv:municipality:northern-usulutan': 9,
    'sv:municipality:santa-ana-el-salvador-central-santa-ana': 1,
    'sv:municipality:southern-ahuachapan': 4,
    'sv:municipality:southern-chalatenango': 20,
    'sv:municipality:southern-cuscatlan': 11,
    'sv:municipality:southern-la-libertad': 2,
    'sv:municipality:southern-la-union': 8,
    'sv:municipality:southern-morazan': 15,
    'sv:municipality:southern-san-salvador': 5,
    'sv:municipality:southern-san-vicente': 6,
    'sv:municipality:western-cabanas': 4,
    'sv:municipality:western-la-libertad': 5,
    'sv:municipality:western-la-paz': 7,
    'sv:municipality:western-san-miguel': 6,
    'sv:municipality:western-san-salvador': 2,
    'sv:municipality:western-santa-ana': 6,
    'sv:municipality:western-usulutan': 4,
}
got_link = {r['postcode']: r['area_source_id'] for r in links}
check('xmap-keys', set(got_link) == set(XMAP),
      str(sorted(set(XMAP) ^ set(got_link))[:8]))
bad_x = {c for c, (d, s) in XMAP.items() if got_link.get(c) != s}
check('xmap-262', not bad_x, str(sorted(bad_x)[:8]))
got_mc = {}
for r in links:
    got_mc[r['area_source_id']] = got_mc.get(r['area_source_id'], 0) + 1
check('muni-code-counts', got_mc == MUNI_CODE_COUNTS,
      str({k for k in MUNI_CODE_COUNTS if got_mc.get(k) != MUNI_CODE_COUNTS[k]}))
print('ALL PASS' if not fails else f'{len(fails)} FAILURES: {fails}')
sys.exit(1 if fails else 0)
