import csv, re, sys
# Albania geography gate. Pins the CORRECTED M3 state (524 codes / 525
# links: 138 retargets + 36 fills - 8707 drop). Run from repo root:
# python3 docs/agents/audit/gate_al.py
A = './packages/addressing/resources/geography/albania-address-areas.csv'
C = './packages/addressing/resources/geography/albania-postal-codes.csv'
L = './packages/addressing/resources/geography/albania-postal-code-areas.csv'
fails = []
def check(name, cond, detail=''):
    print(('PASS' if cond else 'FAIL'), name, detail)
    if not cond: fails.append(name)
rows = list(csv.DictReader(open(A)))
codes = list(csv.DictReader(open(C)))
links = list(csv.DictReader(open(L)))
byid = {r['source_id']: r for r in rows}
# --- tree: ISO 3166-2:AL + Counties/Municipalities-of-Albania oracles ---
check('areas-73', len(rows) == 73, str(len(rows)))
check('counties-12', sum(1 for r in rows if r['type'] == 'county') == 12)
check('municipalities-61', sum(1 for r in rows if r['type'] == 'municipality') == 61)
kids = {'berat': 5, 'diber': 4, 'durres': 3, 'elbasan': 7, 'fier': 6,
        'gjirokaster': 7, 'korce': 6, 'kukes': 3, 'lezhe': 3, 'shkoder': 5,
        'tirana': 5, 'vlore': 7}
for county, n in kids.items():
    have = [r for r in rows if r['parent_source_id'] == f'al:county:{county}']
    check(f'county-{county}-{n}', len(have) == n, str(len(have)))
check('ISO-codes', sorted((r['name'], r['code']) for r in rows if r['type'] == 'county') ==
      [('Berat', '01'), ('Dibër', '09'), ('Durrës', '02'), ('Elbasan', '03'),
       ('Fier', '04'), ('Gjirokastër', '05'), ('Korçë', '06'), ('Kukës', '07'),
       ('Lezhë', '08'), ('Shkodër', '10'), ('Tirana', '11'), ('Vlorë', '12')])
check('dimal-current', byid['al:municipality:dimal']['parent_source_id'] == 'al:county:berat')
# --- counts (corrected state) ---
check('codes-524', len(codes) == 524, str(len(codes)))
check('links-525', len(links) == 525, str(len(links)))
bad = [c['code'] for c in codes if not re.match(r'^\d{4}$', c['code'])]
check('code-format', not bad, str(bad[:3]))
dang = [l for l in links if l['area_source_id'] not in byid]
check('no-dangling', not dang, str(dang[:3]))
from collections import Counter
prim = Counter(l['postcode'] for l in links if l['is_primary'] == 'true')
multi = [pc for pc, c in prim.items() if c != 1]
check('exactly-one-primary', len(prim) == 524 and not multi,
      f'primaries={len(prim)} multi={multi[:3]}')
# --- per-municipality primary counts (corrected; 61/61 covered) ---
expect = {
          'belsh': 4,
          'berat': 12,
          'bulqize': 9,
          'cerrik': 4,
          'delvine': 4,
          'devoll': 7,
          'diber': 15,
          'dimal': 6,
          'divjake': 6,
          'dropull': 5,
          'durres': 16,
          'elbasan': 19,
          'fier': 18,
          'finiq': 6,
          'fushe-arrez': 5,
          'gjirokaster': 11,
          'gramsh': 10,
          'has': 5,
          'himare': 9,
          'kamez': 5,
          'kavaje': 6,
          'kelcyre': 3,
          'klos': 6,
          'kolonje': 6,
          'konispol': 4,
          'korce': 13,
          'kruje': 8,
          'kucove': 9,
          'kukes': 20,
          'kurbin': 6,
          'lezhe': 11,
          'libohove': 3,
          'librazhd': 7,
          'lushnje': 16,
          'malesi-e-madhe': 6,
          'maliq': 8,
          'mallakaster': 9,
          'mat': 8,
          'memaliaj': 7,
          'mirdite': 8,
          'patos': 3,
          'peqin': 6,
          'permet': 6,
          'pogradec': 10,
          'polican': 5,
          'prrenjas': 6,
          'puke': 5,
          'pustec': 1,
          'roskovec': 5,
          'rrogozhine': 5,
          'sarande': 4,
          'selenice': 8,
          'shijak': 6,
          'shkoder': 17,
          'skrapar': 11,
          'tepelene': 4,
          'tirana': 47,
          'tropoje': 6,
          'vau-i-dejes': 12,
          'vlore': 13,
          'vore': 4,
}
have = Counter()
for l in links:
    if l['is_primary'] == 'true':
        have[l['area_source_id'].split(':')[-1]] += 1
for slug, n in expect.items():
    check(f'count-{slug}-{n}', have[slug] == n, str(have[slug]))
check('zero-codeless', set(expect) == set(have))
# --- 1029 dual: Kamez primary + Tirana secondary (pinned, keep) ---
got = sorted((l['area_source_id'].split(':')[-1], l['is_primary'])
             for l in links if l['postcode'] == '1029')
check('dual-1029', got == [('kamez', 'true'), ('tirana', 'false')], str(got))
counts = Counter(l['postcode'] for l in links)
check('single-dual', sorted(pc for pc, c in counts.items() if c > 1) == ['1029'],
      str(sorted(pc for pc, c in counts.items() if c > 1)))
# --- drop: 8707 gone; weak keep 8520 still Kukes ---
check('drop-8707', '8707' not in {c['code'] for c in codes})
plink = {l['postcode']: l['area_source_id'] for l in links
         if l['is_primary'] == 'true'}
check('keep-8520-kukes', plink.get('8520') == 'al:municipality:kukes', str(plink.get('8520')))
# --- 36 fills (corrected primaries) ---
fills = {
         '3301': 'gramsh',
         '3302': 'gramsh',
         '3303': 'gramsh',
         '3304': 'gramsh',
         '3305': 'gramsh',
         '3306': 'gramsh',
         '3307': 'gramsh',
         '3308': 'gramsh',
         '3309': 'gramsh',
         '3310': 'gramsh',
         '3501': 'peqin',
         '3502': 'peqin',
         '3503': 'peqin',
         '3504': 'peqin',
         '3505': 'peqin',
         '3506': 'peqin',
         '6301': 'tepelene',
         '6302': 'memaliaj',
         '6303': 'tepelene',
         '6304': 'memaliaj',
         '6305': 'tepelene',
         '6306': 'memaliaj',
         '6307': 'memaliaj',
         '6308': 'memaliaj',
         '6309': 'memaliaj',
         '6310': 'memaliaj',
         '6311': 'tepelene',
         '6401': 'permet',
         '6402': 'kelcyre',
         '6403': 'permet',
         '6404': 'permet',
         '6405': 'permet',
         '6406': 'kelcyre',
         '6407': 'kelcyre',
         '6408': 'permet',
         '6409': 'permet',
}
for pc, slug in fills.items():
    want = f'al:municipality:{slug}'
    check(f'fill-{pc}-{slug}', plink.get(pc) == want, str(plink.get(pc)))
# --- 138 retarget anchors (corrected primaries) ---
fixes = {
         '2013': 'shijak',
         '2014': 'shijak',
         '2018': 'shijak',
         '2019': 'shijak',
         '2020': 'shijak',
         '2022': 'shijak',
         '2503': 'rrogozhine',
         '2507': 'rrogozhine',
         '2508': 'rrogozhine',
         '2510': 'rrogozhine',
         '2511': 'rrogozhine',
         '3007': 'cerrik',
         '3008': 'belsh',
         '3017': 'cerrik',
         '3018': 'cerrik',
         '3020': 'cerrik',
         '3021': 'belsh',
         '3022': 'belsh',
         '3023': 'belsh',
         '3403': 'prrenjas',
         '3404': 'prrenjas',
         '3405': 'prrenjas',
         '3406': 'prrenjas',
         '3407': 'prrenjas',
         '3413': 'prrenjas',
         '4008': 'vau-i-dejes',
         '4013': 'vau-i-dejes',
         '4014': 'vau-i-dejes',
         '4021': 'vau-i-dejes',
         '4022': 'vau-i-dejes',
         '4023': 'vau-i-dejes',
         '4024': 'vau-i-dejes',
         '4025': 'vau-i-dejes',
         '4026': 'vau-i-dejes',
         '4027': 'vau-i-dejes',
         '4028': 'vau-i-dejes',
         '4029': 'vau-i-dejes',
         '4030': 'fushe-arrez',
         '4402': 'fushe-arrez',
         '4403': 'fushe-arrez',
         '4404': 'fushe-arrez',
         '4406': 'fushe-arrez',
         '5007': 'dimal',
         '5008': 'dimal',
         '5009': 'dimal',
         '5013': 'kucove',
         '5015': 'polican',
         '5016': 'polican',
         '5017': 'polican',
         '5018': 'dimal',
         '5019': 'dimal',
         '5022': 'dimal',
         '5403': 'polican',
         '5404': 'polican',
         '6003': 'libohove',
         '6005': 'dropull',
         '6006': 'dropull',
         '6007': 'dropull',
         '6010': 'dropull',
         '6011': 'dropull',
         '6012': 'libohove',
         '6016': 'libohove',
         '7005': 'maliq',
         '7006': 'devoll',
         '7007': 'devoll',
         '7008': 'devoll',
         '7009': 'devoll',
         '7010': 'devoll',
         '7011': 'devoll',
         '7012': 'devoll',
         '7014': 'maliq',
         '7015': 'maliq',
         '7016': 'maliq',
         '7018': 'maliq',
         '7020': 'pustec',
         '7021': 'maliq',
         '7027': 'maliq',
         '7028': 'maliq',
         '8002': 'klos',
         '8006': 'klos',
         '8007': 'klos',
         '8008': 'klos',
         '8013': 'klos',
         '8014': 'klos',
         '9004': 'divjake',
         '9011': 'divjake',
         '9014': 'divjake',
         '9015': 'divjake',
         '9021': 'divjake',
         '9022': 'divjake',
         '9306': 'roskovec',
         '9307': 'patos',
         '9308': 'mallakaster',
         '9312': 'patos',
         '9315': 'roskovec',
         '9316': 'roskovec',
         '9317': 'patos',
         '9319': 'roskovec',
         '9320': 'roskovec',
         '9328': 'mallakaster',
         '9329': 'mallakaster',
         '9330': 'mallakaster',
         '9331': 'mallakaster',
         '9332': 'mallakaster',
         '9333': 'mallakaster',
         '9334': 'mallakaster',
         '9335': 'mallakaster',
         '9407': 'selenice',
         '9408': 'selenice',
         '9409': 'selenice',
         '9410': 'selenice',
         '9412': 'selenice',
         '9413': 'himare',
         '9416': 'himare',
         '9417': 'himare',
         '9418': 'himare',
         '9421': 'selenice',
         '9422': 'himare',
         '9424': 'selenice',
         '9425': 'himare',
         '9427': 'selenice',
         '9704': 'delvine',
         '9705': 'konispol',
         '9707': 'konispol',
         '9708': 'konispol',
         '9709': 'konispol',
         '9710': 'finiq',
         '9711': 'finiq',
         '9712': 'finiq',
         '9713': 'himare',
         '9714': 'himare',
         '9715': 'himare',
         '9716': 'finiq',
         '9717': 'finiq',
         '9718': 'delvine',
         '9719': 'delvine',
         '9720': 'delvine',
         '9721': 'finiq',
}
for pc, slug in fixes.items():
    want = f'al:municipality:{slug}'
    check(f'fix-{pc}-{slug}', plink.get(pc) == want, str(plink.get(pc)))
# --- corroborated keep anchors (homonyms + specials) ---
keeps = {
         '1001': 'tirana',
         '1028': 'tirana',
         '1030': 'kamez',
         '1031': 'kamez',
         '1032': 'vore',
         '1033': 'vore',
         '1039': 'vore',
         '1046': 'tirana',
         '1047': 'kamez',
         '1053': 'vore',
         '1054': 'kamez',
         '1502': 'kruje',
         '1507': 'kruje',
         '1700': 'tirana',
         '1800': 'tirana',
         '2012': 'durres',
         '2015': 'durres',
         '2016': 'durres',
         '2017': 'durres',
         '2021': 'durres',
         '2504': 'kavaje',
         '3001': 'elbasan',
         '3013': 'elbasan',
         '3019': 'elbasan',
         '3025': 'elbasan',
         '3401': 'librazhd',
         '3408': 'librazhd',
         '3412': 'librazhd',
         '4001': 'shkoder',
         '4009': 'shkoder',
         '4012': 'shkoder',
         '4015': 'shkoder',
         '4017': 'shkoder',
         '4019': 'shkoder',
         '4301': 'malesi-e-madhe',
         '4401': 'puke',
         '4405': 'puke',
         '4409': 'puke',
         '4501': 'lezhe',
         '4506': 'lezhe',
         '4511': 'lezhe',
         '4604': 'mirdite',
         '4701': 'kurbin',
         '5001': 'berat',
         '5010': 'berat',
         '5020': 'berat',
         '5021': 'berat',
         '5301': 'kucove',
         '5307': 'kucove',
         '5401': 'skrapar',
         '5410': 'skrapar',
         '5411': 'skrapar',
         '5412': 'skrapar',
         '6001': 'gjirokaster',
         '6004': 'gjirokaster',
         '6008': 'gjirokaster',
         '6009': 'gjirokaster',
         '6013': 'gjirokaster',
         '6014': 'gjirokaster',
         '6015': 'gjirokaster',
         '6018': 'gjirokaster',
         '6019': 'gjirokaster',
         '7001': 'korce',
         '7013': 'korce',
         '7019': 'korce',
         '7024': 'korce',
         '7301': 'pogradec',
         '7401': 'kolonje',
         '7402': 'kolonje',
         '8001': 'mat',
         '8011': 'mat',
         '8301': 'diber',
         '8401': 'bulqize',
         '8408': 'bulqize',
         '8409': 'bulqize',
         '8501': 'kukes',
         '8511': 'kukes',
         '8519': 'kukes',
         '8520': 'kukes',
         '8601': 'has',
         '8701': 'tropoje',
         '8706': 'tropoje',
         '9001': 'lushnje',
         '9003': 'lushnje',
         '9018': 'lushnje',
         '9019': 'lushnje',
         '9020': 'lushnje',
         '9301': 'fier',
         '9321': 'fier',
         '9326': 'fier',
         '9327': 'fier',
         '9401': 'vlore',
         '9406': 'vlore',
         '9411': 'vlore',
         '9414': 'vlore',
         '9419': 'vlore',
         '9420': 'vlore',
         '9423': 'vlore',
         '9426': 'vlore',
         '9701': 'sarande',
         '9706': 'sarande',
}
for pc, slug in keeps.items():
    want = f'al:municipality:{slug}'
    check(f'keep-{pc}-{slug}', plink.get(pc) == want, str(plink.get(pc)))
print('ALL PASS' if not fails else f'{len(fails)} FAILURES')
sys.exit(1 if fails else 0)
