import csv, re, sys
# United Kingdom gate. Pins the B13 fix-and-fill pass (2943 codes / 3750 links,
# 687 multi-L2 outwards) plus the tree (4 nations + 48 English ceremonial counties
# + 32 Scottish councils + 22 Welsh principal areas + 11 NI districts).
# Oracles: ONS NSPL August 2026 (unit-postcode LAD/ward/usertype/dointr, 1.81M live),
# Lieutenancies Act 1997 Sch 1 (unitary->ceremonial + Tees split rule), ONS LAD/CTY/CTRY
# lookups, OSM River Tees centreline geometry (point-vs-river side test, 15/15 anchors),
# GeoNames GB postal dump (27,450 place rows, 3002 outwards), postcodes.io live outcode
# arrays (46 exemplars), Wikipedia postcode-area/village pages + addressed sightings for
# E22/MK20 fills. Run from repo root: python3 docs/agents/audit/gate_gb.py
# (optional argv: <geography-dir> to check a simulated tree).
import os
D = sys.argv[1] if len(sys.argv) > 1 else './packages/addressing/resources/geography'
A = os.path.join(D, 'united-kingdom-address-areas.csv')
C = os.path.join(D, 'united-kingdom-postal-codes.csv')
L = os.path.join(D, 'united-kingdom-postal-code-areas.csv')
fails = []
def check(name, cond, detail=''):
    print(('PASS' if cond else 'FAIL'), name, detail)
    if not cond:
        fails.append(name)
try:
    rows = list(csv.DictReader(open(A)))
    codes = list(csv.DictReader(open(C)))
    links = list(csv.DictReader(open(L)))
except FileNotFoundError as e:
    check('files-present', False, str(e))
    print(f'{len(fails)} FAILURES')
    sys.exit(1)
byid = {r['source_id']: r for r in rows}
# --- tree: 4 nations + 113 L2 ---
check('areas-117', len(rows) == 117, str(len(rows)))
check('nations-4', sum(1 for r in rows if r['type'] == 'nation') == 4)
check('counties-59', sum(1 for r in rows if r['type'] == 'county') == 59)
check('councils-32', sum(1 for r in rows if r['type'] == 'council_area') == 32)
check('cboroughs-11', sum(1 for r in rows if r['type'] == 'county_borough') == 11)
check('districts-11', sum(1 for r in rows if r['type'] == 'district') == 11)
eng = [r for r in rows if r['parent_source_id'] == 'gb:nation:england']
sct = [r for r in rows if r['parent_source_id'] == 'gb:nation:scotland']
wls = [r for r in rows if r['parent_source_id'] == 'gb:nation:wales']
nir = [r for r in rows if r['parent_source_id'] == 'gb:nation:northern-ireland']
check('eng-48', len(eng) == 48, str(len(eng)))
check('sct-32', len(sct) == 32, str(len(sct)))
check('wls-22', len(wls) == 22, str(len(wls)))
check('nir-11', len(nir) == 11, str(len(nir)))
nat = {'gb:nation:england': ('England', 'ENG'), 'gb:nation:scotland': ('Scotland', 'SCT'),
       'gb:nation:wales': ('Wales', 'WLS'), 'gb:nation:northern-ireland': ('Northern Ireland', 'NIR')}
for sid, (name, code) in nat.items():
    r = byid.get(sid)
    check(f'nation-{code}', bool(r) and r['name'] == name and r['code'] == code
          and r['level'] == '1' and r['parent_source_id'] == '', str(r))
# B13 renames: Orkney Islands per ONS LAD S12000023 + ISO GB-ORK; Na h-Eileanan Siar
# per ONS LAD S12000013 exact (ISO GB-ELS reads 'Eilean Siar', its short form) with
# the GN postal dump's 232 'Western Isles' rows confirming the parenthetical is legacy.
# (Worker prose cited GB-EAY; that is East Ayrshire and is not repeated here.)
check('rename-orkney', byid.get('gb:council_area:orkney', {}).get('name') == 'Orkney Islands',
      str(byid.get('gb:council_area:orkney')))
check('rename-eileanan', byid.get('gb:council_area:na-h-eileanan-siar-western-isles', {}).get('name') == 'Na h-Eileanan Siar',
      str(byid.get('gb:council_area:na-h-eileanan-siar-western-isles')))
spots = {'gb:county:greater-london': ('Greater London', 'gb:nation:england'),
         'gb:county:city-of-london': ('City of London', 'gb:nation:england'),
         'gb:county:bristol': ('Bristol', 'gb:nation:england'),
         'gb:county:east-riding-of-yorkshire': ('East Riding of Yorkshire', 'gb:nation:england'),
         'gb:county:isle-of-wight': ('Isle of Wight', 'gb:nation:england'),
         'gb:council_area:aberdeen-city': ('Aberdeen City', 'gb:nation:scotland'),
         'gb:council_area:shetland-islands': ('Shetland Islands', 'gb:nation:scotland'),
         'gb:county:cardiff': ('Cardiff', 'gb:nation:wales'),
         'gb:county_borough:newport': ('Newport', 'gb:nation:wales'),
         'gb:district:belfast': ('Belfast', 'gb:nation:northern-ireland'),
         'gb:district:armagh-city-banbridge-and-craigavon': ('Armagh City, Banbridge and Craigavon', 'gb:nation:northern-ireland'),
         'gb:district:newry-mourne-and-down': ('Newry, Mourne and Down', 'gb:nation:northern-ireland'),
         'gb:district:derry-city-and-strabane': ('Derry City and Strabane', 'gb:nation:northern-ireland')}
for sid, (name, par) in spots.items():
    r = byid.get(sid)
    check(f'spot-{sid.split(chr(58))[-1]}', bool(r) and r['name'] == name and r['level'] == '2'
          and r['parent_source_id'] == par, str(r))
orph = [r['source_id'] for r in rows if r['parent_source_id'] and r['parent_source_id'] not in byid]
check('no-orphans', not orph, str(orph[:3]))
check('l1-no-parents', all(r['parent_source_id'] == '' for r in rows if r['level'] == '1'))
# --- postal counts: 2943 codes / 3750 links (CRLF) ---
check('codes-2943', len(codes) == 2943, str(len(codes)))
check('links-3750', len(links) == 3750, str(len(links)))
check('country-GB', all(c['country_code'] == 'GB' for c in codes))
bad = [c['code'] for c in codes if not re.match(r'^[A-Z]{1,2}[0-9]{1,2}[A-Z]?$', c['code'])]
check('code-format-outward', not bad, str(bad[:3]))
check('codes-unique', len({c['code'] for c in codes}) == 2943)
check('codes-sorted', [c['code'] for c in codes] == sorted(c['code'] for c in codes))
lkeys = [(l['postcode'], l['area_source_id']) for l in links]
check('links-sorted', lkeys == sorted(lkeys))
dang = [l for l in links if l['area_source_id'] not in byid]
check('no-dangling', not dang, str(dang[:3]))
badrel = [l for l in links if l['relationship_type'] != 'served_by' or l['is_primary'] not in ('true', 'false')]
check('link-shape', not badrel, str(badrel[:3]))
from collections import Counter
prim = Counter(l['postcode'] for l in links if l['is_primary'] == 'true')
multi = [pc for pc, c in prim.items() if c != 1]
check('exactly-one-primary', len(prim) == 2943 and not multi,
      f'primaries={len(prim)} multi={multi[:3]}')
check('every-code-linked', {c['code'] for c in codes} == {l['postcode'] for l in links})
counts = Counter(l['postcode'] for l in links)
nmulti = sorted(pc for pc, c in counts.items() if c > 1)
check('multi-687', len(nmulti) == 687, str(len(nmulti)))
legs = Counter(counts[pc] for pc in nmulti)
check('legs-574-107-5-1', legs[2] == 574 and legs[3] == 107 and legs[4] == 5 and legs[5] == 1, str(dict(legs)))
# --- full multi-leg table: code -> (primary, [secondaries]) ---
MULTI = {
 'AB12': ('gb:council_area:aberdeen-city', ['gb:council_area:aberdeenshire']),
 'AB14': ('gb:council_area:aberdeen-city', ['gb:council_area:aberdeenshire']),
 'AB15': ('gb:council_area:aberdeen-city', ['gb:council_area:aberdeenshire']),
 'AB21': ('gb:council_area:aberdeen-city', ['gb:council_area:aberdeenshire']),
 'AB23': ('gb:council_area:aberdeen-city', ['gb:council_area:aberdeenshire']),
 'AB30': ('gb:council_area:aberdeenshire', ['gb:council_area:angus']),
 'AB31': ('gb:council_area:aberdeenshire', ['gb:council_area:aberdeen-city']),
 'AB32': ('gb:council_area:aberdeenshire', ['gb:council_area:aberdeen-city']),
 'AB37': ('gb:council_area:moray', ['gb:council_area:highland']),
 'AB45': ('gb:council_area:aberdeenshire', ['gb:council_area:moray']),
 'AB54': ('gb:council_area:aberdeenshire', ['gb:council_area:moray']),
 'AB55': ('gb:council_area:moray', ['gb:council_area:aberdeenshire']),
 'AB56': ('gb:council_area:moray', ['gb:council_area:aberdeenshire']),
 'AL3': ('gb:county:hertfordshire', ['gb:county:bedfordshire']),
 'AL5': ('gb:county:hertfordshire', ['gb:county:bedfordshire']),
 'B14': ('gb:county:west-midlands', ['gb:county:worcestershire']),
 'B31': ('gb:county:west-midlands', ['gb:county:worcestershire']),
 'B32': ('gb:county:west-midlands', ['gb:county:worcestershire']),
 'B38': ('gb:county:west-midlands', ['gb:county:worcestershire']),
 'B45': ('gb:county:west-midlands', ['gb:county:worcestershire']),
 'B47': ('gb:county:worcestershire', ['gb:county:warwickshire', 'gb:county:west-midlands']),
 'B48': ('gb:county:worcestershire', ['gb:county:warwickshire']),
 'B49': ('gb:county:warwickshire', ['gb:county:worcestershire']),
 'B62': ('gb:county:west-midlands', ['gb:county:worcestershire']),
 'B74': ('gb:county:west-midlands', ['gb:county:staffordshire']),
 'B75': ('gb:county:west-midlands', ['gb:county:staffordshire', 'gb:county:warwickshire']),
 'B76': ('gb:county:west-midlands', ['gb:county:warwickshire']),
 'B78': ('gb:county:warwickshire', ['gb:county:staffordshire']),
 'B79': ('gb:county:staffordshire', ['gb:county:leicestershire', 'gb:county:warwickshire']),
 'B90': ('gb:county:west-midlands', ['gb:county:worcestershire']),
 'B93': ('gb:county:west-midlands', ['gb:county:warwickshire']),
 'B94': ('gb:county:warwickshire', ['gb:county:west-midlands']),
 'B96': ('gb:county:worcestershire', ['gb:county:warwickshire']),
 'B97': ('gb:county:worcestershire', ['gb:county:warwickshire']),
 'B98': ('gb:county:worcestershire', ['gb:county:warwickshire']),
 'BA1': ('gb:county:somerset', ['gb:county:gloucestershire']),
 'BA11': ('gb:county:somerset', ['gb:county:wiltshire']),
 'BA13': ('gb:county:wiltshire', ['gb:county:somerset']),
 'BA15': ('gb:county:wiltshire', ['gb:county:somerset']),
 'BA2': ('gb:county:somerset', ['gb:county:wiltshire']),
 'BA21': ('gb:county:somerset', ['gb:county:dorset']),
 'BA22': ('gb:county:somerset', ['gb:county:dorset']),
 'BA8': ('gb:county:somerset', ['gb:county:dorset']),
 'BB18': ('gb:county:lancashire', ['gb:county:north-yorkshire']),
 'BD20': ('gb:county:west-yorkshire', ['gb:county:north-yorkshire']),
 'BD22': ('gb:county:west-yorkshire', ['gb:county:north-yorkshire']),
 'BD23': ('gb:county:north-yorkshire', ['gb:county:lancashire']),
 'BH23': ('gb:county:dorset', ['gb:county:hampshire']),
 'BH24': ('gb:county:hampshire', ['gb:county:dorset']),
 'BH31': ('gb:county:dorset', ['gb:county:hampshire']),
 'BL0': ('gb:county:greater-manchester', ['gb:county:lancashire']),
 'BL6': ('gb:county:greater-manchester', ['gb:county:lancashire']),
 'BL7': ('gb:county:greater-manchester', ['gb:county:lancashire']),
 'BL8': ('gb:county:greater-manchester', ['gb:county:lancashire']),
 'BL9': ('gb:county:greater-manchester', ['gb:county:lancashire']),
 'BN41': ('gb:county:east-sussex', ['gb:county:west-sussex']),
 'BN42': ('gb:county:west-sussex', ['gb:county:east-sussex']),
 'BN6': ('gb:county:west-sussex', ['gb:county:east-sussex']),
 'BR6': ('gb:county:greater-london', ['gb:county:kent']),
 'BR8': ('gb:county:kent', ['gb:county:greater-london']),
 'BS10': ('gb:county:bristol', ['gb:county:gloucestershire']),
 'BS13': ('gb:county:bristol', ['gb:county:somerset']),
 'BS14': ('gb:county:bristol', ['gb:county:somerset']),
 'BS15': ('gb:county:gloucestershire', ['gb:county:bristol']),
 'BS16': ('gb:county:gloucestershire', ['gb:county:bristol']),
 'BS3': ('gb:county:bristol', ['gb:county:somerset']),
 'BS31': ('gb:county:somerset', ['gb:county:bristol', 'gb:county:gloucestershire']),
 'BS7': ('gb:county:bristol', ['gb:county:gloucestershire']),
 'BS8': ('gb:county:bristol', ['gb:county:somerset']),
 'BT14': ('gb:district:belfast', ['gb:district:antrim-and-newtownabbey']),
 'BT16': ('gb:district:lisburn-and-castlereagh', ['gb:district:ards-and-north-down', 'gb:district:belfast']),
 'BT17': ('gb:district:belfast', ['gb:district:lisburn-and-castlereagh']),
 'BT18': ('gb:district:ards-and-north-down', ['gb:district:belfast', 'gb:district:lisburn-and-castlereagh']),
 'BT23': ('gb:district:ards-and-north-down', ['gb:district:lisburn-and-castlereagh', 'gb:district:newry-mourne-and-down']),
 'BT24': ('gb:district:newry-mourne-and-down', ['gb:district:ards-and-north-down', 'gb:district:lisburn-and-castlereagh']),
 'BT25': ('gb:district:armagh-city-banbridge-and-craigavon', ['gb:district:lisburn-and-castlereagh', 'gb:district:newry-mourne-and-down']),
 'BT29': ('gb:district:antrim-and-newtownabbey', ['gb:district:lisburn-and-castlereagh']),
 'BT30': ('gb:district:newry-mourne-and-down', ['gb:district:ards-and-north-down']),
 'BT31': ('gb:district:newry-mourne-and-down', ['gb:district:armagh-city-banbridge-and-craigavon']),
 'BT32': ('gb:district:armagh-city-banbridge-and-craigavon', ['gb:district:newry-mourne-and-down']),
 'BT34': ('gb:district:newry-mourne-and-down', ['gb:district:armagh-city-banbridge-and-craigavon']),
 'BT35': ('gb:district:newry-mourne-and-down', ['gb:district:armagh-city-banbridge-and-craigavon']),
 'BT36': ('gb:district:antrim-and-newtownabbey', ['gb:district:belfast', 'gb:district:mid-and-east-antrim']),
 'BT38': ('gb:district:mid-and-east-antrim', ['gb:district:antrim-and-newtownabbey']),
 'BT39': ('gb:district:antrim-and-newtownabbey', ['gb:district:mid-and-east-antrim']),
 'BT41': ('gb:district:antrim-and-newtownabbey', ['gb:district:mid-and-east-antrim', 'gb:district:mid-ulster']),
 'BT42': ('gb:district:mid-and-east-antrim', ['gb:district:antrim-and-newtownabbey']),
 'BT44': ('gb:district:causeway-coast-and-glens', ['gb:district:mid-and-east-antrim', 'gb:district:mid-ulster']),
 'BT46': ('gb:district:mid-ulster', ['gb:district:causeway-coast-and-glens']),
 'BT47': ('gb:district:derry-city-and-strabane', ['gb:district:causeway-coast-and-glens']),
 'BT5': ('gb:district:belfast', ['gb:district:lisburn-and-castlereagh']),
 'BT51': ('gb:district:causeway-coast-and-glens', ['gb:district:mid-ulster']),
 'BT6': ('gb:district:belfast', ['gb:district:lisburn-and-castlereagh']),
 'BT60': ('gb:district:armagh-city-banbridge-and-craigavon', ['gb:district:newry-mourne-and-down']),
 'BT66': ('gb:district:armagh-city-banbridge-and-craigavon', ['gb:district:lisburn-and-castlereagh']),
 'BT67': ('gb:district:armagh-city-banbridge-and-craigavon', ['gb:district:lisburn-and-castlereagh']),
 'BT70': ('gb:district:mid-ulster', ['gb:district:fermanagh-and-omagh']),
 'BT71': ('gb:district:mid-ulster', ['gb:district:armagh-city-banbridge-and-craigavon']),
 'BT75': ('gb:district:mid-ulster', ['gb:district:fermanagh-and-omagh']),
 'BT76': ('gb:district:mid-ulster', ['gb:district:fermanagh-and-omagh']),
 'BT78': ('gb:district:fermanagh-and-omagh', ['gb:district:derry-city-and-strabane', 'gb:district:mid-ulster']),
 'BT79': ('gb:district:fermanagh-and-omagh', ['gb:district:derry-city-and-strabane', 'gb:district:mid-ulster']),
 'BT8': ('gb:district:lisburn-and-castlereagh', ['gb:district:belfast']),
 'BT81': ('gb:district:derry-city-and-strabane', ['gb:district:fermanagh-and-omagh']),
 'CA8': ('gb:county:cumbria', ['gb:county:northumberland']),
 'CA9': ('gb:county:cumbria', ['gb:county:northumberland']),
 'CB10': ('gb:county:essex', ['gb:county:cambridgeshire']),
 'CB21': ('gb:county:cambridgeshire', ['gb:county:essex']),
 'CB8': ('gb:county:suffolk', ['gb:county:cambridgeshire']),
 'CB9': ('gb:county:suffolk', ['gb:county:essex']),
 'CF11': ('gb:county:cardiff', ['gb:county_borough:vale-of-glamorgan']),
 'CF14': ('gb:county:cardiff', ['gb:county_borough:caerphilly']),
 'CF15': ('gb:county:cardiff', ['gb:county_borough:caerphilly', 'gb:county_borough:rhondda-cynon-taf']),
 'CF3': ('gb:county:cardiff', ['gb:county_borough:caerphilly', 'gb:county_borough:newport']),
 'CF32': ('gb:county_borough:bridgend', ['gb:county_borough:vale-of-glamorgan']),
 'CF33': ('gb:county_borough:bridgend', ['gb:county_borough:neath-port-talbot']),
 'CF35': ('gb:county_borough:bridgend', ['gb:county_borough:rhondda-cynon-taf', 'gb:county_borough:vale-of-glamorgan']),
 'CF37': ('gb:county_borough:rhondda-cynon-taf', ['gb:county_borough:caerphilly']),
 'CF39': ('gb:county_borough:rhondda-cynon-taf', ['gb:county_borough:bridgend']),
 'CF44': ('gb:county_borough:rhondda-cynon-taf', ['gb:county:powys', 'gb:county_borough:merthyr-tydfil']),
 'CF46': ('gb:county_borough:merthyr-tydfil', ['gb:county_borough:caerphilly']),
 'CF48': ('gb:county_borough:merthyr-tydfil', ['gb:county:powys', 'gb:county_borough:caerphilly', 'gb:county_borough:rhondda-cynon-taf']),
 'CF5': ('gb:county:cardiff', ['gb:county_borough:vale-of-glamorgan']),
 'CF72': ('gb:county_borough:rhondda-cynon-taf', ['gb:county:cardiff', 'gb:county_borough:bridgend', 'gb:county_borough:vale-of-glamorgan']),
 'CF83': ('gb:county_borough:caerphilly', ['gb:county:cardiff', 'gb:county_borough:rhondda-cynon-taf']),
 'CH1': ('gb:county:cheshire', ['gb:county:flintshire']),
 'CH4': ('gb:county:cheshire', ['gb:county:flintshire']),
 'CH62': ('gb:county:merseyside', ['gb:county:cheshire']),
 'CH64': ('gb:county:cheshire', ['gb:county:merseyside']),
 'CH65': ('gb:county:cheshire', ['gb:county:merseyside']),
 'CH7': ('gb:county:flintshire', ['gb:county:denbighshire']),
 'CH8': ('gb:county:flintshire', ['gb:county:denbighshire']),
 'CM13': ('gb:county:essex', ['gb:county:greater-london']),
 'CM14': ('gb:county:essex', ['gb:county:greater-london']),
 'CM20': ('gb:county:essex', ['gb:county:hertfordshire']),
 'CM21': ('gb:county:hertfordshire', ['gb:county:essex']),
 'CM23': ('gb:county:hertfordshire', ['gb:county:essex']),
 'CO10': ('gb:county:suffolk', ['gb:county:essex']),
 'CO11': ('gb:county:essex', ['gb:county:suffolk']),
 'CO6': ('gb:county:essex', ['gb:county:suffolk']),
 'CO7': ('gb:county:essex', ['gb:county:suffolk']),
 'CO8': ('gb:county:essex', ['gb:county:suffolk']),
 'CR3': ('gb:county:surrey', ['gb:county:greater-london']),
 'CR5': ('gb:county:greater-london', ['gb:county:surrey']),
 'CR6': ('gb:county:surrey', ['gb:county:greater-london']),
 'CR8': ('gb:county:greater-london', ['gb:county:surrey']),
 'CV10': ('gb:county:warwickshire', ['gb:county:leicestershire']),
 'CV11': ('gb:county:warwickshire', ['gb:county:leicestershire']),
 'CV2': ('gb:county:west-midlands', ['gb:county:warwickshire']),
 'CV23': ('gb:county:warwickshire', ['gb:county:northamptonshire']),
 'CV3': ('gb:county:west-midlands', ['gb:county:warwickshire']),
 'CV37': ('gb:county:warwickshire', ['gb:county:worcestershire']),
 'CV4': ('gb:county:west-midlands', ['gb:county:warwickshire']),
 'CV6': ('gb:county:west-midlands', ['gb:county:warwickshire']),
 'CV7': ('gb:county:warwickshire', ['gb:county:west-midlands']),
 'CV8': ('gb:county:warwickshire', ['gb:county:west-midlands']),
 'CV9': ('gb:county:warwickshire', ['gb:county:leicestershire']),
 'CW12': ('gb:county:cheshire', ['gb:county:staffordshire']),
 'CW2': ('gb:county:cheshire', ['gb:county:staffordshire']),
 'CW3': ('gb:county:cheshire', ['gb:county:shropshire', 'gb:county:staffordshire']),
 'DA1': ('gb:county:kent', ['gb:county:greater-london']),
 'DA14': ('gb:county:greater-london', ['gb:county:kent']),
 'DA17': ('gb:county:greater-london', ['gb:county:kent']),
 'DA5': ('gb:county:greater-london', ['gb:county:kent']),
 'DD10': ('gb:council_area:angus', ['gb:council_area:aberdeenshire']),
 'DD2': ('gb:council_area:dundee-city', ['gb:council_area:angus', 'gb:council_area:perth-and-kinross']),
 'DD3': ('gb:council_area:dundee-city', ['gb:council_area:angus']),
 'DD4': ('gb:council_area:dundee-city', ['gb:council_area:angus']),
 'DD5': ('gb:council_area:dundee-city', ['gb:council_area:angus']),
 'DD9': ('gb:council_area:angus', ['gb:council_area:aberdeenshire']),
 'DE11': ('gb:county:derbyshire', ['gb:county:leicestershire']),
 'DE12': ('gb:county:leicestershire', ['gb:county:derbyshire']),
 'DE13': ('gb:county:staffordshire', ['gb:county:derbyshire']),
 'DE15': ('gb:county:staffordshire', ['gb:county:derbyshire']),
 'DE6': ('gb:county:derbyshire', ['gb:county:staffordshire']),
 'DE73': ('gb:county:derbyshire', ['gb:county:leicestershire']),
 'DE74': ('gb:county:leicestershire', ['gb:county:derbyshire']),
 'DG14': ('gb:council_area:dumfries-and-galloway', ['gb:council_area:scottish-borders']),
 'DG16': ('gb:council_area:dumfries-and-galloway', ['gb:county:cumbria']),
 'DG8': ('gb:council_area:dumfries-and-galloway', ['gb:council_area:south-ayrshire']),
 'DH2': ('gb:county:durham', ['gb:county:tyne-and-wear']),
 'DH3': ('gb:county:durham', ['gb:county:tyne-and-wear']),
 'DH4': ('gb:county:tyne-and-wear', ['gb:county:durham']),
 'DH5': ('gb:county:tyne-and-wear', ['gb:county:durham']),
 'DH8': ('gb:county:durham', ['gb:county:northumberland']),
 'DH9': ('gb:county:durham', ['gb:county:tyne-and-wear']),
 'DL11': ('gb:county:north-yorkshire', ['gb:county:durham']),
 'DL12': ('gb:county:durham', ['gb:county:cumbria', 'gb:county:north-yorkshire']),
 'DL2': ('gb:county:durham', ['gb:county:north-yorkshire']),
 'DN10': ('gb:county:nottinghamshire', ['gb:county:lincolnshire', 'gb:county:south-yorkshire']),
 'DN11': ('gb:county:south-yorkshire', ['gb:county:nottinghamshire']),
 'DN14': ('gb:county:east-riding-of-yorkshire', ['gb:county:lincolnshire', 'gb:county:north-yorkshire', 'gb:county:south-yorkshire']),
 'DN21': ('gb:county:lincolnshire', ['gb:county:nottinghamshire']),
 'DN6': ('gb:county:south-yorkshire', ['gb:county:north-yorkshire', 'gb:county:west-yorkshire']),
 'DN8': ('gb:county:south-yorkshire', ['gb:county:east-riding-of-yorkshire', 'gb:county:lincolnshire']),
 'DN9': ('gb:county:lincolnshire', ['gb:county:nottinghamshire', 'gb:county:south-yorkshire']),
 'DT10': ('gb:county:dorset', ['gb:county:somerset']),
 'DT7': ('gb:county:dorset', ['gb:county:devon']),
 'DT8': ('gb:county:dorset', ['gb:county:somerset']),
 'DT9': ('gb:county:dorset', ['gb:county:somerset']),
 'DY10': ('gb:county:worcestershire', ['gb:county:staffordshire']),
 'DY11': ('gb:county:worcestershire', ['gb:county:staffordshire']),
 'DY12': ('gb:county:worcestershire', ['gb:county:shropshire']),
 'DY14': ('gb:county:shropshire', ['gb:county:worcestershire']),
 'DY3': ('gb:county:west-midlands', ['gb:county:staffordshire']),
 'DY6': ('gb:county:west-midlands', ['gb:county:staffordshire']),
 'DY7': ('gb:county:staffordshire', ['gb:county:shropshire', 'gb:county:west-midlands']),
 'DY8': ('gb:county:west-midlands', ['gb:county:staffordshire', 'gb:county:worcestershire']),
 'DY9': ('gb:county:west-midlands', ['gb:county:worcestershire']),
 'E1': ('gb:county:greater-london', ['gb:county:city-of-london']),
 'E4': ('gb:county:greater-london', ['gb:county:essex']),
 'EC1A': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC1M': ('gb:county:greater-london', ['gb:county:city-of-london']),
 'EC1N': ('gb:county:greater-london', ['gb:county:city-of-london']),
 'EC1Y': ('gb:county:greater-london', ['gb:county:city-of-london']),
 'EC2A': ('gb:county:greater-london', ['gb:county:city-of-london']),
 'EC2M': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC2N': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC2P': ('gb:county:greater-london', ['gb:county:city-of-london']),
 'EC2R': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC2V': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC2Y': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC3A': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC3N': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC3P': ('gb:county:greater-london', ['gb:county:city-of-london']),
 'EC3R': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC3V': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC4A': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC4M': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC4N': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC4R': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC4V': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EC4Y': ('gb:county:city-of-london', ['gb:county:greater-london']),
 'EH10': ('gb:council_area:city-of-edinburgh', ['gb:council_area:midlothian']),
 'EH14': ('gb:council_area:city-of-edinburgh', ['gb:council_area:west-lothian']),
 'EH16': ('gb:council_area:city-of-edinburgh', ['gb:council_area:midlothian']),
 'EH17': ('gb:council_area:city-of-edinburgh', ['gb:council_area:midlothian']),
 'EH18': ('gb:council_area:midlothian', ['gb:council_area:city-of-edinburgh']),
 'EH21': ('gb:council_area:east-lothian', ['gb:council_area:city-of-edinburgh', 'gb:council_area:midlothian']),
 'EH22': ('gb:council_area:midlothian', ['gb:council_area:city-of-edinburgh', 'gb:council_area:east-lothian']),
 'EH23': ('gb:council_area:midlothian', ['gb:council_area:scottish-borders']),
 'EH26': ('gb:council_area:midlothian', ['gb:council_area:scottish-borders']),
 'EH27': ('gb:council_area:west-lothian', ['gb:council_area:city-of-edinburgh']),
 'EH28': ('gb:council_area:city-of-edinburgh', ['gb:council_area:west-lothian']),
 'EH29': ('gb:council_area:city-of-edinburgh', ['gb:council_area:west-lothian']),
 'EH30': ('gb:council_area:city-of-edinburgh', ['gb:council_area:west-lothian']),
 'EH37': ('gb:council_area:midlothian', ['gb:council_area:east-lothian', 'gb:council_area:scottish-borders']),
 'EH46': ('gb:council_area:scottish-borders', ['gb:council_area:midlothian', 'gb:council_area:south-lanarkshire']),
 'EH47': ('gb:council_area:west-lothian', ['gb:council_area:north-lanarkshire']),
 'EH49': ('gb:council_area:west-lothian', ['gb:council_area:falkirk']),
 'EH52': ('gb:council_area:west-lothian', ['gb:council_area:city-of-edinburgh']),
 'EH53': ('gb:council_area:west-lothian', ['gb:council_area:city-of-edinburgh']),
 'EH55': ('gb:council_area:west-lothian', ['gb:council_area:south-lanarkshire']),
 'EN10': ('gb:county:hertfordshire', ['gb:county:essex']),
 'EN11': ('gb:county:hertfordshire', ['gb:county:essex']),
 'EN2': ('gb:county:greater-london', ['gb:county:hertfordshire']),
 'EN4': ('gb:county:greater-london', ['gb:county:hertfordshire']),
 'EN5': ('gb:county:greater-london', ['gb:county:hertfordshire']),
 'EN6': ('gb:county:hertfordshire', ['gb:county:greater-london']),
 'EN7': ('gb:county:hertfordshire', ['gb:county:greater-london']),
 'EN8': ('gb:county:hertfordshire', ['gb:county:essex', 'gb:county:greater-london']),
 'EN9': ('gb:county:essex', ['gb:county:greater-london', 'gb:county:hertfordshire']),
 'EX13': ('gb:county:devon', ['gb:county:somerset']),
 'EX14': ('gb:county:devon', ['gb:county:somerset']),
 'EX16': ('gb:county:devon', ['gb:county:somerset']),
 'EX22': ('gb:county:devon', ['gb:county:cornwall']),
 'EX23': ('gb:county:cornwall', ['gb:county:devon']),
 'EX35': ('gb:county:devon', ['gb:county:somerset']),
 'EX36': ('gb:county:devon', ['gb:county:somerset']),
 'FK1': ('gb:council_area:falkirk', ['gb:council_area:north-lanarkshire', 'gb:council_area:west-lothian']),
 'FK10': ('gb:council_area:clackmannanshire', ['gb:council_area:fife']),
 'FK14': ('gb:council_area:clackmannanshire', ['gb:council_area:fife', 'gb:council_area:perth-and-kinross']),
 'FK15': ('gb:council_area:stirling', ['gb:council_area:perth-and-kinross']),
 'FK2': ('gb:council_area:falkirk', ['gb:council_area:stirling']),
 'FK20': ('gb:council_area:stirling', ['gb:council_area:argyll-and-bute']),
 'FK21': ('gb:council_area:stirling', ['gb:council_area:perth-and-kinross']),
 'FK4': ('gb:council_area:falkirk', ['gb:council_area:north-lanarkshire']),
 'FK5': ('gb:council_area:falkirk', ['gb:council_area:stirling']),
 'FK6': ('gb:council_area:falkirk', ['gb:council_area:north-lanarkshire', 'gb:council_area:stirling']),
 'FK7': ('gb:council_area:stirling', ['gb:council_area:falkirk']),
 'FK9': ('gb:council_area:stirling', ['gb:council_area:clackmannanshire']),
 'G13': ('gb:council_area:glasgow-city', ['gb:council_area:west-dunbartonshire']),
 'G14': ('gb:council_area:glasgow-city', ['gb:council_area:west-dunbartonshire']),
 'G33': ('gb:council_area:glasgow-city', ['gb:council_area:east-dunbartonshire', 'gb:council_area:north-lanarkshire']),
 'G44': ('gb:council_area:glasgow-city', ['gb:council_area:east-renfrewshire', 'gb:council_area:south-lanarkshire']),
 'G46': ('gb:council_area:east-renfrewshire', ['gb:council_area:glasgow-city']),
 'G51': ('gb:council_area:glasgow-city', ['gb:council_area:renfrewshire']),
 'G52': ('gb:council_area:glasgow-city', ['gb:council_area:renfrewshire']),
 'G53': ('gb:council_area:glasgow-city', ['gb:council_area:east-renfrewshire']),
 'G61': ('gb:council_area:east-dunbartonshire', ['gb:council_area:glasgow-city']),
 'G62': ('gb:council_area:east-dunbartonshire', ['gb:council_area:glasgow-city', 'gb:council_area:stirling']),
 'G63': ('gb:council_area:stirling', ['gb:council_area:argyll-and-bute', 'gb:council_area:west-dunbartonshire']),
 'G64': ('gb:council_area:east-dunbartonshire', ['gb:council_area:glasgow-city', 'gb:council_area:north-lanarkshire']),
 'G65': ('gb:council_area:north-lanarkshire', ['gb:council_area:east-dunbartonshire']),
 'G66': ('gb:council_area:east-dunbartonshire', ['gb:council_area:north-lanarkshire']),
 'G67': ('gb:council_area:north-lanarkshire', ['gb:council_area:falkirk']),
 'G68': ('gb:council_area:north-lanarkshire', ['gb:council_area:east-dunbartonshire', 'gb:council_area:falkirk']),
 'G69': ('gb:council_area:north-lanarkshire', ['gb:council_area:east-dunbartonshire', 'gb:council_area:glasgow-city']),
 'G71': ('gb:council_area:south-lanarkshire', ['gb:council_area:glasgow-city', 'gb:council_area:north-lanarkshire']),
 'G72': ('gb:council_area:south-lanarkshire', ['gb:council_area:glasgow-city']),
 'G73': ('gb:council_area:south-lanarkshire', ['gb:council_area:glasgow-city']),
 'G76': ('gb:council_area:east-renfrewshire', ['gb:council_area:glasgow-city', 'gb:council_area:south-lanarkshire']),
 'G77': ('gb:council_area:east-renfrewshire', ['gb:council_area:east-ayrshire']),
 'G78': ('gb:council_area:east-renfrewshire', ['gb:council_area:east-ayrshire', 'gb:council_area:glasgow-city', 'gb:council_area:north-ayrshire', 'gb:council_area:renfrewshire']),
 'G81': ('gb:council_area:west-dunbartonshire', ['gb:council_area:east-dunbartonshire']),
 'G82': ('gb:council_area:west-dunbartonshire', ['gb:council_area:argyll-and-bute']),
 'G83': ('gb:council_area:west-dunbartonshire', ['gb:council_area:argyll-and-bute', 'gb:council_area:stirling']),
 'GL17': ('gb:county:gloucestershire', ['gb:county:herefordshire']),
 'GL18': ('gb:county:gloucestershire', ['gb:county:herefordshire']),
 'GL19': ('gb:county:gloucestershire', ['gb:county:worcestershire']),
 'GL20': ('gb:county:gloucestershire', ['gb:county:worcestershire']),
 'GL56': ('gb:county:gloucestershire', ['gb:county:oxfordshire', 'gb:county:warwickshire']),
 'GL7': ('gb:county:gloucestershire', ['gb:county:oxfordshire', 'gb:county:wiltshire']),
 'GL8': ('gb:county:gloucestershire', ['gb:county:wiltshire']),
 'GL9': ('gb:county:gloucestershire', ['gb:county:wiltshire']),
 'GU10': ('gb:county:surrey', ['gb:county:hampshire']),
 'GU12': ('gb:county:surrey', ['gb:county:hampshire']),
 'GU15': ('gb:county:surrey', ['gb:county:berkshire']),
 'GU16': ('gb:county:surrey', ['gb:county:hampshire']),
 'GU19': ('gb:county:surrey', ['gb:county:berkshire']),
 'GU20': ('gb:county:surrey', ['gb:county:berkshire']),
 'GU26': ('gb:county:surrey', ['gb:county:hampshire']),
 'GU27': ('gb:county:surrey', ['gb:county:hampshire', 'gb:county:west-sussex']),
 'GU30': ('gb:county:hampshire', ['gb:county:west-sussex']),
 'GU31': ('gb:county:hampshire', ['gb:county:west-sussex']),
 'GU33': ('gb:county:hampshire', ['gb:county:west-sussex']),
 'GU46': ('gb:county:hampshire', ['gb:county:berkshire']),
 'HA5': ('gb:county:greater-london', ['gb:county:hertfordshire']),
 'HA6': ('gb:county:greater-london', ['gb:county:hertfordshire']),
 'HA7': ('gb:county:greater-london', ['gb:county:hertfordshire']),
 'HD8': ('gb:county:west-yorkshire', ['gb:county:south-yorkshire']),
 'HD9': ('gb:county:west-yorkshire', ['gb:county:south-yorkshire']),
 'HP14': ('gb:county:buckinghamshire', ['gb:county:oxfordshire']),
 'HP18': ('gb:county:buckinghamshire', ['gb:county:oxfordshire']),
 'HP23': ('gb:county:hertfordshire', ['gb:county:buckinghamshire']),
 'HP4': ('gb:county:hertfordshire', ['gb:county:bedfordshire', 'gb:county:buckinghamshire']),
 'HP5': ('gb:county:buckinghamshire', ['gb:county:hertfordshire']),
 'HP8': ('gb:county:buckinghamshire', ['gb:county:hertfordshire']),
 'HR3': ('gb:county:herefordshire', ['gb:county:powys']),
 'HR5': ('gb:county:herefordshire', ['gb:county:powys']),
 'HR7': ('gb:county:herefordshire', ['gb:county:worcestershire']),
 'HR8': ('gb:county:herefordshire', ['gb:county:gloucestershire', 'gb:county:worcestershire']),
 'HR9': ('gb:county:herefordshire', ['gb:county:gloucestershire']),
 'IG7': ('gb:county:essex', ['gb:county:greater-london']),
 'IG8': ('gb:county:greater-london', ['gb:county:essex']),
 'IG9': ('gb:county:essex', ['gb:county:greater-london']),
 'IP20': ('gb:county:norfolk', ['gb:county:suffolk']),
 'IP21': ('gb:county:suffolk', ['gb:county:norfolk']),
 'IP22': ('gb:county:norfolk', ['gb:county:suffolk']),
 'IP23': ('gb:county:suffolk', ['gb:county:norfolk']),
 'IP24': ('gb:county:norfolk', ['gb:county:suffolk']),
 'IP27': ('gb:county:suffolk', ['gb:county:norfolk']),
 'IP28': ('gb:county:suffolk', ['gb:county:cambridgeshire']),
 'KA1': ('gb:council_area:east-ayrshire', ['gb:council_area:south-ayrshire']),
 'KA11': ('gb:council_area:north-ayrshire', ['gb:council_area:east-ayrshire']),
 'KA13': ('gb:council_area:north-ayrshire', ['gb:council_area:east-ayrshire']),
 'KA19': ('gb:council_area:south-ayrshire', ['gb:council_area:east-ayrshire']),
 'KA2': ('gb:council_area:east-ayrshire', ['gb:council_area:north-ayrshire', 'gb:council_area:south-ayrshire']),
 'KA3': ('gb:council_area:east-ayrshire', ['gb:council_area:north-ayrshire']),
 'KA5': ('gb:council_area:east-ayrshire', ['gb:council_area:south-ayrshire']),
 'KA6': ('gb:council_area:east-ayrshire', ['gb:council_area:south-ayrshire']),
 'KT17': ('gb:county:surrey', ['gb:county:greater-london']),
 'KT18': ('gb:county:surrey', ['gb:county:greater-london']),
 'KT19': ('gb:county:surrey', ['gb:county:greater-london']),
 'KT22': ('gb:county:surrey', ['gb:county:greater-london']),
 'KT4': ('gb:county:greater-london', ['gb:county:surrey']),
 'KT6': ('gb:county:greater-london', ['gb:county:surrey']),
 'KT7': ('gb:county:surrey', ['gb:county:greater-london']),
 'KT8': ('gb:county:surrey', ['gb:county:greater-london']),
 'KT9': ('gb:county:greater-london', ['gb:county:surrey']),
 'KY13': ('gb:council_area:perth-and-kinross', ['gb:council_area:clackmannanshire', 'gb:council_area:fife']),
 'KY14': ('gb:council_area:fife', ['gb:council_area:perth-and-kinross']),
 'KY4': ('gb:council_area:fife', ['gb:council_area:perth-and-kinross']),
 'KY5': ('gb:council_area:fife', ['gb:council_area:perth-and-kinross']),
 'KY6': ('gb:council_area:fife', ['gb:council_area:perth-and-kinross']),
 'L24': ('gb:county:merseyside', ['gb:county:cheshire']),
 'L31': ('gb:county:merseyside', ['gb:county:lancashire']),
 'L33': ('gb:county:merseyside', ['gb:county:lancashire']),
 'L35': ('gb:county:merseyside', ['gb:county:cheshire']),
 'L37': ('gb:county:merseyside', ['gb:county:lancashire']),
 'LA10': ('gb:county:cumbria', ['gb:county:north-yorkshire']),
 'LA2': ('gb:county:lancashire', ['gb:county:north-yorkshire']),
 'LA5': ('gb:county:lancashire', ['gb:county:cumbria']),
 'LA6': ('gb:county:lancashire', ['gb:county:cumbria', 'gb:county:north-yorkshire']),
 'LA7': ('gb:county:cumbria', ['gb:county:lancashire']),
 'LD7': ('gb:county:powys', ['gb:county:shropshire']),
 'LD8': ('gb:county:powys', ['gb:county:herefordshire']),
 'LE10': ('gb:county:leicestershire', ['gb:county:warwickshire']),
 'LE12': ('gb:county:leicestershire', ['gb:county:nottinghamshire']),
 'LE14': ('gb:county:leicestershire', ['gb:county:nottinghamshire']),
 'LE15': ('gb:county:rutland', ['gb:county:leicestershire', 'gb:county:northamptonshire']),
 'LE16': ('gb:county:leicestershire', ['gb:county:northamptonshire', 'gb:county:rutland']),
 'LE17': ('gb:county:leicestershire', ['gb:county:northamptonshire']),
 'LE65': ('gb:county:leicestershire', ['gb:county:derbyshire']),
 'LL11': ('gb:county_borough:wrexham', ['gb:county:denbighshire', 'gb:county:flintshire']),
 'LL12': ('gb:county_borough:wrexham', ['gb:county:flintshire']),
 'LL14': ('gb:county_borough:wrexham', ['gb:county:shropshire']),
 'LL16': ('gb:county:denbighshire', ['gb:county_borough:conwy']),
 'LL17': ('gb:county:denbighshire', ['gb:county_borough:conwy']),
 'LL18': ('gb:county:denbighshire', ['gb:county:flintshire', 'gb:county_borough:conwy']),
 'LL19': ('gb:county:denbighshire', ['gb:county:flintshire']),
 'LL20': ('gb:county:denbighshire', ['gb:county_borough:wrexham']),
 'LL21': ('gb:county:denbighshire', ['gb:county:gwynedd', 'gb:county_borough:conwy']),
 'LL22': ('gb:county_borough:conwy', ['gb:county:denbighshire']),
 'LL33': ('gb:county_borough:conwy', ['gb:county:gwynedd']),
 'LL59': ('gb:county:isle-of-anglesey', ['gb:county:gwynedd']),
 'LS17': ('gb:county:west-yorkshire', ['gb:county:north-yorkshire']),
 'LS21': ('gb:county:west-yorkshire', ['gb:county:north-yorkshire']),
 'LS22': ('gb:county:west-yorkshire', ['gb:county:north-yorkshire']),
 'LS24': ('gb:county:north-yorkshire', ['gb:county:west-yorkshire']),
 'LS25': ('gb:county:west-yorkshire', ['gb:county:north-yorkshire']),
 'LS29': ('gb:county:west-yorkshire', ['gb:county:north-yorkshire']),
 'LU1': ('gb:county:bedfordshire', ['gb:county:hertfordshire']),
 'LU2': ('gb:county:bedfordshire', ['gb:county:hertfordshire']),
 'LU6': ('gb:county:bedfordshire', ['gb:county:buckinghamshire', 'gb:county:hertfordshire']),
 'LU7': ('gb:county:bedfordshire', ['gb:county:buckinghamshire']),
 'M22': ('gb:county:greater-manchester', ['gb:county:cheshire']),
 'MK16': ('gb:county:buckinghamshire', ['gb:county:northamptonshire']),
 'MK17': ('gb:county:buckinghamshire', ['gb:county:bedfordshire']),
 'MK18': ('gb:county:buckinghamshire', ['gb:county:oxfordshire']),
 'MK19': ('gb:county:buckinghamshire', ['gb:county:northamptonshire']),
 'MK43': ('gb:county:bedfordshire', ['gb:county:buckinghamshire']),
 'MK44': ('gb:county:bedfordshire', ['gb:county:cambridgeshire']),
 'ML11': ('gb:council_area:south-lanarkshire', ['gb:council_area:west-lothian']),
 'ML12': ('gb:council_area:south-lanarkshire', ['gb:council_area:dumfries-and-galloway', 'gb:council_area:scottish-borders']),
 'ML2': ('gb:council_area:north-lanarkshire', ['gb:council_area:south-lanarkshire']),
 'ML7': ('gb:council_area:north-lanarkshire', ['gb:council_area:west-lothian']),
 'NE13': ('gb:county:tyne-and-wear', ['gb:county:northumberland']),
 'NE15': ('gb:county:tyne-and-wear', ['gb:county:northumberland']),
 'NE16': ('gb:county:tyne-and-wear', ['gb:county:durham']),
 'NE17': ('gb:county:tyne-and-wear', ['gb:county:durham', 'gb:county:northumberland']),
 'NE20': ('gb:county:northumberland', ['gb:county:tyne-and-wear']),
 'NE23': ('gb:county:northumberland', ['gb:county:tyne-and-wear']),
 'NE25': ('gb:county:tyne-and-wear', ['gb:county:northumberland']),
 'NE26': ('gb:county:tyne-and-wear', ['gb:county:northumberland']),
 'NE27': ('gb:county:tyne-and-wear', ['gb:county:northumberland']),
 'NE38': ('gb:county:tyne-and-wear', ['gb:county:durham']),
 'NE39': ('gb:county:tyne-and-wear', ['gb:county:durham']),
 'NE41': ('gb:county:northumberland', ['gb:county:tyne-and-wear']),
 'NE42': ('gb:county:northumberland', ['gb:county:tyne-and-wear']),
 'NG13': ('gb:county:nottinghamshire', ['gb:county:leicestershire']),
 'NG16': ('gb:county:nottinghamshire', ['gb:county:derbyshire']),
 'NG19': ('gb:county:nottinghamshire', ['gb:county:derbyshire']),
 'NG20': ('gb:county:derbyshire', ['gb:county:nottinghamshire']),
 'NG23': ('gb:county:nottinghamshire', ['gb:county:lincolnshire']),
 'NG32': ('gb:county:lincolnshire', ['gb:county:leicestershire']),
 'NG33': ('gb:county:lincolnshire', ['gb:county:leicestershire']),
 'NN10': ('gb:county:northamptonshire', ['gb:county:bedfordshire']),
 'NN11': ('gb:county:northamptonshire', ['gb:county:warwickshire']),
 'NN12': ('gb:county:northamptonshire', ['gb:county:buckinghamshire']),
 'NN13': ('gb:county:northamptonshire', ['gb:county:buckinghamshire', 'gb:county:oxfordshire']),
 'NN29': ('gb:county:northamptonshire', ['gb:county:bedfordshire']),
 'NN6': ('gb:county:northamptonshire', ['gb:county:leicestershire']),
 'NN7': ('gb:county:northamptonshire', ['gb:county:buckinghamshire']),
 'NP10': ('gb:county_borough:newport', ['gb:county_borough:caerphilly']),
 'NP11': ('gb:county_borough:caerphilly', ['gb:county_borough:blaenau-gwent', 'gb:county_borough:torfaen']),
 'NP13': ('gb:county_borough:blaenau-gwent', ['gb:county_borough:caerphilly']),
 'NP16': ('gb:county:monmouthshire', ['gb:county:gloucestershire']),
 'NP18': ('gb:county_borough:newport', ['gb:county:monmouthshire', 'gb:county_borough:torfaen']),
 'NP22': ('gb:county_borough:blaenau-gwent', ['gb:county_borough:caerphilly']),
 'NP23': ('gb:county_borough:blaenau-gwent', ['gb:county:monmouthshire']),
 'NP25': ('gb:county:monmouthshire', ['gb:county:gloucestershire', 'gb:county:herefordshire']),
 'NP26': ('gb:county:monmouthshire', ['gb:county_borough:newport']),
 'NP4': ('gb:county_borough:torfaen', ['gb:county:monmouthshire']),
 'NP44': ('gb:county_borough:torfaen', ['gb:county:monmouthshire']),
 'NP7': ('gb:county:monmouthshire', ['gb:county:herefordshire', 'gb:county:powys']),
 'NP8': ('gb:county:powys', ['gb:county:monmouthshire']),
 'NR34': ('gb:county:suffolk', ['gb:county:norfolk']),
 'NR35': ('gb:county:norfolk', ['gb:county:suffolk']),
 'OL12': ('gb:county:greater-manchester', ['gb:county:lancashire']),
 'OL14': ('gb:county:west-yorkshire', ['gb:county:greater-manchester', 'gb:county:lancashire']),
 'OL15': ('gb:county:greater-manchester', ['gb:county:west-yorkshire']),
 'OX12': ('gb:county:oxfordshire', ['gb:county:berkshire']),
 'OX15': ('gb:county:oxfordshire', ['gb:county:warwickshire']),
 'OX17': ('gb:county:northamptonshire', ['gb:county:oxfordshire', 'gb:county:warwickshire']),
 'OX18': ('gb:county:oxfordshire', ['gb:county:gloucestershire']),
 'OX27': ('gb:county:oxfordshire', ['gb:county:buckinghamshire', 'gb:county:northamptonshire']),
 'OX33': ('gb:county:oxfordshire', ['gb:county:buckinghamshire']),
 'OX39': ('gb:county:oxfordshire', ['gb:county:buckinghamshire']),
 'OX5': ('gb:county:oxfordshire', ['gb:county:buckinghamshire']),
 'OX7': ('gb:county:oxfordshire', ['gb:county:gloucestershire']),
 'OX9': ('gb:county:oxfordshire', ['gb:county:buckinghamshire']),
 'PA11': ('gb:council_area:renfrewshire', ['gb:council_area:inverclyde']),
 'PA13': ('gb:council_area:inverclyde', ['gb:council_area:renfrewshire']),
 'PA14': ('gb:council_area:inverclyde', ['gb:council_area:renfrewshire']),
 'PA38': ('gb:council_area:argyll-and-bute', ['gb:council_area:highland']),
 'PE12': ('gb:county:lincolnshire', ['gb:county:cambridgeshire']),
 'PE13': ('gb:county:cambridgeshire', ['gb:county:lincolnshire', 'gb:county:norfolk']),
 'PE14': ('gb:county:norfolk', ['gb:county:cambridgeshire']),
 'PE19': ('gb:county:cambridgeshire', ['gb:county:bedfordshire']),
 'PE28': ('gb:county:cambridgeshire', ['gb:county:bedfordshire']),
 'PE34': ('gb:county:norfolk', ['gb:county:lincolnshire']),
 'PE38': ('gb:county:norfolk', ['gb:county:cambridgeshire']),
 'PE6': ('gb:county:lincolnshire', ['gb:county:cambridgeshire']),
 'PE8': ('gb:county:northamptonshire', ['gb:county:cambridgeshire']),
 'PE9': ('gb:county:lincolnshire', ['gb:county:cambridgeshire', 'gb:county:northamptonshire', 'gb:county:rutland']),
 'PH11': ('gb:council_area:perth-and-kinross', ['gb:council_area:angus']),
 'PH12': ('gb:council_area:angus', ['gb:council_area:perth-and-kinross']),
 'PH13': ('gb:council_area:perth-and-kinross', ['gb:council_area:angus']),
 'PH2': ('gb:council_area:perth-and-kinross', ['gb:council_area:fife']),
 'PH33': ('gb:council_area:highland', ['gb:council_area:perth-and-kinross']),
 'PL15': ('gb:county:cornwall', ['gb:county:devon']),
 'PO10': ('gb:county:west-sussex', ['gb:county:hampshire']),
 'PO9': ('gb:county:hampshire', ['gb:county:west-sussex']),
 'PR8': ('gb:county:merseyside', ['gb:county:lancashire']),
 'PR9': ('gb:county:merseyside', ['gb:county:lancashire']),
 'RG17': ('gb:county:berkshire', ['gb:county:oxfordshire', 'gb:county:wiltshire']),
 'RG19': ('gb:county:berkshire', ['gb:county:hampshire']),
 'RG20': ('gb:county:berkshire', ['gb:county:hampshire']),
 'RG26': ('gb:county:hampshire', ['gb:county:berkshire']),
 'RG27': ('gb:county:hampshire', ['gb:county:berkshire']),
 'RG4': ('gb:county:berkshire', ['gb:county:oxfordshire']),
 'RG7': ('gb:county:berkshire', ['gb:county:hampshire']),
 'RG8': ('gb:county:berkshire', ['gb:county:oxfordshire']),
 'RG9': ('gb:county:oxfordshire', ['gb:county:berkshire', 'gb:county:buckinghamshire']),
 'RH10': ('gb:county:west-sussex', ['gb:county:surrey']),
 'RH12': ('gb:county:west-sussex', ['gb:county:surrey']),
 'RH14': ('gb:county:west-sussex', ['gb:county:surrey']),
 'RH15': ('gb:county:west-sussex', ['gb:county:east-sussex']),
 'RH16': ('gb:county:west-sussex', ['gb:county:east-sussex']),
 'RH17': ('gb:county:west-sussex', ['gb:county:east-sussex']),
 'RH19': ('gb:county:west-sussex', ['gb:county:east-sussex', 'gb:county:surrey']),
 'RH6': ('gb:county:surrey', ['gb:county:west-sussex']),
 'RM14': ('gb:county:greater-london', ['gb:county:essex']),
 'RM15': ('gb:county:essex', ['gb:county:greater-london']),
 'RM4': ('gb:county:essex', ['gb:county:greater-london']),
 'S11': ('gb:county:south-yorkshire', ['gb:county:derbyshire']),
 'S12': ('gb:county:south-yorkshire', ['gb:county:derbyshire']),
 'S17': ('gb:county:south-yorkshire', ['gb:county:derbyshire']),
 'S71': ('gb:county:south-yorkshire', ['gb:county:west-yorkshire']),
 'S72': ('gb:county:south-yorkshire', ['gb:county:west-yorkshire']),
 'S75': ('gb:county:south-yorkshire', ['gb:county:west-yorkshire']),
 'S8': ('gb:county:south-yorkshire', ['gb:county:derbyshire']),
 'S80': ('gb:county:nottinghamshire', ['gb:county:derbyshire', 'gb:county:south-yorkshire']),
 'S81': ('gb:county:nottinghamshire', ['gb:county:south-yorkshire']),
 'SA1': ('gb:county:swansea', ['gb:county_borough:neath-port-talbot']),
 'SA10': ('gb:county_borough:neath-port-talbot', ['gb:county:powys']),
 'SA11': ('gb:county_borough:neath-port-talbot', ['gb:county:powys', 'gb:county_borough:rhondda-cynon-taf']),
 'SA18': ('gb:county:carmarthenshire', ['gb:county:swansea', 'gb:county_borough:neath-port-talbot']),
 'SA34': ('gb:county:carmarthenshire', ['gb:county:pembrokeshire']),
 'SA35': ('gb:county:pembrokeshire', ['gb:county:carmarthenshire']),
 'SA37': ('gb:county:pembrokeshire', ['gb:county:carmarthenshire']),
 'SA38': ('gb:county:carmarthenshire', ['gb:county:ceredigion']),
 'SA39': ('gb:county:carmarthenshire', ['gb:county:ceredigion']),
 'SA4': ('gb:county:swansea', ['gb:county:carmarthenshire']),
 'SA40': ('gb:county:carmarthenshire', ['gb:county:ceredigion']),
 'SA43': ('gb:county:ceredigion', ['gb:county:pembrokeshire']),
 'SA44': ('gb:county:ceredigion', ['gb:county:carmarthenshire']),
 'SA48': ('gb:county:ceredigion', ['gb:county:carmarthenshire']),
 'SA66': ('gb:county:pembrokeshire', ['gb:county:carmarthenshire']),
 'SA67': ('gb:county:pembrokeshire', ['gb:county:carmarthenshire']),
 'SA7': ('gb:county:swansea', ['gb:county_borough:neath-port-talbot']),
 'SA8': ('gb:county_borough:neath-port-talbot', ['gb:county:swansea']),
 'SA9': ('gb:county:powys', ['gb:county:carmarthenshire', 'gb:county_borough:neath-port-talbot']),
 'SG16': ('gb:county:bedfordshire', ['gb:county:hertfordshire']),
 'SG19': ('gb:county:bedfordshire', ['gb:county:cambridgeshire']),
 'SG5': ('gb:county:hertfordshire', ['gb:county:bedfordshire']),
 'SG6': ('gb:county:hertfordshire', ['gb:county:bedfordshire']),
 'SG7': ('gb:county:hertfordshire', ['gb:county:bedfordshire', 'gb:county:cambridgeshire']),
 'SG8': ('gb:county:cambridgeshire', ['gb:county:bedfordshire', 'gb:county:essex', 'gb:county:hertfordshire']),
 'SK11': ('gb:county:cheshire', ['gb:county:staffordshire']),
 'SK12': ('gb:county:cheshire', ['gb:county:greater-manchester']),
 'SK14': ('gb:county:greater-manchester', ['gb:county:derbyshire']),
 'SK17': ('gb:county:derbyshire', ['gb:county:staffordshire']),
 'SK22': ('gb:county:derbyshire', ['gb:county:cheshire', 'gb:county:greater-manchester']),
 'SK23': ('gb:county:derbyshire', ['gb:county:cheshire']),
 'SK6': ('gb:county:greater-manchester', ['gb:county:cheshire']),
 'SK7': ('gb:county:greater-manchester', ['gb:county:cheshire']),
 'SK8': ('gb:county:greater-manchester', ['gb:county:cheshire']),
 'SL0': ('gb:county:buckinghamshire', ['gb:county:berkshire']),
 'SL1': ('gb:county:berkshire', ['gb:county:buckinghamshire']),
 'SL2': ('gb:county:berkshire', ['gb:county:buckinghamshire']),
 'SL3': ('gb:county:berkshire', ['gb:county:buckinghamshire']),
 'SL4': ('gb:county:berkshire', ['gb:county:buckinghamshire', 'gb:county:surrey']),
 'SL5': ('gb:county:berkshire', ['gb:county:surrey']),
 'SL6': ('gb:county:berkshire', ['gb:county:buckinghamshire']),
 'SL7': ('gb:county:buckinghamshire', ['gb:county:berkshire']),
 'SL8': ('gb:county:buckinghamshire', ['gb:county:berkshire']),
 'SL9': ('gb:county:buckinghamshire', ['gb:county:hertfordshire']),
 'SM2': ('gb:county:greater-london', ['gb:county:surrey']),
 'SM3': ('gb:county:greater-london', ['gb:county:surrey']),
 'SM5': ('gb:county:greater-london', ['gb:county:surrey']),
 'SM7': ('gb:county:surrey', ['gb:county:greater-london']),
 'SN14': ('gb:county:wiltshire', ['gb:county:gloucestershire']),
 'SN16': ('gb:county:wiltshire', ['gb:county:gloucestershire']),
 'SN6': ('gb:county:wiltshire', ['gb:county:gloucestershire', 'gb:county:oxfordshire']),
 'SN8': ('gb:county:wiltshire', ['gb:county:berkshire']),
 'SO51': ('gb:county:hampshire', ['gb:county:wiltshire']),
 'SP11': ('gb:county:hampshire', ['gb:county:wiltshire']),
 'SP4': ('gb:county:wiltshire', ['gb:county:hampshire']),
 'SP5': ('gb:county:wiltshire', ['gb:county:dorset', 'gb:county:hampshire']),
 'SP6': ('gb:county:hampshire', ['gb:county:dorset', 'gb:county:wiltshire']),
 'SP7': ('gb:county:dorset', ['gb:county:wiltshire']),
 'SP9': ('gb:county:wiltshire', ['gb:county:hampshire']),
 'SR7': ('gb:county:durham', ['gb:county:tyne-and-wear']),
 'ST14': ('gb:county:staffordshire', ['gb:county:derbyshire']),
 'ST19': ('gb:county:staffordshire', ['gb:county:shropshire']),
 'ST7': ('gb:county:staffordshire', ['gb:county:cheshire']),
 'SY10': ('gb:county:shropshire', ['gb:county:powys', 'gb:county_borough:wrexham']),
 'SY13': ('gb:county:shropshire', ['gb:county:cheshire', 'gb:county_borough:wrexham']),
 'SY14': ('gb:county:cheshire', ['gb:county:shropshire', 'gb:county_borough:wrexham']),
 'SY15': ('gb:county:powys', ['gb:county:shropshire']),
 'SY20': ('gb:county:powys', ['gb:county:ceredigion', 'gb:county:gwynedd']),
 'SY21': ('gb:county:powys', ['gb:county:shropshire']),
 'SY22': ('gb:county:powys', ['gb:county:shropshire']),
 'SY23': ('gb:county:ceredigion', ['gb:county:powys']),
 'SY25': ('gb:county:ceredigion', ['gb:county:powys']),
 'SY5': ('gb:county:shropshire', ['gb:county:powys']),
 'SY7': ('gb:county:shropshire', ['gb:county:herefordshire', 'gb:county:powys']),
 'SY8': ('gb:county:shropshire', ['gb:county:herefordshire', 'gb:county:worcestershire']),
 'SY9': ('gb:county:shropshire', ['gb:county:powys']),
 'TA18': ('gb:county:somerset', ['gb:county:dorset']),
 'TA20': ('gb:county:somerset', ['gb:county:devon', 'gb:county:dorset']),
 'TA21': ('gb:county:somerset', ['gb:county:devon']),
 'TA22': ('gb:county:somerset', ['gb:county:devon']),
 'TA3': ('gb:county:somerset', ['gb:county:devon']),
 'TA4': ('gb:county:somerset', ['gb:county:devon']),
 'TD11': ('gb:council_area:scottish-borders', ['gb:council_area:east-lothian']),
 'TD12': ('gb:council_area:scottish-borders', ['gb:county:northumberland']),
 'TD13': ('gb:council_area:scottish-borders', ['gb:council_area:east-lothian']),
 'TD15': ('gb:county:northumberland', ['gb:council_area:scottish-borders']),
 'TD5': ('gb:council_area:scottish-borders', ['gb:county:northumberland']),
 'TD9': ('gb:council_area:scottish-borders', ['gb:county:cumbria']),
 'TF10': ('gb:county:shropshire', ['gb:county:staffordshire']),
 'TF11': ('gb:county:shropshire', ['gb:county:staffordshire']),
 'TF9': ('gb:county:shropshire', ['gb:county:cheshire', 'gb:county:staffordshire']),
 'TN14': ('gb:county:kent', ['gb:county:greater-london']),
 'TN16': ('gb:county:greater-london', ['gb:county:kent', 'gb:county:surrey']),
 'TN18': ('gb:county:kent', ['gb:county:east-sussex']),
 'TN2': ('gb:county:kent', ['gb:county:east-sussex']),
 'TN3': ('gb:county:kent', ['gb:county:east-sussex']),
 'TN5': ('gb:county:east-sussex', ['gb:county:kent']),
 'TN8': ('gb:county:kent', ['gb:county:east-sussex', 'gb:county:surrey']),
 'TS17': ('gb:county:north-yorkshire', ['gb:county:durham']),
 'TS2': ('gb:county:north-yorkshire', ['gb:county:durham']),
 'TW12': ('gb:county:greater-london', ['gb:county:surrey']),
 'TW14': ('gb:county:greater-london', ['gb:county:surrey']),
 'TW15': ('gb:county:surrey', ['gb:county:greater-london']),
 'TW18': ('gb:county:surrey', ['gb:county:berkshire']),
 'TW19': ('gb:county:surrey', ['gb:county:berkshire', 'gb:county:greater-london']),
 'TW6': ('gb:county:greater-london', ['gb:county:surrey']),
 'UB8': ('gb:county:greater-london', ['gb:county:buckinghamshire']),
 'UB9': ('gb:county:buckinghamshire', ['gb:county:greater-london', 'gb:county:hertfordshire']),
 'WA11': ('gb:county:merseyside', ['gb:county:lancashire']),
 'WA12': ('gb:county:merseyside', ['gb:county:cheshire', 'gb:county:greater-manchester']),
 'WA13': ('gb:county:cheshire', ['gb:county:greater-manchester']),
 'WA14': ('gb:county:greater-manchester', ['gb:county:cheshire']),
 'WA15': ('gb:county:greater-manchester', ['gb:county:cheshire']),
 'WA2': ('gb:county:cheshire', ['gb:county:merseyside']),
 'WA3': ('gb:county:greater-manchester', ['gb:county:cheshire', 'gb:county:merseyside']),
 'WA5': ('gb:county:cheshire', ['gb:county:merseyside']),
 'WA8': ('gb:county:cheshire', ['gb:county:merseyside']),
 'WA9': ('gb:county:merseyside', ['gb:county:cheshire']),
 'WC1V': ('gb:county:greater-london', ['gb:county:city-of-london']),
 'WC2A': ('gb:county:greater-london', ['gb:county:city-of-london']),
 'WD23': ('gb:county:hertfordshire', ['gb:county:greater-london']),
 'WD3': ('gb:county:hertfordshire', ['gb:county:buckinghamshire', 'gb:county:greater-london']),
 'WD6': ('gb:county:hertfordshire', ['gb:county:greater-london']),
 'WF11': ('gb:county:west-yorkshire', ['gb:county:north-yorkshire']),
 'WF8': ('gb:county:west-yorkshire', ['gb:county:north-yorkshire', 'gb:county:south-yorkshire']),
 'WN4': ('gb:county:greater-manchester', ['gb:county:merseyside']),
 'WN5': ('gb:county:greater-manchester', ['gb:county:lancashire', 'gb:county:merseyside']),
 'WN6': ('gb:county:greater-manchester', ['gb:county:lancashire']),
 'WR11': ('gb:county:worcestershire', ['gb:county:gloucestershire', 'gb:county:warwickshire']),
 'WR12': ('gb:county:worcestershire', ['gb:county:gloucestershire']),
 'WR13': ('gb:county:herefordshire', ['gb:county:gloucestershire', 'gb:county:worcestershire']),
 'WR14': ('gb:county:worcestershire', ['gb:county:herefordshire']),
 'WR15': ('gb:county:worcestershire', ['gb:county:herefordshire', 'gb:county:shropshire']),
 'WR6': ('gb:county:worcestershire', ['gb:county:herefordshire']),
 'WR8': ('gb:county:worcestershire', ['gb:county:gloucestershire']),
 'WS3': ('gb:county:west-midlands', ['gb:county:staffordshire']),
 'WS8': ('gb:county:west-midlands', ['gb:county:staffordshire']),
 'WS9': ('gb:county:west-midlands', ['gb:county:staffordshire']),
 'WV10': ('gb:county:west-midlands', ['gb:county:staffordshire']),
 'WV11': ('gb:county:west-midlands', ['gb:county:staffordshire']),
 'WV15': ('gb:county:shropshire', ['gb:county:staffordshire']),
 'WV3': ('gb:county:west-midlands', ['gb:county:staffordshire']),
 'WV4': ('gb:county:west-midlands', ['gb:county:staffordshire']),
 'WV5': ('gb:county:staffordshire', ['gb:county:shropshire']),
 'WV6': ('gb:county:west-midlands', ['gb:county:shropshire', 'gb:county:staffordshire']),
 'WV7': ('gb:county:shropshire', ['gb:county:staffordshire']),
 'WV8': ('gb:county:staffordshire', ['gb:county:shropshire', 'gb:county:west-midlands']),
 'WV9': ('gb:county:staffordshire', ['gb:county:west-midlands']),
 'WV98': ('gb:county:worcestershire', ['gb:county:west-midlands']),
 'YO25': ('gb:county:east-riding-of-yorkshire', ['gb:county:north-yorkshire']),
 'YO41': ('gb:county:east-riding-of-yorkshire', ['gb:county:north-yorkshire']),
 'YO8': ('gb:county:north-yorkshire', ['gb:county:east-riding-of-yorkshire']),
}
plink = {l['postcode']: l['area_source_id'] for l in links if l['is_primary'] == 'true'}
secl = {}
for l in links:
    if l['is_primary'] == 'false':
        secl.setdefault(l['postcode'], []).append(l['area_source_id'])
badmulti = [(pc, plink.get(pc), sorted(secl.get(pc, []))) for pc, (p, ss) in MULTI.items()
            if plink.get(pc) != p or sorted(secl.get(pc, [])) != ss]
check('multi-table-exact', not badmulti, str(badmulti[:3]))
extras = [pc for pc in nmulti if pc not in MULTI]
check('multi-no-extras', not extras, str(extras[:5]))
# --- per-nation primary counts ---
check('nation-england-2210', sum(1 for c, p in plink.items() if byid[p]['parent_source_id'] == 'gb:nation:england') == 2210)
check('nation-northern-ireland-80', sum(1 for c, p in plink.items() if byid[p]['parent_source_id'] == 'gb:nation:northern-ireland') == 80)
check('nation-scotland-453', sum(1 for c, p in plink.items() if byid[p]['parent_source_id'] == 'gb:nation:scotland') == 453)
check('nation-wales-200', sum(1 for c, p in plink.items() if byid[p]['parent_source_id'] == 'gb:nation:wales') == 200)
# --- per-L2 primary counts (113) ---
PRIM2 = {
 'gb:council_area:aberdeen-city': 13,
 'gb:council_area:aberdeenshire': 17,
 'gb:council_area:angus': 6,
 'gb:council_area:argyll-and-bute': 48,
 'gb:council_area:city-of-edinburgh': 23,
 'gb:council_area:clackmannanshire': 5,
 'gb:council_area:dumfries-and-galloway': 15,
 'gb:council_area:dundee-city': 5,
 'gb:council_area:east-ayrshire': 9,
 'gb:council_area:east-dunbartonshire': 4,
 'gb:council_area:east-lothian': 11,
 'gb:council_area:east-renfrewshire': 4,
 'gb:council_area:falkirk': 7,
 'gb:council_area:fife': 17,
 'gb:council_area:glasgow-city': 29,
 'gb:council_area:highland': 85,
 'gb:council_area:inverclyde': 6,
 'gb:council_area:midlothian': 9,
 'gb:council_area:moray': 8,
 'gb:council_area:na-h-eileanan-siar-western-isles': 9,
 'gb:council_area:north-ayrshire': 16,
 'gb:council_area:north-lanarkshire': 11,
 'gb:council_area:orkney': 3,
 'gb:council_area:perth-and-kinross': 18,
 'gb:council_area:renfrewshire': 12,
 'gb:council_area:scottish-borders': 19,
 'gb:council_area:shetland-islands': 3,
 'gb:council_area:south-ayrshire': 6,
 'gb:council_area:south-lanarkshire': 12,
 'gb:council_area:stirling': 11,
 'gb:council_area:west-dunbartonshire': 4,
 'gb:council_area:west-lothian': 8,
 'gb:county:bedfordshire': 18,
 'gb:county:berkshire': 29,
 'gb:county:bristol': 15,
 'gb:county:buckinghamshire': 46,
 'gb:county:cambridgeshire': 27,
 'gb:county:cardiff': 12,
 'gb:county:carmarthenshire': 14,
 'gb:county:ceredigion': 9,
 'gb:county:cheshire': 41,
 'gb:county:city-of-london': 17,
 'gb:county:cornwall': 50,
 'gb:county:cumbria': 46,
 'gb:county:denbighshire': 7,
 'gb:county:derbyshire': 36,
 'gb:county:devon': 60,
 'gb:county:dorset': 37,
 'gb:county:durham': 37,
 'gb:county:east-riding-of-yorkshire': 27,
 'gb:county:east-sussex': 38,
 'gb:county:essex': 73,
 'gb:county:flintshire': 4,
 'gb:county:gloucestershire': 35,
 'gb:county:greater-london': 266,
 'gb:county:greater-manchester': 93,
 'gb:county:gwynedd': 23,
 'gb:county:hampshire': 67,
 'gb:county:herefordshire': 10,
 'gb:county:hertfordshire': 47,
 'gb:county:isle-of-anglesey': 21,
 'gb:county:isle-of-wight': 12,
 'gb:county:kent': 74,
 'gb:county:lancashire': 42,
 'gb:county:leicestershire': 28,
 'gb:county:lincolnshire': 47,
 'gb:county:merseyside': 73,
 'gb:county:monmouthshire': 5,
 'gb:county:norfolk': 49,
 'gb:county:north-yorkshire': 54,
 'gb:county:northamptonshire': 21,
 'gb:county:northumberland': 27,
 'gb:county:nottinghamshire': 29,
 'gb:county:oxfordshire': 27,
 'gb:county:pembrokeshire': 18,
 'gb:county:powys': 18,
 'gb:county:rutland': 1,
 'gb:county:shropshire': 32,
 'gb:county:somerset': 55,
 'gb:county:south-yorkshire': 48,
 'gb:county:staffordshire': 38,
 'gb:county:suffolk': 34,
 'gb:county:surrey': 58,
 'gb:county:swansea': 9,
 'gb:county:tyne-and-wear': 46,
 'gb:county:warwickshire': 24,
 'gb:county:west-midlands': 94,
 'gb:county:west-sussex': 35,
 'gb:county:west-yorkshire': 91,
 'gb:county:wiltshire': 29,
 'gb:county:worcestershire': 27,
 'gb:county_borough:blaenau-gwent': 3,
 'gb:county_borough:bridgend': 6,
 'gb:county_borough:caerphilly': 6,
 'gb:county_borough:conwy': 12,
 'gb:county_borough:merthyr-tydfil': 3,
 'gb:county_borough:neath-port-talbot': 5,
 'gb:county_borough:newport': 4,
 'gb:county_borough:rhondda-cynon-taf': 10,
 'gb:county_borough:torfaen': 2,
 'gb:county_borough:vale-of-glamorgan': 5,
 'gb:county_borough:wrexham': 4,
 'gb:district:antrim-and-newtownabbey': 5,
 'gb:district:ards-and-north-down': 6,
 'gb:district:armagh-city-banbridge-and-craigavon': 10,
 'gb:district:belfast': 15,
 'gb:district:causeway-coast-and-glens': 9,
 'gb:district:derry-city-and-strabane': 4,
 'gb:district:fermanagh-and-omagh': 6,
 'gb:district:lisburn-and-castlereagh': 5,
 'gb:district:mid-and-east-antrim': 4,
 'gb:district:mid-ulster': 10,
 'gb:district:newry-mourne-and-down': 6,
}
have2 = Counter(plink.values())
bad2 = [(s, have2[s], w) for s, w in PRIM2.items() if have2[s] != w]
check('per-l2-primary-exact', not bad2, str(bad2[:3]))
# --- anchors: fills, Tees, City, flips, exemplars ---
anchors = {
 'E22': 'gb:county:greater-london',
 'MK20': 'gb:county:buckinghamshire',
 'AB12': 'gb:council_area:aberdeen-city',
 'BA1': 'gb:county:somerset',
 'TR25': 'gb:county:cornwall',
 'W1A': 'gb:county:greater-london',
 'E1': 'gb:county:greater-london',
 'EC1A': 'gb:county:city-of-london',
 'B97': 'gb:county:worcestershire',
 'B98': 'gb:county:worcestershire',
 'CV10': 'gb:county:warwickshire',
 'CV11': 'gb:county:warwickshire',
 'RH10': 'gb:county:west-sussex',
 'RH16': 'gb:county:west-sussex',
 'SG7': 'gb:county:hertfordshire',
 'SG8': 'gb:county:cambridgeshire',
 'TN2': 'gb:county:kent',
 'TN8': 'gb:county:kent',
 'EN10': 'gb:county:hertfordshire',
 'EN11': 'gb:county:hertfordshire',
 'CM21': 'gb:county:hertfordshire',
 'CM23': 'gb:county:hertfordshire',
 'DE13': 'gb:county:staffordshire',
 'DE15': 'gb:county:staffordshire',
 'DY10': 'gb:county:worcestershire',
 'GU12': 'gb:county:surrey',
 'GU16': 'gb:county:surrey',
 'IP23': 'gb:county:suffolk',
 'IP28': 'gb:county:suffolk',
 'PE12': 'gb:county:lincolnshire',
 'PE34': 'gb:county:norfolk',
 'PE38': 'gb:county:norfolk',
 'ST14': 'gb:county:staffordshire',
 'NG19': 'gb:county:nottinghamshire',
 'EX23': 'gb:county:cornwall',
 'DT7': 'gb:county:dorset',
 'NP16': 'gb:county:monmouthshire',
 'NP25': 'gb:county:monmouthshire',
 'WR8': 'gb:county:worcestershire',
 'BH31': 'gb:county:dorset',
 'B47': 'gb:county:worcestershire',
 'S80': 'gb:county:nottinghamshire',
 'B79': 'gb:county:staffordshire',
 'B78': 'gb:county:warwickshire',
 'DE74': 'gb:county:leicestershire',
 'DY7': 'gb:county:staffordshire',
 'DY8': 'gb:county:west-midlands',
 'EN8': 'gb:county:hertfordshire',
 'TS15': 'gb:county:north-yorkshire',
 'TS16': 'gb:county:durham',
 'TS17': 'gb:county:north-yorkshire',
 'TS18': 'gb:county:durham',
 'TS2': 'gb:county:north-yorkshire',
 'TS8': 'gb:county:north-yorkshire',
 'PA34': 'gb:council_area:argyll-and-bute',
 'DD4': 'gb:council_area:dundee-city',
 'G83': 'gb:council_area:west-dunbartonshire',
 'CF44': 'gb:county_borough:rhondda-cynon-taf',
 'BT30': 'gb:district:newry-mourne-and-down',
}
for pc, want in anchors.items():
    check(f'anchor-{pc}', plink.get(pc) == want, str(plink.get(pc)))
# --- holds: primaries kept against unit plurality (judgment calls) ---
holds = {
 'CW3': 'gb:county:cheshire',
 'LA6': 'gb:county:lancashire',
 'MK19': 'gb:county:buckinghamshire',
 'NG20': 'gb:county:derbyshire',
 'PH12': 'gb:council_area:angus',
 'WA3': 'gb:county:greater-manchester',
 'WV9': 'gb:county:staffordshire',
}
for pc, want in holds.items():
    check(f'hold-{pc}', plink.get(pc) == want, str(plink.get(pc)))
# --- dropped legs are gone (Tees singles + PA34) ---
check('single-TS15', counts.get('TS15') == 1, str(counts.get('TS15')))
check('single-TS16', counts.get('TS16') == 1, str(counts.get('TS16')))
check('single-TS18', counts.get('TS18') == 1, str(counts.get('TS18')))
check('single-TS19', counts.get('TS19') == 1, str(counts.get('TS19')))
check('single-TS20', counts.get('TS20') == 1, str(counts.get('TS20')))
check('single-TS21', counts.get('TS21') == 1, str(counts.get('TS21')))
check('single-TS22', counts.get('TS22') == 1, str(counts.get('TS22')))
check('single-TS23', counts.get('TS23') == 1, str(counts.get('TS23')))
check('single-TS8', counts.get('TS8') == 1, str(counts.get('TS8')))
check('single-PA34', counts.get('PA34') == 1, str(counts.get('PA34')))
# --- 61-drop list + 10 NSPL-live holds stay absent ---
DROPS = ['BB94', 'BN91', 'BS0', 'BS80', 'BT58', 'CA99', 'CR44', 'DN55', 'E77', 'EC1', 'EC2', 'EC3', 'EC4', 'EC50', 'FY0', 'G9', 'GU13', 'GU95', 'GY1', 'GY10', 'GY2', 'GY3', 'GY4', 'GY5', 'GY6', 'GY7', 'GY8', 'GY9', 'IM1', 'IM2', 'IM3', 'IM4', 'IM5', 'IM6', 'IM7', 'IM8', 'IM9', 'JE1', 'JE2', 'JE3', 'JE4', 'L73', 'L80', 'LE55', 'ME99', 'NE82', 'NE83', 'NG70', 'OL95', 'OX6', 'OX8', 'PE99', 'SR9', 'SW1', 'W1', 'W1M', 'WC1', 'WC2', 'WD1', 'WD2', 'YO91', 'CH90', 'EN77', 'GIR', 'IM99', 'LS78', 'PO24', 'S94', 'SN80', 'SR43', 'TW98']
code_set = {c['code'] for c in codes}
link_set = {l['postcode'] for l in links}
present = [pc for pc in DROPS if pc in code_set or pc in link_set]
check('drops-absent-71', not present, str(present[:5]))
# --- 33 micro-hold legs stay absent (NSPL <10u, no GN place) ---
HOLDS = [
 ('B50', 'gb:county:worcestershire'),
 ('B77', 'gb:county:warwickshire'),
 ('B80', 'gb:county:worcestershire'),
 ('BN1', 'gb:county:west-sussex'),
 ('BN8', 'gb:county:west-sussex'),
 ('CB6', 'gb:county:norfolk'),
 ('CB7', 'gb:county:suffolk'),
 ('CM19', 'gb:county:hertfordshire'),
 ('CM22', 'gb:county:hertfordshire'),
 ('CV13', 'gb:county:warwickshire'),
 ('DE55', 'gb:county:nottinghamshire'),
 ('DE7', 'gb:county:nottinghamshire'),
 ('DE72', 'gb:county:leicestershire'),
 ('DE74', 'gb:county:nottinghamshire'),
 ('DY7', 'gb:county:worcestershire'),
 ('EX13', 'gb:county:dorset'),
 ('GL16', 'gb:county:monmouthshire'),
 ('GL55', 'gb:county:warwickshire'),
 ('GU14', 'gb:county:surrey'),
 ('GU6', 'gb:county:west-sussex'),
 ('GU8', 'gb:county:west-sussex'),
 ('LE17', 'gb:county:warwickshire'),
 ('LN1', 'gb:county:nottinghamshire'),
 ('LN6', 'gb:county:nottinghamshire'),
 ('NG10', 'gb:county:leicestershire'),
 ('NG10', 'gb:county:nottinghamshire'),
 ('NG13', 'gb:county:lincolnshire'),
 ('NR31', 'gb:county:suffolk'),
 ('OX7', 'gb:county:warwickshire'),
 ('PE14', 'gb:county:lincolnshire'),
 ('RH18', 'gb:county:west-sussex'),
 ('RH5', 'gb:county:west-sussex'),
 ('TN31', 'gb:county:kent'),
]
lpairs = {(l['postcode'], l['area_source_id']) for l in links}
got = [p for p in HOLDS if p in lpairs]
check('micro-holds-absent-33', not got, str(got[:3]))
# --- EOL + trailing newlines (areas LF; codes/links CRLF) ---
rawA, rawC, rawL = open(A, 'rb').read(), open(C, 'rb').read(), open(L, 'rb').read()
check('areas-lf-only', rawA.count(b'\r') == 0 and rawA.count(b'\n') == 118,
      f"cr={rawA.count(bytes([13]))} lf={rawA.count(bytes([10]))}")
check('codes-crlf-2944', rawC.count(b'\r\n') == 2944 and rawC.count(b'\r') == 2944 and rawC.count(b'\n') == 2944,
      f"cr={rawC.count(bytes([13]))} lf={rawC.count(bytes([10]))}")
check('links-crlf-3751', rawL.count(b'\r\n') == 3751 and rawL.count(b'\r') == 3751 and rawL.count(b'\n') == 3751,
      f"cr={rawL.count(bytes([13]))} lf={rawL.count(bytes([10]))}")
check('areas-trailing-nl', rawA.endswith(b'\n') and not rawA.endswith(b'\r\n'))
check('codes-trailing-crlf', rawC.endswith(b'\r\n'))
check('links-trailing-crlf', rawL.endswith(b'\r\n'))
print('ALL PASS' if not fails else f'{len(fails)} FAILURES')
sys.exit(1 if fails else 0)
