import csv, sys
from collections import Counter
AREAS = './packages/addressing/resources/geography/malaysia-address-areas.csv'
LINKS = './packages/addressing/resources/geography/malaysia-postal-code-areas.csv'
fails = []
def check(name, cond, detail=''):
    print(('PASS' if cond else 'FAIL'), name, detail)
    if not cond: fails.append(name)
rows = list(csv.DictReader(open(AREAS)))
links = list(csv.DictReader(open(LINKS)))
byid = {r['source_id']: r for r in rows}
K = 'my:subdistrict:district:selangor'
dang = [l for l in links if l['area_source_id'] not in byid]
check('no-dangling', not dang, str(dang[:3]))
prim = Counter(l['postcode'] for l in links if l['is_primary'] == 'true')
multi = [pc for pc, c in prim.items() if c != 1]
check('exactly-one-primary', not multi, str(multi[:5]))
check('retype balakong=bandar', byid[f'{K}:hulu-langat:balakong']['type'] == 'bandar')
check('retype serdang=pekan', byid[f'{K}:petaling:serdang']['type'] == 'pekan')
check('sabak-bernam-locality-removed', f'{K}:sabak-bernam:sabak-bernam' not in byid)
check('teluk-locality-removed', f'{K}:kuala-langat:teluk-panglima-garang' not in byid)
spots = [
 ('klang:bandar-klang','bandar','klang'),
 ('klang:bandar-sultan-sulaiman','bandar','klang'),
 ('klang:bandar-shah-alam','bandar','klang'),
 ('klang:pekan-bukit-kemuning','pekan','klang'),
 ('klang:pekan-kapar','pekan','klang'),
 ('klang:pekan-telok-menegun','pekan','klang'),
 ('klang:pekan-batu-empat','pekan','klang'),
 ('klang:pekan-pandamaran','pekan','klang'),
 ('kuala-langat:bandar-sijangkang','bandar','kuala-langat'),
 ('kuala-langat:bandar-telok-panglima-garang','bandar','kuala-langat'),
 ('kuala-langat:pekan-batu','pekan','kuala-langat'),
 ('kuala-langat:pekan-bukit-changgang','pekan','kuala-langat'),
 ('kuala-langat:pekan-chodoi','pekan','kuala-langat'),
 ('kuala-langat:pekan-jenjarom','pekan','kuala-langat'),
 ('kuala-langat:pekan-kancung','pekan','kuala-langat'),
 ('kuala-langat:pekan-kancung-darat','pekan','kuala-langat'),
 ('kuala-langat:pekan-kelanang-batu-enam','pekan','kuala-langat'),
 ('kuala-langat:pekan-morib','pekan','kuala-langat'),
 ('kuala-langat:pekan-permatang-pasir','pekan','kuala-langat'),
 ('kuala-langat:pekan-sijangkang','pekan','kuala-langat'),
 ('kuala-langat:pekan-simpang-morib','pekan','kuala-langat'),
 ('kuala-langat:pekan-sungai-manggis','pekan','kuala-langat'),
 ('kuala-langat:pekan-sungai-raba','pekan','kuala-langat'),
 ('kuala-langat:pekan-tanjong-duabelas','pekan','kuala-langat'),
 ('kuala-langat:pekan-telok-datok','pekan','kuala-langat'),
 ('kuala-langat:pekan-telok','pekan','kuala-langat'),
 ('kuala-langat:pekan-tongkah','pekan','kuala-langat'),
 ('kuala-selangor:bandar-kuala-selangor','bandar','kuala-selangor'),
 ('kuala-selangor:bandar-tanjong-karang','bandar','kuala-selangor'),
 ('kuala-selangor:pekan-asam-jawa','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-jeram','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-kampong-kuantan','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-kuala-sungai-buloh','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-pasir-penambang','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-simpang-tiga','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-tanjong-karang','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-bukit-belimbing','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-bukit-talang','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-kampong-baru-hulu-tiram-buruk','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-parit-mahang','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-simpang-tiga-ijok','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-sungai-sembilang','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-taman-pkns','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-tambak-jawa','pekan','kuala-selangor'),
 ('kuala-selangor:pekan-bestari-jaya','pekan','kuala-selangor'),
 ('sabak-bernam:pekan-bagan-terap','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-parit-enam','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-parit-sembilan','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-simpang-lima','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-sabak','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-sungai-air-tawar','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-sungai-sepintas','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-bagan-nakhoda-omar','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-parit-baru','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-pasir-panjang','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-sekinchan-site','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-sungai-haji-dorani','pekan','sabak-bernam'),
 ('sabak-bernam:pekan-sungai-nibong','pekan','sabak-bernam'),
 ('hulu-langat:bandar-cheras','bandar','hulu-langat'),
 ('hulu-langat:bandar-hulu-langat','bandar','hulu-langat'),
 ('hulu-langat:bandar-kajang','bandar','hulu-langat'),
 ('hulu-langat:bandar-semenyih','bandar','hulu-langat'),
 ('hulu-langat:bandar-ampang','bandar','hulu-langat'),
 ('hulu-langat:bandar-country-height','bandar','hulu-langat'),
 ('hulu-langat:bandar-batu-9-cheras','bandar','hulu-langat'),
 ('hulu-langat:bandar-batu-18-semenyih','bandar','hulu-langat'),
 ('hulu-langat:bandar-batu-26-beranang','bandar','hulu-langat'),
 ('hulu-langat:pekan-beranang','pekan','hulu-langat'),
 ('hulu-langat:pekan-kachau','pekan','hulu-langat'),
 ('hulu-langat:pekan-tarun','pekan','hulu-langat'),
 ('hulu-langat:pekan-bangi-lama','pekan','hulu-langat'),
 ('hulu-langat:pekan-batu-18-hulu-langat','pekan','hulu-langat'),
 ('hulu-langat:pekan-batu-23-sungai-lalang','pekan','hulu-langat'),
 ('hulu-langat:pekan-batu-26-beranang','pekan','hulu-langat'),
 ('hulu-langat:pekan-bukit-sungai-raya','pekan','hulu-langat'),
 ('hulu-langat:pekan-cheras','pekan','hulu-langat'),
 ('hulu-langat:pekan-desa-raya','pekan','hulu-langat'),
 ('hulu-langat:pekan-dusun-tua-hulu-langat','pekan','hulu-langat'),
 ('hulu-langat:pekan-kajang','pekan','hulu-langat'),
 ('hulu-langat:pekan-kampung-pasir-batu-14-semenyih','pekan','hulu-langat'),
 ('hulu-langat:pekan-kampung-sungai-tangkas','pekan','hulu-langat'),
 ('hulu-langat:pekan-rumah-murah-sungai-lui','pekan','hulu-langat'),
 ('hulu-langat:pekan-semenyih','pekan','hulu-langat'),
 ('hulu-langat:pekan-simpang-balak','pekan','hulu-langat'),
 ('hulu-langat:pekan-sri-nanding','pekan','hulu-langat'),
 ('hulu-langat:pekan-sungai-kembong-beranang','pekan','hulu-langat'),
 ('hulu-langat:pekan-sungai-lui','pekan','hulu-langat'),
 ('hulu-langat:pekan-sungai-makau','pekan','hulu-langat'),
 ('hulu-selangor:bandar-hulu-yam','bandar','hulu-selangor'),
 ('hulu-selangor:bandar-hulu-yam-baharu','bandar','hulu-selangor'),
 ('hulu-selangor:bandar-kalumpang','bandar','hulu-selangor'),
 ('hulu-selangor:bandar-rasa','bandar','hulu-selangor'),
 ('hulu-selangor:bandar-serendah','bandar','hulu-selangor'),
 ('hulu-selangor:bandar-batang-kali','bandar','hulu-selangor'),
 ('hulu-selangor:bandar-hulu-bernam-i','bandar','hulu-selangor'),
 ('hulu-selangor:bandar-hulu-bernam-ii','bandar','hulu-selangor'),
 ('hulu-selangor:bandar-sungai-chik','bandar','hulu-selangor'),
 ('hulu-selangor:pekan-kerling','pekan','hulu-selangor'),
 ('hulu-selangor:pekan-peretak','pekan','hulu-selangor'),
 ('hulu-selangor:pekan-simpang-sungai-choh','pekan','hulu-selangor'),
 ('petaling:bandar-damansara','bandar','petaling'),
 ('petaling:bandar-glenmarie','bandar','petaling'),
 ('petaling:bandar-petaling-jaya-selatan','bandar','petaling'),
 ('petaling:bandar-sri-damansara','bandar','petaling'),
 ('petaling:bandar-sunway','bandar','petaling'),
 ('petaling:pekan-batu-tiga','pekan','petaling'),
 ('petaling:pekan-merbau-sempak','pekan','petaling'),
 ('petaling:pekan-sungai-penchala','pekan','petaling'),
 ('petaling:pekan-cempaka','pekan','petaling'),
 ('petaling:pekan-country-height','pekan','petaling'),
 ('petaling:pekan-desa-puchong','pekan','petaling'),
 ('petaling:pekan-hicom','pekan','petaling'),
 ('petaling:pekan-kayu-ara','pekan','petaling'),
 ('petaling:pekan-kinrara','pekan','petaling'),
 ('petaling:pekan-baru-hicom','pekan','petaling'),
 ('petaling:pekan-baru-subang','pekan','petaling'),
 ('petaling:pekan-baru-sungai-besi','pekan','petaling'),
 ('petaling:pekan-baru-sungai-buloh','pekan','petaling'),
 ('petaling:pekan-penaga','pekan','petaling'),
 ('petaling:pekan-puchong-jaya','pekan','petaling'),
 ('petaling:pekan-puchong-perdana','pekan','petaling'),
 ('petaling:pekan-subang','pekan','petaling'),
 ('petaling:pekan-subang-jaya','pekan','petaling'),
 ('gombak:bandar-rawang','bandar','gombak'),
 ('gombak:bandar-hulu-klang','bandar','gombak'),
 ('gombak:bandar-kepong','bandar','gombak'),
 ('gombak:bandar-sungai-buloh','bandar','gombak'),
 ('gombak:bandar-sungai-pusu','bandar','gombak'),
 ('gombak:pekan-batu','pekan','gombak'),
 ('gombak:pekan-kuang','pekan','gombak'),
 ('gombak:pekan-mimaland','pekan','gombak'),
 ('gombak:pekan-pengkalan-kundang','pekan','gombak'),
 ('gombak:pekan-sungai-buloh','pekan','gombak'),
 ('gombak:pekan-templer','pekan','gombak'),
 ('sepang:bandar-sepang','bandar','sepang'),
 ('sepang:bandar-baru-bangi','bandar','sepang'),
 ('sepang:bandar-lapangan-terbang-antarabangsa-sepang','bandar','sepang'),
 ('sepang:bandar-sungai-merab','bandar','sepang'),
 ('sepang:pekan-dengkil','pekan','sepang'),
 ('sepang:pekan-salak','pekan','sepang'),
 ('sepang:pekan-batu-1-sepang','pekan','sepang'),
 ('sepang:pekan-bukit-bisa','pekan','sepang'),
 ('sepang:pekan-bukit-prang','pekan','sepang'),
 ('sepang:pekan-dato-bakar-baginda','pekan','sepang'),
 ('sepang:pekan-baru-salak-tinggi','pekan','sepang'),
 ('sepang:pekan-sungai-merab','pekan','sepang'),
 ('sepang:pekan-tanjung-mas','pekan','sepang'),
 ('sepang:pekan-tanjung-mas-1','pekan','sepang'),
]
ok = True
for slug, t, parent in spots:
    r = byid.get(f'{K}:{slug}')
    if not r or r['type'] != t or r['parent_source_id'] != f'my:district:selangor:{parent}' or r['level'] != '3':
        print('FAIL spot', slug, r); fails.append(f'spot {slug}'); ok = False
if ok: print(f'PASS all {len(spots)} add spots')
moves = [('41000',f'{K}:klang:bandar-klang'),('42150',f'{K}:klang:bandar-klang'),
 ('42200',f'{K}:klang:pekan-kapar'),
 ('42500',f'{K}:kuala-langat:bandar-telok-panglima-garang'),
 ('42425',f'{K}:kuala-langat:bandar-telok-panglima-garang'),
 ('42600',f'{K}:kuala-langat:jenjarom'),
 ('45000',f'{K}:kuala-selangor:bandar-kuala-selangor'),
 ('45500',f'{K}:kuala-selangor:bandar-tanjong-karang'),
 ('45800',f'{K}:kuala-selangor:pekan-jeram'),
 ('45600',f'{K}:kuala-selangor:pekan-bestari-jaya'),
 ('45200',f'{K}:sabak-bernam:pekan-sabak'),
 ('45100',f'{K}:sabak-bernam:pekan-sungai-air-tawar'),
 ('43200',f'{K}:hulu-langat:bandar-cheras'),
 ('43100',f'{K}:hulu-langat:bandar-hulu-langat'),
 ('43000',f'{K}:hulu-langat:bandar-kajang'),
 ('43500',f'{K}:hulu-langat:bandar-semenyih'),
 ('68000',f'{K}:hulu-langat:bandar-ampang'),
 ('43700',f'{K}:hulu-langat:pekan-beranang'),
 ('44300',f'{K}:hulu-selangor:bandar-batang-kali'),
 ('44100',f'{K}:hulu-selangor:pekan-kerling'),
 ('44200',f'{K}:hulu-selangor:bandar-rasa'),
 ('48200',f'{K}:hulu-selangor:bandar-serendah'),
 ('48000',f'{K}:gombak:bandar-rawang'),
 ('48050',f'{K}:gombak:bandar-rawang'),
 ('47000',f'{K}:gombak:bandar-sungai-buloh'),
 ('48100',f'{K}:gombak:batu-arang'),
 ('43900',f'{K}:sepang:bandar-sepang'),
 ('43800',f'{K}:sepang:pekan-dengkil'),
 ('64000',f'{K}:sepang:bandar-lapangan-terbang-antarabangsa-sepang')]
for pc, sid in moves:
    hits = [l for l in links if l['postcode']==pc and l['is_primary']=='true']
    check(f'{pc}-primary-{sid.split(":")[-1]}', len(hits)==1 and hits[0]['area_source_id']==sid, str(hits))
# city primaries that must NOT move
stays = [('42700',f'{K}:kuala-langat:banting'),('42800',f'{K}:kuala-langat:tanjong-sepat'),
 ('45700',f'{K}:kuala-selangor:bukit-rotan'),('45400',f'{K}:sabak-bernam:sekinchan'),
 ('45300',f'{K}:sabak-bernam:sungai-besar'),('43650',f'{K}:hulu-langat:bandar-baru-bangi'),
 ('44000',f'{K}:hulu-selangor:kuala-kubu-bharu'),('43400',f'{K}:petaling:serdang'),
 ('43300',f'{K}:petaling:seri-kembangan'),('68100',f'{K}:gombak:batu-caves'),
 ('35900','my:subdistrict:district:perak:muallim:tanjong-malim')]
for pc, sid in stays:
    hits = [l for l in links if l['postcode']==pc and l['is_primary']=='true']
    check(f'{pc}-stays-{sid.split(":")[-1]}', len(hits)==1 and hits[0]['area_source_id']==sid, str(hits))
for pc, slug in [
 ('41000','klang:klang'),
 ('41050','klang:klang'),
 ('41070','klang:klang'),
 ('41100','klang:klang'),
 ('41150','klang:klang'),
 ('41160','klang:klang'),
 ('41200','klang:klang'),
 ('41205','klang:klang'),
 ('41250','klang:klang'),
 ('41299','klang:klang'),
 ('41300','klang:klang'),
 ('41301','klang:klang'),
 ('41400','klang:klang'),
 ('41500','klang:klang'),
 ('41506','klang:klang'),
 ('41560','klang:klang'),
 ('41586','klang:klang'),
 ('41600','klang:klang'),
 ('41670','klang:klang'),
 ('41672','klang:klang'),
 ('41700','klang:klang'),
 ('41710','klang:klang'),
 ('41720','klang:klang'),
 ('41730','klang:klang'),
 ('41750','klang:klang'),
 ('41780','klang:klang'),
 ('41900','klang:klang'),
 ('41902','klang:klang'),
 ('41904','klang:klang'),
 ('41906','klang:klang'),
 ('41908','klang:klang'),
 ('41910','klang:klang'),
 ('41912','klang:klang'),
 ('41914','klang:klang'),
 ('41916','klang:klang'),
 ('41918','klang:klang'),
 ('41990','klang:klang'),
 ('42100','klang:klang'),
 ('42150','klang:klang'),
 ('42200','klang:kapar'),
 ('42209','klang:kapar'),
 ('42425','kuala-langat:telok-panglima-garang'),
 ('42507','kuala-langat:telok-panglima-garang'),
 ('42509','kuala-langat:telok-panglima-garang'),
 ('45000','kuala-selangor:kuala-selangor'),
 ('45010','kuala-selangor:kuala-selangor'),
 ('45500','kuala-selangor:tanjong-karang'),
 ('45800','kuala-selangor:jeram'),
 ('45600','kuala-selangor:bestari-jaya'),
 ('45607','kuala-selangor:bestari-jaya'),
 ('45609','kuala-selangor:bestari-jaya'),
 ('45620','kuala-selangor:bestari-jaya'),
 ('45630','kuala-selangor:bestari-jaya'),
 ('43200','hulu-langat:cheras'),
 ('43207','hulu-langat:cheras'),
 ('43100','hulu-langat:hulu-langat'),
 ('43000','hulu-langat:kajang'),
 ('43007','hulu-langat:kajang'),
 ('43009','hulu-langat:kajang'),
 ('43558','hulu-langat:kajang'),
 ('43500','hulu-langat:semenyih'),
 ('68000','hulu-langat:ampang'),
 ('43700','hulu-langat:beranang'),
 ('43701','hulu-langat:beranang'),
 ('44300','hulu-selangor:batang-kali'),
 ('44309','hulu-selangor:batang-kali'),
 ('44330','hulu-selangor:batang-kali'),
 ('44100','hulu-selangor:kerling'),
 ('44200','hulu-selangor:rasa'),
 ('48200','hulu-selangor:serendah'),
 ('48250','hulu-selangor:serendah'),
 ('48000','gombak:rawang'),
 ('48009','gombak:rawang'),
 ('48010','gombak:rawang'),
 ('48020','gombak:rawang'),
 ('48050','gombak:rawang'),
 ('48300','gombak:rawang'),
 ('48302','gombak:rawang'),
 ('47000','petaling:sungai-buloh'),
 ('47020','petaling:sungai-buloh'),
 ('47031','petaling:sungai-buloh'),
 ('43900','sepang:sepang'),
 ('43800','sepang:dengkil'),
 ('43807','sepang:dengkil'),
 ('42000','klang:bandar-sultan-sulaiman'),
 ('42000','klang:pekan-pandamaran'),
 ('40460','klang:pekan-bukit-kemuning'),
 ('41000','klang:pekan-telok-menegun'),
 ('42500','kuala-langat:bandar-sijangkang'),
 ('42800','kuala-langat:pekan-batu'),
 ('42700','kuala-langat:pekan-bukit-changgang'),
 ('42700','kuala-langat:pekan-chodoi'),
 ('42700','kuala-langat:pekan-kelanang-batu-enam'),
 ('42700','kuala-langat:pekan-morib'),
 ('42700','kuala-langat:pekan-permatang-pasir'),
 ('42700','kuala-langat:pekan-sungai-manggis'),
 ('42700','kuala-langat:pekan-sungai-raba'),
 ('42700','kuala-langat:pekan-tanjong-duabelas'),
 ('42700','kuala-langat:pekan-telok-datok'),
 ('45700','kuala-selangor:pekan-asam-jawa'),
 ('45600','kuala-selangor:pekan-kampong-kuantan'),
 ('45000','kuala-selangor:pekan-pasir-penambang'),
 ('45000','kuala-selangor:pekan-bukit-belimbing'),
 ('45800','kuala-selangor:pekan-simpang-tiga'),
 ('45800','kuala-selangor:pekan-parit-mahang'),
 ('45800','kuala-selangor:pekan-sungai-sembilang'),
 ('45800','kuala-selangor:pekan-tambak-jawa'),
 ('45600','kuala-selangor:pekan-simpang-tiga-ijok'),
 ('45500','kuala-selangor:pekan-kampong-baru-hulu-tiram-buruk'),
 ('45300','sabak-bernam:pekan-parit-enam'),
 ('45300','sabak-bernam:pekan-parit-sembilan'),
 ('45300','sabak-bernam:pekan-simpang-lima'),
 ('45300','sabak-bernam:pekan-sungai-haji-dorani'),
 ('45400','sabak-bernam:pekan-sekinchan-site'),
 ('45400','sabak-bernam:pekan-sungai-nibong'),
 ('45209','sabak-bernam:pekan-bagan-terap'),
 ('45200','sabak-bernam:pekan-sungai-sepintas'),
 ('45100','sabak-bernam:pekan-parit-baru'),
 ('43000','hulu-langat:bandar-country-height'),
 ('43200','hulu-langat:bandar-batu-9-cheras'),
 ('43207','hulu-langat:bandar-batu-9-cheras'),
 ('43700','hulu-langat:bandar-batu-26-beranang'),
 ('43500','hulu-langat:pekan-kachau'),
 ('43500','hulu-langat:pekan-tarun'),
 ('43500','hulu-langat:pekan-kampung-pasir-batu-14-semenyih'),
 ('43500','hulu-langat:pekan-batu-23-sungai-lalang'),
 ('43000','hulu-langat:pekan-bangi-lama'),
 ('43000','hulu-langat:pekan-kampung-sungai-tangkas'),
 ('43000','hulu-langat:pekan-simpang-balak'),
 ('43000','hulu-langat:pekan-sungai-kembong-beranang'),
 ('43100','hulu-langat:pekan-batu-18-hulu-langat'),
 ('43100','hulu-langat:pekan-desa-raya'),
 ('43100','hulu-langat:pekan-dusun-tua-hulu-langat'),
 ('43100','hulu-langat:pekan-sri-nanding'),
 ('43100','hulu-langat:pekan-sungai-lui'),
 ('44300','hulu-selangor:bandar-hulu-yam'),
 ('44300','hulu-selangor:bandar-hulu-yam-baharu'),
 ('44300','hulu-selangor:bandar-sungai-chik'),
 ('44100','hulu-selangor:bandar-kalumpang'),
 ('35900','hulu-selangor:bandar-hulu-bernam-i'),
 ('35900','hulu-selangor:bandar-hulu-bernam-ii'),
 ('48000','hulu-selangor:pekan-simpang-sungai-choh'),
 ('40150','petaling:bandar-glenmarie'),
 ('40150','petaling:pekan-hicom'),
 ('40150','petaling:pekan-subang'),
 ('40150','petaling:pekan-baru-subang'),
 ('40150','petaling:pekan-batu-tiga'),
 ('40160','petaling:pekan-merbau-sempak'),
 ('40160','petaling:pekan-baru-sungai-buloh'),
 ('46000','petaling:pekan-sungai-penchala'),
 ('60000','petaling:pekan-sungai-penchala'),
 ('46000','petaling:pekan-penaga'),
 ('47400','petaling:pekan-kayu-ara'),
 ('47100','petaling:pekan-kinrara'),
 ('47170','petaling:pekan-kinrara'),
 ('47180','petaling:pekan-kinrara'),
 ('47190','petaling:pekan-kinrara'),
 ('47170','petaling:pekan-puchong-jaya'),
 ('47150','petaling:pekan-puchong-perdana'),
 ('47500','petaling:bandar-sunway'),
 ('52200','petaling:bandar-sri-damansara'),
 ('43300','petaling:pekan-baru-sungai-besi'),
 ('48020','gombak:kundang'),
 ('48050','gombak:kundang'),
 ('68100','gombak:selayang'),
 ('53100','gombak:gombak-setia'),
 ('53100','gombak:bandar-sungai-pusu'),
 ('52100','gombak:bandar-kepong'),
 ('54200','gombak:bandar-hulu-klang'),
 ('48050','gombak:pekan-pengkalan-kundang'),
 ('48000','gombak:pekan-templer'),
 ('68100','gombak:pekan-templer'),
 ('43900','sepang:baru-salak-tinggi'),
 ('43900','sepang:pekan-salak'),
 ('43900','sepang:pekan-tanjung-mas'),
 ('43900','sepang:pekan-tanjung-mas-1'),
 ('43000','sepang:bandar-sungai-merab'),
 ('43650','sepang:bandar-baru-bangi'),
]:
    sid = f'{K}:{slug}'
    hits = [l for l in links if l['postcode']==pc and l['area_source_id']==sid]
    check(f'{pc}-secondary-{slug.split(":")[-1]}', len(hits)==1 and hits[0]['is_primary']=='false', str(hits))
for slug in ['klang:bandar-shah-alam','klang:pekan-batu-empat',
             'kuala-langat:pekan-jenjarom','kuala-langat:pekan-kancung','kuala-langat:pekan-kancung-darat',
             'kuala-langat:pekan-sijangkang','kuala-langat:pekan-simpang-morib','kuala-langat:pekan-telok',
             'kuala-langat:pekan-tongkah',
             'kuala-selangor:pekan-kuala-sungai-buloh','kuala-selangor:pekan-tanjong-karang',
             'kuala-selangor:pekan-bukit-talang','kuala-selangor:pekan-taman-pkns',
             'sabak-bernam:pekan-bagan-nakhoda-omar','sabak-bernam:pekan-pasir-panjang',
             'hulu-langat:bandar-batu-18-semenyih','hulu-langat:pekan-batu-26-beranang',
             'hulu-langat:pekan-bukit-sungai-raya','hulu-langat:pekan-cheras','hulu-langat:pekan-kajang',
             'hulu-langat:pekan-rumah-murah-sungai-lui','hulu-langat:pekan-semenyih',
             'hulu-langat:pekan-sungai-makau','hulu-selangor:pekan-peretak',
             'petaling:bandar-damansara','petaling:bandar-petaling-jaya-selatan','petaling:pekan-cempaka',
             'petaling:pekan-country-height','petaling:pekan-desa-puchong','petaling:pekan-baru-hicom',
             'petaling:pekan-subang-jaya',
             'gombak:pekan-batu','gombak:pekan-kuang','gombak:pekan-mimaland','gombak:pekan-sungai-buloh',
             'sepang:pekan-batu-1-sepang','sepang:pekan-bukit-bisa','sepang:pekan-bukit-prang',
             'sepang:pekan-dato-bakar-baginda','sepang:pekan-baru-salak-tinggi','sepang:pekan-sungai-merab']:
    sid = f'{K}:{slug}'
    check(f'{slug}-linkless', not [l for l in links if l['area_source_id']==sid])
for d, mbp in [('klang',12),('kuala-langat',29),('kuala-selangor',28),('sabak-bernam',20),
               ('hulu-langat',39),('hulu-selangor',26),('petaling',33),('gombak',20),('sepang',20)]:
    n = sum(1 for r in rows if r['parent_source_id']==f'my:district:selangor:{d}' and r['type'] in ('mukim','bandar','pekan'))
    check(f'{d}-count-{mbp}', n==mbp, str(n))
print('ALL PASS' if not fails else f'{len(fails)} FAILURES')
sys.exit(1 if fails else 0)
