import csv, re, sys
from collections import Counter
# Turkiye gate. M7 revisit: tree verified clean against ISO 3166-2:TR
# (81 provinces, codes 01-81) + Districts-of-Turkey per-province tables
# (973 ilceler = 922 named + 51 Merkez; wiki omits Merkez rows and
# drops Gomec from the Balikesir table - both confirmed ours-correct);
# postal verify-only: 2896 codes = GeoNames TR dump minus 57 KKTC 99xxx
# rows; every primary agrees with the GN modal admin2 (269 via Merkez
# equivalence, 6 via stale-GN spellings); all 7 multis adjudicated keeps
# with GN + worldpostalcode town-page place evidence (16270 + 44000 are
# GN 1-1 ties, primaries kept per no-move-on-ties). Run from repo root:
# python3 docs/agents/audit/gate_tr.py [repo-root]
ROOT = sys.argv[1] if len(sys.argv) > 1 else '.'
A = f'{ROOT}/packages/addressing/resources/geography/turkiye-address-areas.csv'
C = f'{ROOT}/packages/addressing/resources/geography/turkiye-postal-codes.csv'
L = f'{ROOT}/packages/addressing/resources/geography/turkiye-postal-code-areas.csv'
fails = []
def check(name, cond, detail=''):
    print(('PASS' if cond else 'FAIL'), name, detail)
    if not cond: fails.append(name)
rows = list(csv.DictReader(open(A)))
codes = list(csv.DictReader(open(C)))
links = list(csv.DictReader(open(L)))
byid = {r['source_id']: r for r in rows}
# --- tree: 81 provinces + 973 districts ---
check('areas-1054', len(rows) == 1054, str(len(rows)))
check('provinces-81', sum(1 for r in rows if r['type'] == 'province') == 81)
check('districts-973', sum(1 for r in rows if r['type'] == 'district') == 973)
# ISO 3166-2:TR: source_id -> (name, plate code).
iso = {
 'tr:province:adana': ('Adana', '01'),
 'tr:province:adyaman': ('Adıyaman', '02'),
 'tr:province:afyonkarahisar': ('Afyonkarahisar', '03'),
 'tr:province:agr': ('Ağrı', '04'),
 'tr:province:amasya': ('Amasya', '05'),
 'tr:province:ankara': ('Ankara', '06'),
 'tr:province:antalya': ('Antalya', '07'),
 'tr:province:artvin': ('Artvin', '08'),
 'tr:province:aydn': ('Aydın', '09'),
 'tr:province:balkesir': ('Balıkesir', '10'),
 'tr:province:bilecik': ('Bilecik', '11'),
 'tr:province:bingol': ('Bingöl', '12'),
 'tr:province:bitlis': ('Bitlis', '13'),
 'tr:province:bolu': ('Bolu', '14'),
 'tr:province:burdur': ('Burdur', '15'),
 'tr:province:bursa': ('Bursa', '16'),
 'tr:province:canakkale': ('Çanakkale', '17'),
 'tr:province:cankr': ('Çankırı', '18'),
 'tr:province:corum': ('Çorum', '19'),
 'tr:province:denizli': ('Denizli', '20'),
 'tr:province:diyarbakr': ('Diyarbakır', '21'),
 'tr:province:edirne': ('Edirne', '22'),
 'tr:province:elazg': ('Elazığ', '23'),
 'tr:province:erzincan': ('Erzincan', '24'),
 'tr:province:erzurum': ('Erzurum', '25'),
 'tr:province:eskisehir': ('Eskişehir', '26'),
 'tr:province:gaziantep': ('Gaziantep', '27'),
 'tr:province:giresun': ('Giresun', '28'),
 'tr:province:gumushane': ('Gümüşhane', '29'),
 'tr:province:hakkari': ('Hakkâri', '30'),
 'tr:province:hatay': ('Hatay', '31'),
 'tr:province:isparta': ('Isparta', '32'),
 'tr:province:mersin': ('Mersin', '33'),
 'tr:province:istanbul': ('İstanbul', '34'),
 'tr:province:izmir': ('İzmir', '35'),
 'tr:province:kars': ('Kars', '36'),
 'tr:province:kastamonu': ('Kastamonu', '37'),
 'tr:province:kayseri': ('Kayseri', '38'),
 'tr:province:krklareli': ('Kırklareli', '39'),
 'tr:province:krsehir': ('Kırşehir', '40'),
 'tr:province:kocaeli': ('Kocaeli', '41'),
 'tr:province:konya': ('Konya', '42'),
 'tr:province:kutahya': ('Kütahya', '43'),
 'tr:province:malatya': ('Malatya', '44'),
 'tr:province:manisa': ('Manisa', '45'),
 'tr:province:kahramanmaras': ('Kahramanmaraş', '46'),
 'tr:province:mardin': ('Mardin', '47'),
 'tr:province:mugla': ('Muğla', '48'),
 'tr:province:mus': ('Muş', '49'),
 'tr:province:nevsehir': ('Nevşehir', '50'),
 'tr:province:nigde': ('Niğde', '51'),
 'tr:province:ordu': ('Ordu', '52'),
 'tr:province:rize': ('Rize', '53'),
 'tr:province:sakarya': ('Sakarya', '54'),
 'tr:province:samsun': ('Samsun', '55'),
 'tr:province:siirt': ('Siirt', '56'),
 'tr:province:sinop': ('Sinop', '57'),
 'tr:province:sivas': ('Sivas', '58'),
 'tr:province:tekirdag': ('Tekirdağ', '59'),
 'tr:province:tokat': ('Tokat', '60'),
 'tr:province:trabzon': ('Trabzon', '61'),
 'tr:province:tunceli': ('Tunceli', '62'),
 'tr:province:sanlurfa': ('Şanlıurfa', '63'),
 'tr:province:usak': ('Uşak', '64'),
 'tr:province:van': ('Van', '65'),
 'tr:province:yozgat': ('Yozgat', '66'),
 'tr:province:zonguldak': ('Zonguldak', '67'),
 'tr:province:aksaray': ('Aksaray', '68'),
 'tr:province:bayburt': ('Bayburt', '69'),
 'tr:province:karaman': ('Karaman', '70'),
 'tr:province:krkkale': ('Kırıkkale', '71'),
 'tr:province:batman': ('Batman', '72'),
 'tr:province:srnak': ('Şırnak', '73'),
 'tr:province:bartn': ('Bartın', '74'),
 'tr:province:ardahan': ('Ardahan', '75'),
 'tr:province:igdr': ('Iğdır', '76'),
 'tr:province:yalova': ('Yalova', '77'),
 'tr:province:karabuk': ('Karabük', '78'),
 'tr:province:kilis': ('Kilis', '79'),
 'tr:province:osmaniye': ('Osmaniye', '80'),
 'tr:province:duzce': ('Düzce', '81'),
}
bad = [sid for sid, (name, code) in iso.items()
       if sid not in byid or byid[sid]['name'] != name
       or byid[sid]['type'] != 'province' or byid[sid]['code'] != code
       or byid[sid]['level'] != '1' or byid[sid]['parent_source_id']]
check('iso-81', not bad, str(bad[:3]))
# Per-province district counts (Districts-of-Turkey tables + Merkez).
exp_parent = {
 'tr:province:adana': 15,
 'tr:province:adyaman': 9,
 'tr:province:afyonkarahisar': 18,
 'tr:province:agr': 8,
 'tr:province:amasya': 7,
 'tr:province:ankara': 25,
 'tr:province:antalya': 19,
 'tr:province:artvin': 9,
 'tr:province:aydn': 17,
 'tr:province:balkesir': 20,
 'tr:province:bilecik': 8,
 'tr:province:bingol': 8,
 'tr:province:bitlis': 7,
 'tr:province:bolu': 9,
 'tr:province:burdur': 11,
 'tr:province:bursa': 17,
 'tr:province:canakkale': 12,
 'tr:province:cankr': 12,
 'tr:province:corum': 14,
 'tr:province:denizli': 19,
 'tr:province:diyarbakr': 17,
 'tr:province:edirne': 9,
 'tr:province:elazg': 11,
 'tr:province:erzincan': 9,
 'tr:province:erzurum': 20,
 'tr:province:eskisehir': 14,
 'tr:province:gaziantep': 9,
 'tr:province:giresun': 16,
 'tr:province:gumushane': 6,
 'tr:province:hakkari': 5,
 'tr:province:hatay': 15,
 'tr:province:isparta': 13,
 'tr:province:mersin': 13,
 'tr:province:istanbul': 39,
 'tr:province:izmir': 30,
 'tr:province:kars': 8,
 'tr:province:kastamonu': 20,
 'tr:province:kayseri': 16,
 'tr:province:krklareli': 8,
 'tr:province:krsehir': 7,
 'tr:province:kocaeli': 12,
 'tr:province:konya': 31,
 'tr:province:kutahya': 13,
 'tr:province:malatya': 13,
 'tr:province:manisa': 17,
 'tr:province:kahramanmaras': 11,
 'tr:province:mardin': 10,
 'tr:province:mugla': 13,
 'tr:province:mus': 6,
 'tr:province:nevsehir': 8,
 'tr:province:nigde': 6,
 'tr:province:ordu': 19,
 'tr:province:rize': 12,
 'tr:province:sakarya': 16,
 'tr:province:samsun': 17,
 'tr:province:siirt': 7,
 'tr:province:sinop': 9,
 'tr:province:sivas': 17,
 'tr:province:tekirdag': 11,
 'tr:province:tokat': 12,
 'tr:province:trabzon': 18,
 'tr:province:tunceli': 8,
 'tr:province:sanlurfa': 13,
 'tr:province:usak': 6,
 'tr:province:van': 13,
 'tr:province:yozgat': 14,
 'tr:province:zonguldak': 8,
 'tr:province:aksaray': 8,
 'tr:province:bayburt': 3,
 'tr:province:karaman': 6,
 'tr:province:krkkale': 9,
 'tr:province:batman': 6,
 'tr:province:srnak': 7,
 'tr:province:bartn': 4,
 'tr:province:ardahan': 6,
 'tr:province:igdr': 4,
 'tr:province:yalova': 6,
 'tr:province:karabuk': 6,
 'tr:province:kilis': 4,
 'tr:province:osmaniye': 7,
 'tr:province:duzce': 8,
}
got_parent = Counter(r['parent_source_id'] for r in rows if r['level'] == '2')
wrong = [sid for sid, n in exp_parent.items() if got_parent.get(sid, 0) != n]
check('per-parent-counts-81', not wrong, str(wrong[:5]))
check('merkez-51', sum(1 for r in rows if r['level'] == '2' and r['name'] == 'Merkez') == 51)
check('districts-codeless', all(r['code'] == '' for r in rows if r['level'] == '2'))
orph = [r['source_id'] for r in rows if r['parent_source_id'] and r['parent_source_id'] not in byid]
check('no-orphans', not orph, str(orph[:3]))
# Key district pins (post-2012 splits + stale-GN spellings).
pin_d = {
 'tr:district:hakkari:derecik': ('Derecik', 'tr:province:hakkari'),
 'tr:district:aksaray:sultanhan': ('Sultanhanı', 'tr:province:aksaray'),
 'tr:district:artvin:kemalpasa': ('Kemalpaşa', 'tr:province:artvin'),
 'tr:district:balkesir:gomec': ('Gömeç', 'tr:province:balkesir'),
 'tr:district:siirt:tillo': ('Tillo', 'tr:province:siirt'),
 'tr:district:agr:dogubayazt': ('Doğubayazıt', 'tr:province:agr'),
 'tr:district:kahramanmaras:caglayancerit': ('Çağlayancerit', 'tr:province:kahramanmaras'),
 'tr:district:samsun:19-mays': ('19 Mayıs', 'tr:province:samsun'),
 'tr:district:ankara:kahramankazan': ('Kahramankazan', 'tr:province:ankara'),
}
bad = [sid for sid, (name, par) in pin_d.items()
       if sid not in byid or byid[sid]['name'] != name
       or byid[sid]['parent_source_id'] != par or byid[sid]['level'] != '2']
check('district-pins-9', not bad, str(bad[:3]))
# --- postal: 2896 codes / 2903 links ---
check('codes-2896', len(codes) == 2896, str(len(codes)))
check('links-2903', len(links) == 2903, str(len(links)))
bad = [c['code'] for c in codes if not re.match(r'^\d{5}$', c['code'])]
check('code-format-5n', not bad, str(bad[:3]))
check('no-99xxx', not [c['code'] for c in codes if c['code'].startswith('99')])
dang = [l for l in links if l['area_source_id'] not in byid]
check('no-dangling', not dang, str(dang[:3]))
cset = {c['code'] for c in codes}
lset = {l['postcode'] for l in links}
check('codes-linked-both-ways', cset == lset,
      f'unlinked={sorted(cset - lset)[:3]} dangling={sorted(lset - cset)[:3]}')
prim = Counter(l['postcode'] for l in links if l['is_primary'] == 'true')
multi = [pc for pc, c in prim.items() if c != 1]
check('exactly-one-primary', len(prim) == 2896 and not multi,
      f'primaries={len(prim)} multi={multi[:3]}')
check('rel-served-by', all(l['relationship_type'] == 'served_by' for l in links))
# Every primary postcode prefix matches its province plate.
plate = {r['source_id']: r['code'] for r in rows if r['level'] == '1'}
mis = [l['postcode'] for l in links if l['is_primary'] == 'true'
       and l['postcode'][:2] != plate[byid[l['area_source_id']]['parent_source_id']]]
check('prefix-plate-match', not mis, str(mis[:3]))
counts = Counter(l['postcode'] for l in links)
multis = sorted(pc for pc, c in counts.items() if c > 1)
check('multis-7', multis == ['09670', '16270', '16370', '19800', '35730', '44000', '55530'], str(multis))
# Full multi map (M7-adjudicated keeps; GN + town-page tallies noted).
exp = {
 '09670': [('tr:district:aydn:buharkent', 'true'), ('tr:district:aydn:kocarl', 'false')],  # GN 9-2
 '16270': [('tr:district:bursa:osmangazi', 'true'), ('tr:district:bursa:yldrm', 'false')],  # GN 1-1 tie
 '16370': [('tr:district:bursa:osmangazi', 'true'), ('tr:district:bursa:yldrm', 'false')],  # GN 29-2
 '19800': [('tr:district:corum:bayat', 'true'), ('tr:district:corum:dodurga', 'false')],  # GN 39-1 Akkaya
 '35730': [('tr:district:izmir:kemalpasa', 'true'), ('tr:district:izmir:bergama', 'false')],  # GN 30-15
 '44000': [('tr:district:malatya:yesilyurt', 'true'), ('tr:district:malatya:battalgazi', 'false')],  # GN 1-1 tie
 '55530': [('tr:district:samsun:salpazar', 'true'), ('tr:district:samsun:tekkekoy', 'false')],  # GN 33-1
}
got = {}
for l in links:
    if l['postcode'] in exp:
        got.setdefault(l['postcode'], []).append((l['area_source_id'], l['is_primary']))
ok = all(sorted(got.get(pc, [])) == sorted(v) for pc, v in exp.items())
check('multi-map-7', ok, str({k: got.get(k) for k in exp if sorted(got.get(k, [])) != sorted(exp[k])}))
# Triple-corroborated anchors (GN + town page + OSM where covered).
pin = {l['postcode']: l['area_source_id'] for l in links if l['is_primary'] == 'true'}
check('pin-01010-seyhan', pin.get('01010') == 'tr:district:adana:seyhan')
check('pin-06050-altindag', pin.get('06050') == 'tr:district:ankara:altndag')
check('pin-34010-zeytinburnu', pin.get('34010') == 'tr:district:istanbul:zeytinburnu')
check('pin-07010-muratpasa', pin.get('07010') == 'tr:district:antalya:muratpasa')
check('pin-61000-ortahisar', pin.get('61000') == 'tr:district:trabzon:ortahisar')
check('pin-63000-eyyubiye', pin.get('63000') == 'tr:district:sanlurfa:eyyubiye')
check('pin-10715-gomec', pin.get('10715') == 'tr:district:balkesir:gomec')
check('pin-59520-kapakli', pin.get('59520') == 'tr:district:tekirdag:kapakl')
check('pin-38310-talas', pin.get('38310') == 'tr:district:kayseri:talas')
check('pin-30800-semdinli', pin.get('30800') == 'tr:district:hakkari:semdinli')
check('pin-68190-merkez', pin.get('68190') == 'tr:district:aksaray:merkez')
check('pin-08610-hopa', pin.get('08610') == 'tr:district:artvin:hopa')
# Per-district primary counts (970 covered; 3 post-2017 splits codeless).
have = Counter(l['area_source_id'] for l in links if l['is_primary'] == 'true')
exp_counts = {
 'tr:district:adana:aladag': 1,
 'tr:district:adana:ceyhan': 5,
 'tr:district:adana:cukurova': 3,
 'tr:district:adana:feke': 1,
 'tr:district:adana:imamoglu': 1,
 'tr:district:adana:karaisal': 1,
 'tr:district:adana:karatas': 1,
 'tr:district:adana:kozan': 5,
 'tr:district:adana:pozant': 2,
 'tr:district:adana:saimbeyli': 1,
 'tr:district:adana:sarcam': 7,
 'tr:district:adana:seyhan': 21,
 'tr:district:adana:tufanbeyli': 1,
 'tr:district:adana:yumurtalk': 1,
 'tr:district:adana:yuregir': 13,
 'tr:district:adyaman:besni': 6,
 'tr:district:adyaman:celikhan': 2,
 'tr:district:adyaman:gerger': 1,
 'tr:district:adyaman:golbas': 4,
 'tr:district:adyaman:kahta': 3,
 'tr:district:adyaman:merkez': 9,
 'tr:district:adyaman:samsat': 1,
 'tr:district:adyaman:sincik': 2,
 'tr:district:adyaman:tut': 1,
 'tr:district:afyonkarahisar:basmakc': 1,
 'tr:district:afyonkarahisar:bayat': 1,
 'tr:district:afyonkarahisar:bolvadin': 3,
 'tr:district:afyonkarahisar:cay': 3,
 'tr:district:afyonkarahisar:cobanlar': 2,
 'tr:district:afyonkarahisar:dazkr': 1,
 'tr:district:afyonkarahisar:dinar': 3,
 'tr:district:afyonkarahisar:emirdag': 2,
 'tr:district:afyonkarahisar:evciler': 1,
 'tr:district:afyonkarahisar:hocalar': 1,
 'tr:district:afyonkarahisar:ihsaniye': 5,
 'tr:district:afyonkarahisar:iscehisar': 3,
 'tr:district:afyonkarahisar:kzloren': 1,
 'tr:district:afyonkarahisar:merkez': 18,
 'tr:district:afyonkarahisar:sandkl': 2,
 'tr:district:afyonkarahisar:sinanpasa': 11,
 'tr:district:afyonkarahisar:suhut': 3,
 'tr:district:afyonkarahisar:sultandag': 4,
 'tr:district:agr:diyadin': 1,
 'tr:district:agr:dogubayazt': 2,
 'tr:district:agr:eleskirt': 1,
 'tr:district:agr:hamur': 1,
 'tr:district:agr:merkez': 3,
 'tr:district:agr:patnos': 1,
 'tr:district:agr:taslcay': 1,
 'tr:district:agr:tutak': 1,
 'tr:district:aksaray:agacoren': 1,
 'tr:district:aksaray:eskil': 2,
 'tr:district:aksaray:gulagac': 3,
 'tr:district:aksaray:guzelyurt': 2,
 'tr:district:aksaray:merkez': 12,
 'tr:district:aksaray:ortakoy': 1,
 'tr:district:aksaray:saryahsi': 1,
 'tr:district:aksaray:sultanhan': 0,
 'tr:district:amasya:goynucek': 1,
 'tr:district:amasya:gumushackoy': 1,
 'tr:district:amasya:hamamozu': 1,
 'tr:district:amasya:merkez': 5,
 'tr:district:amasya:merzifon': 1,
 'tr:district:amasya:suluova': 1,
 'tr:district:amasya:tasova': 2,
 'tr:district:ankara:akyurt': 2,
 'tr:district:ankara:altndag': 14,
 'tr:district:ankara:ayas': 1,
 'tr:district:ankara:bala': 2,
 'tr:district:ankara:beypazar': 4,
 'tr:district:ankara:camldere': 1,
 'tr:district:ankara:cankaya': 23,
 'tr:district:ankara:cubuk': 1,
 'tr:district:ankara:elmadag': 2,
 'tr:district:ankara:etimesgut': 8,
 'tr:district:ankara:evren': 1,
 'tr:district:ankara:golbas': 1,
 'tr:district:ankara:gudul': 4,
 'tr:district:ankara:haymana': 2,
 'tr:district:ankara:kahramankazan': 1,
 'tr:district:ankara:kalecik': 1,
 'tr:district:ankara:kecioren': 9,
 'tr:district:ankara:kzlcahamam': 1,
 'tr:district:ankara:mamak': 12,
 'tr:district:ankara:nallhan': 3,
 'tr:district:ankara:polatl': 1,
 'tr:district:ankara:pursaklar': 2,
 'tr:district:ankara:sereflikochisar': 1,
 'tr:district:ankara:sincan': 10,
 'tr:district:ankara:yenimahalle': 9,
 'tr:district:antalya:akseki': 2,
 'tr:district:antalya:aksu': 2,
 'tr:district:antalya:alanya': 15,
 'tr:district:antalya:demre': 1,
 'tr:district:antalya:dosemealt': 3,
 'tr:district:antalya:elmal': 3,
 'tr:district:antalya:finike': 5,
 'tr:district:antalya:gazipasa': 2,
 'tr:district:antalya:gundogmus': 1,
 'tr:district:antalya:ibrad': 2,
 'tr:district:antalya:kas': 7,
 'tr:district:antalya:kemer': 4,
 'tr:district:antalya:kepez': 9,
 'tr:district:antalya:konyaalt': 3,
 'tr:district:antalya:korkuteli': 4,
 'tr:district:antalya:kumluca': 4,
 'tr:district:antalya:manavgat': 3,
 'tr:district:antalya:muratpasa': 10,
 'tr:district:antalya:serik': 9,
 'tr:district:ardahan:cldr': 1,
 'tr:district:ardahan:damal': 1,
 'tr:district:ardahan:gole': 1,
 'tr:district:ardahan:hanak': 1,
 'tr:district:ardahan:merkez': 1,
 'tr:district:ardahan:posof': 1,
 'tr:district:artvin:ardanuc': 2,
 'tr:district:artvin:arhavi': 2,
 'tr:district:artvin:borcka': 2,
 'tr:district:artvin:hopa': 3,
 'tr:district:artvin:kemalpasa': 0,
 'tr:district:artvin:merkez': 2,
 'tr:district:artvin:murgul': 2,
 'tr:district:artvin:savsat': 2,
 'tr:district:artvin:yusufeli': 2,
 'tr:district:aydn:bozdogan': 2,
 'tr:district:aydn:buharkent': 1,
 'tr:district:aydn:cine': 2,
 'tr:district:aydn:didim': 4,
 'tr:district:aydn:efeler': 9,
 'tr:district:aydn:germencik': 4,
 'tr:district:aydn:incirliova': 2,
 'tr:district:aydn:karacasu': 4,
 'tr:district:aydn:karpuzlu': 1,
 'tr:district:aydn:kocarl': 2,
 'tr:district:aydn:kosk': 1,
 'tr:district:aydn:kusadas': 3,
 'tr:district:aydn:kuyucak': 5,
 'tr:district:aydn:nazilli': 3,
 'tr:district:aydn:soke': 8,
 'tr:district:aydn:sultanhisar': 3,
 'tr:district:aydn:yenipazar': 1,
 'tr:district:balkesir:alteylul': 7,
 'tr:district:balkesir:ayvalk': 5,
 'tr:district:balkesir:balya': 2,
 'tr:district:balkesir:bandrma': 3,
 'tr:district:balkesir:bigadic': 4,
 'tr:district:balkesir:burhaniye': 2,
 'tr:district:balkesir:dursunbey': 1,
 'tr:district:balkesir:edremit': 6,
 'tr:district:balkesir:erdek': 5,
 'tr:district:balkesir:gomec': 1,
 'tr:district:balkesir:gonen': 2,
 'tr:district:balkesir:havran': 2,
 'tr:district:balkesir:ivrindi': 5,
 'tr:district:balkesir:karesi': 7,
 'tr:district:balkesir:kepsut': 1,
 'tr:district:balkesir:manyas': 3,
 'tr:district:balkesir:marmara': 3,
 'tr:district:balkesir:savastepe': 2,
 'tr:district:balkesir:sndrg': 1,
 'tr:district:balkesir:susurluk': 3,
 'tr:district:bartn:amasra': 2,
 'tr:district:bartn:kurucasile': 2,
 'tr:district:bartn:merkez': 5,
 'tr:district:bartn:ulus': 3,
 'tr:district:batman:besiri': 2,
 'tr:district:batman:gercus': 2,
 'tr:district:batman:hasankeyf': 1,
 'tr:district:batman:kozluk': 1,
 'tr:district:batman:merkez': 5,
 'tr:district:batman:sason': 1,
 'tr:district:bayburt:aydntepe': 1,
 'tr:district:bayburt:demirozu': 2,
 'tr:district:bayburt:merkez': 2,
 'tr:district:bilecik:bozuyuk': 2,
 'tr:district:bilecik:golpazar': 1,
 'tr:district:bilecik:inhisar': 1,
 'tr:district:bilecik:merkez': 3,
 'tr:district:bilecik:osmaneli': 1,
 'tr:district:bilecik:pazaryeri': 1,
 'tr:district:bilecik:sogut': 1,
 'tr:district:bilecik:yenipazar': 1,
 'tr:district:bingol:adakl': 1,
 'tr:district:bingol:genc': 1,
 'tr:district:bingol:karlova': 1,
 'tr:district:bingol:kig': 1,
 'tr:district:bingol:merkez': 3,
 'tr:district:bingol:solhan': 1,
 'tr:district:bingol:yayladere': 1,
 'tr:district:bingol:yedisu': 1,
 'tr:district:bitlis:adilcevaz': 1,
 'tr:district:bitlis:ahlat': 1,
 'tr:district:bitlis:guroymak': 2,
 'tr:district:bitlis:hizan': 1,
 'tr:district:bitlis:merkez': 1,
 'tr:district:bitlis:mutki': 1,
 'tr:district:bitlis:tatvan': 1,
 'tr:district:bolu:dortdivan': 1,
 'tr:district:bolu:gerede': 1,
 'tr:district:bolu:goynuk': 1,
 'tr:district:bolu:kbrsck': 1,
 'tr:district:bolu:mengen': 2,
 'tr:district:bolu:merkez': 5,
 'tr:district:bolu:mudurnu': 2,
 'tr:district:bolu:seben': 1,
 'tr:district:bolu:yenicaga': 1,
 'tr:district:burdur:aglasun': 1,
 'tr:district:burdur:altnyayla': 1,
 'tr:district:burdur:bucak': 2,
 'tr:district:burdur:cavdr': 2,
 'tr:district:burdur:celtikci': 1,
 'tr:district:burdur:golhisar': 1,
 'tr:district:burdur:karamanl': 1,
 'tr:district:burdur:kemer': 1,
 'tr:district:burdur:merkez': 5,
 'tr:district:burdur:tefenni': 1,
 'tr:district:burdur:yesilova': 1,
 'tr:district:bursa:buyukorhan': 1,
 'tr:district:bursa:gemlik': 4,
 'tr:district:bursa:gursu': 1,
 'tr:district:bursa:harmanck': 1,
 'tr:district:bursa:inegol': 3,
 'tr:district:bursa:iznik': 3,
 'tr:district:bursa:karacabey': 2,
 'tr:district:bursa:keles': 1,
 'tr:district:bursa:kestel': 2,
 'tr:district:bursa:mudanya': 4,
 'tr:district:bursa:mustafakemalpasa': 7,
 'tr:district:bursa:nilufer': 7,
 'tr:district:bursa:orhaneli': 1,
 'tr:district:bursa:orhangazi': 7,
 'tr:district:bursa:osmangazi': 22,
 'tr:district:bursa:yenisehir': 1,
 'tr:district:bursa:yldrm': 7,
 'tr:district:canakkale:ayvack': 2,
 'tr:district:canakkale:bayramic': 2,
 'tr:district:canakkale:biga': 2,
 'tr:district:canakkale:bozcaada': 1,
 'tr:district:canakkale:can': 2,
 'tr:district:canakkale:eceabat': 1,
 'tr:district:canakkale:ezine': 2,
 'tr:district:canakkale:gelibolu': 3,
 'tr:district:canakkale:gokceada': 1,
 'tr:district:canakkale:lapseki': 3,
 'tr:district:canakkale:merkez': 4,
 'tr:district:canakkale:yenice': 2,
 'tr:district:cankr:atkaracalar': 2,
 'tr:district:cankr:bayramoren': 1,
 'tr:district:cankr:cerkes': 1,
 'tr:district:cankr:eldivan': 1,
 'tr:district:cankr:ilgaz': 1,
 'tr:district:cankr:korgun': 1,
 'tr:district:cankr:kursunlu': 1,
 'tr:district:cankr:kzlrmak': 1,
 'tr:district:cankr:merkez': 3,
 'tr:district:cankr:orta': 1,
 'tr:district:cankr:sabanozu': 1,
 'tr:district:cankr:yaprakl': 1,
 'tr:district:corum:alaca': 1,
 'tr:district:corum:bayat': 1,
 'tr:district:corum:bogazkale': 1,
 'tr:district:corum:dodurga': 1,
 'tr:district:corum:iskilip': 1,
 'tr:district:corum:karg': 1,
 'tr:district:corum:lacin': 1,
 'tr:district:corum:mecitozu': 1,
 'tr:district:corum:merkez': 5,
 'tr:district:corum:oguzlar': 1,
 'tr:district:corum:ortakoy': 1,
 'tr:district:corum:osmanck': 1,
 'tr:district:corum:sungurlu': 1,
 'tr:district:corum:ugurludag': 1,
 'tr:district:denizli:acpayam': 8,
 'tr:district:denizli:babadag': 1,
 'tr:district:denizli:baklan': 2,
 'tr:district:denizli:bekilli': 2,
 'tr:district:denizli:beyagac': 1,
 'tr:district:denizli:bozkurt': 2,
 'tr:district:denizli:buldan': 2,
 'tr:district:denizli:cal': 9,
 'tr:district:denizli:cameli': 1,
 'tr:district:denizli:cardak': 2,
 'tr:district:denizli:civril': 10,
 'tr:district:denizli:guney': 1,
 'tr:district:denizli:honaz': 2,
 'tr:district:denizli:kale': 2,
 'tr:district:denizli:merkezefendi': 6,
 'tr:district:denizli:pamukkale': 5,
 'tr:district:denizli:saraykoy': 5,
 'tr:district:denizli:serinhisar': 2,
 'tr:district:denizli:tavas': 11,
 'tr:district:diyarbakr:baglar': 3,
 'tr:district:diyarbakr:bismil': 3,
 'tr:district:diyarbakr:cermik': 1,
 'tr:district:diyarbakr:cnar': 1,
 'tr:district:diyarbakr:cungus': 1,
 'tr:district:diyarbakr:dicle': 1,
 'tr:district:diyarbakr:egil': 1,
 'tr:district:diyarbakr:ergani': 1,
 'tr:district:diyarbakr:hani': 1,
 'tr:district:diyarbakr:hazro': 1,
 'tr:district:diyarbakr:kayapnar': 2,
 'tr:district:diyarbakr:kocakoy': 1,
 'tr:district:diyarbakr:kulp': 1,
 'tr:district:diyarbakr:lice': 1,
 'tr:district:diyarbakr:silvan': 1,
 'tr:district:diyarbakr:sur': 4,
 'tr:district:diyarbakr:yenisehir': 3,
 'tr:district:duzce:akcakoca': 1,
 'tr:district:duzce:cilimli': 1,
 'tr:district:duzce:cumayeri': 1,
 'tr:district:duzce:golyaka': 1,
 'tr:district:duzce:gumusova': 1,
 'tr:district:duzce:kaynasl': 1,
 'tr:district:duzce:merkez': 7,
 'tr:district:duzce:yglca': 1,
 'tr:district:edirne:enez': 2,
 'tr:district:edirne:havsa': 2,
 'tr:district:edirne:ipsala': 3,
 'tr:district:edirne:kesan': 3,
 'tr:district:edirne:lalapasa': 2,
 'tr:district:edirne:meric': 4,
 'tr:district:edirne:merkez': 5,
 'tr:district:edirne:suloglu': 2,
 'tr:district:edirne:uzunkopru': 4,
 'tr:district:elazg:agn': 1,
 'tr:district:elazg:alacakaya': 1,
 'tr:district:elazg:arcak': 1,
 'tr:district:elazg:baskil': 1,
 'tr:district:elazg:karakocan': 1,
 'tr:district:elazg:keban': 1,
 'tr:district:elazg:kovanclar': 1,
 'tr:district:elazg:maden': 1,
 'tr:district:elazg:merkez': 12,
 'tr:district:elazg:palu': 2,
 'tr:district:elazg:sivrice': 1,
 'tr:district:erzincan:cayrl': 2,
 'tr:district:erzincan:ilic': 2,
 'tr:district:erzincan:kemah': 1,
 'tr:district:erzincan:kemaliye': 3,
 'tr:district:erzincan:merkez': 10,
 'tr:district:erzincan:otlukbeli': 2,
 'tr:district:erzincan:refahiye': 1,
 'tr:district:erzincan:tercan': 4,
 'tr:district:erzincan:uzumlu': 2,
 'tr:district:erzurum:askale': 2,
 'tr:district:erzurum:aziziye': 1,
 'tr:district:erzurum:cat': 2,
 'tr:district:erzurum:hns': 1,
 'tr:district:erzurum:horasan': 1,
 'tr:district:erzurum:ispir': 2,
 'tr:district:erzurum:karacoban': 1,
 'tr:district:erzurum:karayaz': 2,
 'tr:district:erzurum:koprukoy': 2,
 'tr:district:erzurum:narman': 2,
 'tr:district:erzurum:oltu': 1,
 'tr:district:erzurum:olur': 1,
 'tr:district:erzurum:palandoken': 4,
 'tr:district:erzurum:pasinler': 1,
 'tr:district:erzurum:pazaryolu': 1,
 'tr:district:erzurum:senkaya': 4,
 'tr:district:erzurum:tekman': 1,
 'tr:district:erzurum:tortum': 4,
 'tr:district:erzurum:uzundere': 1,
 'tr:district:erzurum:yakutiye': 7,
 'tr:district:eskisehir:alpu': 2,
 'tr:district:eskisehir:beylikova': 1,
 'tr:district:eskisehir:cifteler': 1,
 'tr:district:eskisehir:gunyuzu': 3,
 'tr:district:eskisehir:han': 1,
 'tr:district:eskisehir:inonu': 2,
 'tr:district:eskisehir:mahmudiye': 1,
 'tr:district:eskisehir:mihalcck': 3,
 'tr:district:eskisehir:mihalgazi': 1,
 'tr:district:eskisehir:odunpazar': 17,
 'tr:district:eskisehir:sarcakaya': 1,
 'tr:district:eskisehir:seyitgazi': 3,
 'tr:district:eskisehir:sivrihisar': 4,
 'tr:district:eskisehir:tepebas': 15,
 'tr:district:gaziantep:araban': 2,
 'tr:district:gaziantep:islahiye': 5,
 'tr:district:gaziantep:karkams': 1,
 'tr:district:gaziantep:nizip': 4,
 'tr:district:gaziantep:nurdag': 3,
 'tr:district:gaziantep:oguzeli': 3,
 'tr:district:gaziantep:sahinbey': 13,
 'tr:district:gaziantep:sehitkamil': 14,
 'tr:district:gaziantep:yavuzeli': 1,
 'tr:district:giresun:alucra': 1,
 'tr:district:giresun:bulancak': 2,
 'tr:district:giresun:camoluk': 1,
 'tr:district:giresun:canakc': 1,
 'tr:district:giresun:dereli': 1,
 'tr:district:giresun:dogankent': 1,
 'tr:district:giresun:espiye': 1,
 'tr:district:giresun:eynesil': 1,
 'tr:district:giresun:gorele': 2,
 'tr:district:giresun:guce': 1,
 'tr:district:giresun:kesap': 1,
 'tr:district:giresun:merkez': 4,
 'tr:district:giresun:piraziz': 1,
 'tr:district:giresun:sebinkarahisar': 1,
 'tr:district:giresun:tirebolu': 1,
 'tr:district:giresun:yagldere': 1,
 'tr:district:gumushane:kelkit': 1,
 'tr:district:gumushane:kose': 1,
 'tr:district:gumushane:kurtun': 2,
 'tr:district:gumushane:merkez': 4,
 'tr:district:gumushane:siran': 1,
 'tr:district:gumushane:torul': 1,
 'tr:district:hakkari:cukurca': 1,
 'tr:district:hakkari:derecik': 0,
 'tr:district:hakkari:merkez': 2,
 'tr:district:hakkari:semdinli': 1,
 'tr:district:hakkari:yuksekova': 3,
 'tr:district:hatay:altnozu': 4,
 'tr:district:hatay:antakya': 14,
 'tr:district:hatay:arsuz': 6,
 'tr:district:hatay:belen': 1,
 'tr:district:hatay:defne': 7,
 'tr:district:hatay:dortyol': 5,
 'tr:district:hatay:erzin': 1,
 'tr:district:hatay:hassa': 5,
 'tr:district:hatay:iskenderun': 9,
 'tr:district:hatay:krkhan': 2,
 'tr:district:hatay:kumlu': 1,
 'tr:district:hatay:payas': 1,
 'tr:district:hatay:reyhanl': 1,
 'tr:district:hatay:samandag': 11,
 'tr:district:hatay:yayladag': 5,
 'tr:district:igdr:aralk': 1,
 'tr:district:igdr:karakoyunlu': 1,
 'tr:district:igdr:merkez': 4,
 'tr:district:igdr:tuzluca': 1,
 'tr:district:isparta:aksu': 1,
 'tr:district:isparta:atabey': 1,
 'tr:district:isparta:egirdir': 2,
 'tr:district:isparta:gelendost': 1,
 'tr:district:isparta:gonen': 1,
 'tr:district:isparta:keciborlu': 2,
 'tr:district:isparta:merkez': 7,
 'tr:district:isparta:sarkikaraagac': 3,
 'tr:district:isparta:senirkent': 2,
 'tr:district:isparta:sutculer': 1,
 'tr:district:isparta:uluborlu': 1,
 'tr:district:isparta:yalvac': 2,
 'tr:district:isparta:yenisarbademli': 1,
 'tr:district:istanbul:adalar': 4,
 'tr:district:istanbul:arnavutkoy': 7,
 'tr:district:istanbul:atasehir': 9,
 'tr:district:istanbul:avclar': 4,
 'tr:district:istanbul:bagclar': 8,
 'tr:district:istanbul:bahcelievler': 9,
 'tr:district:istanbul:bakrkoy': 8,
 'tr:district:istanbul:basaksehir': 4,
 'tr:district:istanbul:bayrampasa': 3,
 'tr:district:istanbul:besiktas': 10,
 'tr:district:istanbul:beykoz': 8,
 'tr:district:istanbul:beylikduzu': 3,
 'tr:district:istanbul:beyoglu': 9,
 'tr:district:istanbul:buyukcekmece': 5,
 'tr:district:istanbul:catalca': 5,
 'tr:district:istanbul:cekmekoy': 4,
 'tr:district:istanbul:esenler': 4,
 'tr:district:istanbul:esenyurt': 6,
 'tr:district:istanbul:eyupsultan': 8,
 'tr:district:istanbul:fatih': 17,
 'tr:district:istanbul:gaziosmanpasa': 4,
 'tr:district:istanbul:gungoren': 4,
 'tr:district:istanbul:kadkoy': 17,
 'tr:district:istanbul:kagthane': 8,
 'tr:district:istanbul:kartal': 8,
 'tr:district:istanbul:kucukcekmece': 4,
 'tr:district:istanbul:maltepe': 9,
 'tr:district:istanbul:pendik': 9,
 'tr:district:istanbul:sancaktepe': 4,
 'tr:district:istanbul:saryer': 10,
 'tr:district:istanbul:sile': 2,
 'tr:district:istanbul:silivri': 4,
 'tr:district:istanbul:sisli': 15,
 'tr:district:istanbul:sultanbeyli': 4,
 'tr:district:istanbul:sultangazi': 3,
 'tr:district:istanbul:tuzla': 7,
 'tr:district:istanbul:umraniye': 10,
 'tr:district:istanbul:uskudar': 16,
 'tr:district:istanbul:zeytinburnu': 4,
 'tr:district:izmir:aliaga': 3,
 'tr:district:izmir:balcova': 1,
 'tr:district:izmir:bayndr': 4,
 'tr:district:izmir:bayrakl': 5,
 'tr:district:izmir:bergama': 6,
 'tr:district:izmir:beydag': 1,
 'tr:district:izmir:bornova': 8,
 'tr:district:izmir:buca': 5,
 'tr:district:izmir:cesme': 2,
 'tr:district:izmir:cigli': 5,
 'tr:district:izmir:dikili': 2,
 'tr:district:izmir:foca': 3,
 'tr:district:izmir:gaziemir': 3,
 'tr:district:izmir:guzelbahce': 1,
 'tr:district:izmir:karabaglar': 6,
 'tr:district:izmir:karaburun': 2,
 'tr:district:izmir:karsyaka': 7,
 'tr:district:izmir:kemalpasa': 6,
 'tr:district:izmir:kiraz': 1,
 'tr:district:izmir:knk': 1,
 'tr:district:izmir:konak': 12,
 'tr:district:izmir:menderes': 11,
 'tr:district:izmir:menemen': 8,
 'tr:district:izmir:narldere': 1,
 'tr:district:izmir:odemis': 10,
 'tr:district:izmir:seferihisar': 3,
 'tr:district:izmir:selcuk': 2,
 'tr:district:izmir:tire': 2,
 'tr:district:izmir:torbal': 6,
 'tr:district:izmir:urla': 1,
 'tr:district:kahramanmaras:afsin': 10,
 'tr:district:kahramanmaras:andrn': 4,
 'tr:district:kahramanmaras:caglayancerit': 3,
 'tr:district:kahramanmaras:dulkadiroglu': 6,
 'tr:district:kahramanmaras:ekinozu': 1,
 'tr:district:kahramanmaras:elbistan': 10,
 'tr:district:kahramanmaras:goksun': 8,
 'tr:district:kahramanmaras:nurhak': 4,
 'tr:district:kahramanmaras:onikisubat': 15,
 'tr:district:kahramanmaras:pazarck': 5,
 'tr:district:kahramanmaras:turkoglu': 5,
 'tr:district:karabuk:eflani': 1,
 'tr:district:karabuk:eskipazar': 1,
 'tr:district:karabuk:merkez': 5,
 'tr:district:karabuk:ovack': 1,
 'tr:district:karabuk:safranbolu': 2,
 'tr:district:karabuk:yenice': 1,
 'tr:district:karaman:ayranc': 1,
 'tr:district:karaman:basyayla': 1,
 'tr:district:karaman:ermenek': 3,
 'tr:district:karaman:kazmkarabekir': 1,
 'tr:district:karaman:merkez': 5,
 'tr:district:karaman:sarveliler': 2,
 'tr:district:kars:akyaka': 1,
 'tr:district:kars:arpacay': 1,
 'tr:district:kars:digor': 2,
 'tr:district:kars:kagzman': 1,
 'tr:district:kars:merkez': 1,
 'tr:district:kars:sarkams': 1,
 'tr:district:kars:selim': 1,
 'tr:district:kars:susuz': 1,
 'tr:district:kastamonu:abana': 1,
 'tr:district:kastamonu:agl': 1,
 'tr:district:kastamonu:arac': 3,
 'tr:district:kastamonu:azdavay': 1,
 'tr:district:kastamonu:bozkurt': 1,
 'tr:district:kastamonu:catalzeytin': 1,
 'tr:district:kastamonu:cide': 1,
 'tr:district:kastamonu:daday': 1,
 'tr:district:kastamonu:devrekani': 1,
 'tr:district:kastamonu:doganyurt': 1,
 'tr:district:kastamonu:hanonu': 1,
 'tr:district:kastamonu:ihsangazi': 1,
 'tr:district:kastamonu:inebolu': 1,
 'tr:district:kastamonu:kure': 1,
 'tr:district:kastamonu:merkez': 4,
 'tr:district:kastamonu:pnarbas': 1,
 'tr:district:kastamonu:senpazar': 1,
 'tr:district:kastamonu:seydiler': 1,
 'tr:district:kastamonu:taskopru': 1,
 'tr:district:kastamonu:tosya': 1,
 'tr:district:kayseri:akksla': 2,
 'tr:district:kayseri:bunyan': 1,
 'tr:district:kayseri:develi': 1,
 'tr:district:kayseri:felahiye': 1,
 'tr:district:kayseri:haclar': 1,
 'tr:district:kayseri:incesu': 2,
 'tr:district:kayseri:kocasinan': 8,
 'tr:district:kayseri:melikgazi': 10,
 'tr:district:kayseri:ozvatan': 1,
 'tr:district:kayseri:pnarbas': 2,
 'tr:district:kayseri:saroglan': 4,
 'tr:district:kayseri:sarz': 1,
 'tr:district:kayseri:talas': 3,
 'tr:district:kayseri:tomarza': 2,
 'tr:district:kayseri:yahyal': 1,
 'tr:district:kayseri:yesilhisar': 1,
 'tr:district:kilis:elbeyli': 1,
 'tr:district:kilis:merkez': 1,
 'tr:district:kilis:musabeyli': 1,
 'tr:district:kilis:polateli': 1,
 'tr:district:kocaeli:basiskele': 6,
 'tr:district:kocaeli:cayrova': 1,
 'tr:district:kocaeli:darca': 1,
 'tr:district:kocaeli:derince': 1,
 'tr:district:kocaeli:dilovas': 1,
 'tr:district:kocaeli:gebze': 1,
 'tr:district:kocaeli:golcuk': 2,
 'tr:district:kocaeli:izmit': 8,
 'tr:district:kocaeli:kandra': 1,
 'tr:district:kocaeli:karamursel': 1,
 'tr:district:kocaeli:kartepe': 9,
 'tr:district:kocaeli:korfez': 2,
 'tr:district:konya:ahrl': 2,
 'tr:district:konya:akoren': 1,
 'tr:district:konya:aksehir': 10,
 'tr:district:konya:altnekin': 1,
 'tr:district:konya:beysehir': 7,
 'tr:district:konya:bozkr': 6,
 'tr:district:konya:celtik': 1,
 'tr:district:konya:cihanbeyli': 9,
 'tr:district:konya:cumra': 7,
 'tr:district:konya:derbent': 1,
 'tr:district:konya:derebucak': 4,
 'tr:district:konya:doganhisar': 4,
 'tr:district:konya:emirgazi': 2,
 'tr:district:konya:eregli': 7,
 'tr:district:konya:guneysnr': 1,
 'tr:district:konya:hadim': 4,
 'tr:district:konya:halkapnar': 1,
 'tr:district:konya:huyuk': 3,
 'tr:district:konya:ilgn': 8,
 'tr:district:konya:kadnhan': 4,
 'tr:district:konya:karapnar': 4,
 'tr:district:konya:karatay': 4,
 'tr:district:konya:kulu': 7,
 'tr:district:konya:meram': 5,
 'tr:district:konya:sarayonu': 2,
 'tr:district:konya:selcuklu': 10,
 'tr:district:konya:seydisehir': 6,
 'tr:district:konya:taskent': 3,
 'tr:district:konya:tuzlukcu': 1,
 'tr:district:konya:yalhuyuk': 1,
 'tr:district:konya:yunak': 7,
 'tr:district:krkkale:bahsl': 1,
 'tr:district:krkkale:balseyh': 1,
 'tr:district:krkkale:celebi': 1,
 'tr:district:krkkale:delice': 2,
 'tr:district:krkkale:karakecili': 1,
 'tr:district:krkkale:keskin': 2,
 'tr:district:krkkale:merkez': 5,
 'tr:district:krkkale:sulakyurt': 1,
 'tr:district:krkkale:yahsihan': 2,
 'tr:district:krklareli:babaeski': 2,
 'tr:district:krklareli:demirkoy': 2,
 'tr:district:krklareli:kofcaz': 1,
 'tr:district:krklareli:luleburgaz': 4,
 'tr:district:krklareli:merkez': 3,
 'tr:district:krklareli:pehlivankoy': 2,
 'tr:district:krklareli:pnarhisar': 1,
 'tr:district:krklareli:vize': 1,
 'tr:district:krsehir:akcakent': 1,
 'tr:district:krsehir:akpnar': 1,
 'tr:district:krsehir:boztepe': 2,
 'tr:district:krsehir:cicekdag': 2,
 'tr:district:krsehir:kaman': 2,
 'tr:district:krsehir:merkez': 4,
 'tr:district:krsehir:mucur': 1,
 'tr:district:kutahya:altntas': 1,
 'tr:district:kutahya:aslanapa': 1,
 'tr:district:kutahya:cavdarhisar': 1,
 'tr:district:kutahya:domanic': 2,
 'tr:district:kutahya:dumlupnar': 1,
 'tr:district:kutahya:emet': 1,
 'tr:district:kutahya:gediz': 4,
 'tr:district:kutahya:hisarck': 1,
 'tr:district:kutahya:merkez': 7,
 'tr:district:kutahya:pazarlar': 1,
 'tr:district:kutahya:saphane': 1,
 'tr:district:kutahya:simav': 3,
 'tr:district:kutahya:tavsanl': 4,
 'tr:district:malatya:akcadag': 1,
 'tr:district:malatya:arapgir': 1,
 'tr:district:malatya:arguvan': 1,
 'tr:district:malatya:battalgazi': 10,
 'tr:district:malatya:darende': 7,
 'tr:district:malatya:dogansehir': 5,
 'tr:district:malatya:doganyol': 1,
 'tr:district:malatya:hekimhan': 4,
 'tr:district:malatya:kale': 1,
 'tr:district:malatya:kuluncak': 1,
 'tr:district:malatya:puturge': 1,
 'tr:district:malatya:yazhan': 1,
 'tr:district:malatya:yesilyurt': 12,
 'tr:district:manisa:ahmetli': 1,
 'tr:district:manisa:akhisar': 8,
 'tr:district:manisa:alasehir': 7,
 'tr:district:manisa:demirci': 1,
 'tr:district:manisa:golmarmara': 1,
 'tr:district:manisa:gordes': 3,
 'tr:district:manisa:koprubas': 2,
 'tr:district:manisa:krkagac': 5,
 'tr:district:manisa:kula': 2,
 'tr:district:manisa:salihli': 8,
 'tr:district:manisa:sargol': 1,
 'tr:district:manisa:saruhanl': 14,
 'tr:district:manisa:sehzadeler': 9,
 'tr:district:manisa:selendi': 1,
 'tr:district:manisa:soma': 5,
 'tr:district:manisa:turgutlu': 2,
 'tr:district:manisa:yunusemre': 6,
 'tr:district:mardin:artuklu': 5,
 'tr:district:mardin:dargecit': 1,
 'tr:district:mardin:derik': 1,
 'tr:district:mardin:kzltepe': 4,
 'tr:district:mardin:mazdag': 1,
 'tr:district:mardin:midyat': 7,
 'tr:district:mardin:nusaybin': 2,
 'tr:district:mardin:omerli': 1,
 'tr:district:mardin:savur': 2,
 'tr:district:mardin:yesilli': 1,
 'tr:district:mersin:akdeniz': 8,
 'tr:district:mersin:anamur': 5,
 'tr:district:mersin:aydnck': 1,
 'tr:district:mersin:bozyaz': 3,
 'tr:district:mersin:camlyayla': 2,
 'tr:district:mersin:erdemli': 8,
 'tr:district:mersin:gulnar': 5,
 'tr:district:mersin:mezitli': 4,
 'tr:district:mersin:mut': 1,
 'tr:district:mersin:silifke': 7,
 'tr:district:mersin:tarsus': 11,
 'tr:district:mersin:toroslar': 9,
 'tr:district:mersin:yenisehir': 6,
 'tr:district:mugla:bodrum': 12,
 'tr:district:mugla:dalaman': 1,
 'tr:district:mugla:datca': 1,
 'tr:district:mugla:fethiye': 7,
 'tr:district:mugla:kavakldere': 4,
 'tr:district:mugla:koycegiz': 3,
 'tr:district:mugla:marmaris': 6,
 'tr:district:mugla:mentese': 5,
 'tr:district:mugla:milas': 6,
 'tr:district:mugla:ortaca': 2,
 'tr:district:mugla:seydikemer': 6,
 'tr:district:mugla:ula': 3,
 'tr:district:mugla:yatagan': 6,
 'tr:district:mus:bulank': 4,
 'tr:district:mus:haskoy': 1,
 'tr:district:mus:korkut': 2,
 'tr:district:mus:malazgirt': 2,
 'tr:district:mus:merkez': 9,
 'tr:district:mus:varto': 3,
 'tr:district:nevsehir:acgol': 3,
 'tr:district:nevsehir:avanos': 4,
 'tr:district:nevsehir:derinkuyu': 3,
 'tr:district:nevsehir:gulsehir': 1,
 'tr:district:nevsehir:hacbektas': 1,
 'tr:district:nevsehir:kozakl': 1,
 'tr:district:nevsehir:merkez': 12,
 'tr:district:nevsehir:urgup': 3,
 'tr:district:nigde:altunhisar': 3,
 'tr:district:nigde:bor': 4,
 'tr:district:nigde:camard': 1,
 'tr:district:nigde:ciftlik': 4,
 'tr:district:nigde:merkez': 11,
 'tr:district:nigde:uluksla': 1,
 'tr:district:ordu:akkus': 2,
 'tr:district:ordu:altnordu': 3,
 'tr:district:ordu:aybast': 1,
 'tr:district:ordu:camas': 1,
 'tr:district:ordu:catalpnar': 1,
 'tr:district:ordu:caybas': 2,
 'tr:district:ordu:fatsa': 4,
 'tr:district:ordu:golkoy': 1,
 'tr:district:ordu:gulyal': 1,
 'tr:district:ordu:gurgentepe': 1,
 'tr:district:ordu:ikizce': 1,
 'tr:district:ordu:kabaduz': 1,
 'tr:district:ordu:kabatas': 2,
 'tr:district:ordu:korgan': 2,
 'tr:district:ordu:kumru': 1,
 'tr:district:ordu:mesudiye': 1,
 'tr:district:ordu:persembe': 2,
 'tr:district:ordu:ulubey': 1,
 'tr:district:ordu:unye': 3,
 'tr:district:osmaniye:bahce': 1,
 'tr:district:osmaniye:duzici': 5,
 'tr:district:osmaniye:hasanbeyli': 1,
 'tr:district:osmaniye:kadirli': 2,
 'tr:district:osmaniye:merkez': 5,
 'tr:district:osmaniye:sumbas': 2,
 'tr:district:osmaniye:toprakkale': 2,
 'tr:district:rize:ardesen': 3,
 'tr:district:rize:camlhemsin': 2,
 'tr:district:rize:cayeli': 5,
 'tr:district:rize:derepazar': 2,
 'tr:district:rize:fndkl': 2,
 'tr:district:rize:guneysu': 2,
 'tr:district:rize:hemsin': 2,
 'tr:district:rize:ikizdere': 2,
 'tr:district:rize:iyidere': 3,
 'tr:district:rize:kalkandere': 2,
 'tr:district:rize:merkez': 4,
 'tr:district:rize:pazar': 2,
 'tr:district:sakarya:adapazar': 2,
 'tr:district:sakarya:akyaz': 3,
 'tr:district:sakarya:arifiye': 2,
 'tr:district:sakarya:erenler': 1,
 'tr:district:sakarya:ferizli': 3,
 'tr:district:sakarya:geyve': 2,
 'tr:district:sakarya:hendek': 1,
 'tr:district:sakarya:karapurcek': 1,
 'tr:district:sakarya:karasu': 2,
 'tr:district:sakarya:kaynarca': 2,
 'tr:district:sakarya:kocaali': 1,
 'tr:district:sakarya:pamukova': 1,
 'tr:district:sakarya:sapanca': 1,
 'tr:district:sakarya:serdivan': 3,
 'tr:district:sakarya:sogutlu': 1,
 'tr:district:sakarya:tarakl': 1,
 'tr:district:samsun:19-mays': 3,
 'tr:district:samsun:alacam': 1,
 'tr:district:samsun:asarck': 1,
 'tr:district:samsun:atakum': 2,
 'tr:district:samsun:ayvack': 1,
 'tr:district:samsun:bafra': 3,
 'tr:district:samsun:canik': 1,
 'tr:district:samsun:carsamba': 5,
 'tr:district:samsun:havza': 3,
 'tr:district:samsun:ilkadm': 9,
 'tr:district:samsun:kavak': 1,
 'tr:district:samsun:ladik': 1,
 'tr:district:samsun:salpazar': 1,
 'tr:district:samsun:tekkekoy': 4,
 'tr:district:samsun:terme': 1,
 'tr:district:samsun:vezirkopru': 1,
 'tr:district:samsun:yakakent': 1,
 'tr:district:sanlurfa:akcakale': 1,
 'tr:district:sanlurfa:birecik': 2,
 'tr:district:sanlurfa:bozova': 1,
 'tr:district:sanlurfa:ceylanpnar': 1,
 'tr:district:sanlurfa:eyyubiye': 4,
 'tr:district:sanlurfa:halfeti': 3,
 'tr:district:sanlurfa:haliliye': 6,
 'tr:district:sanlurfa:harran': 1,
 'tr:district:sanlurfa:hilvan': 1,
 'tr:district:sanlurfa:karakopru': 3,
 'tr:district:sanlurfa:siverek': 3,
 'tr:district:sanlurfa:suruc': 2,
 'tr:district:sanlurfa:viransehir': 1,
 'tr:district:siirt:baykan': 2,
 'tr:district:siirt:eruh': 1,
 'tr:district:siirt:kurtalan': 2,
 'tr:district:siirt:merkez': 3,
 'tr:district:siirt:pervari': 1,
 'tr:district:siirt:sirvan': 1,
 'tr:district:siirt:tillo': 1,
 'tr:district:sinop:ayanck': 1,
 'tr:district:sinop:boyabat': 1,
 'tr:district:sinop:dikmen': 1,
 'tr:district:sinop:duragan': 1,
 'tr:district:sinop:erfelek': 1,
 'tr:district:sinop:gerze': 1,
 'tr:district:sinop:merkez': 1,
 'tr:district:sinop:sarayduzu': 1,
 'tr:district:sinop:turkeli': 1,
 'tr:district:sivas:aknclar': 1,
 'tr:district:sivas:altnyayla': 1,
 'tr:district:sivas:divrigi': 1,
 'tr:district:sivas:dogansar': 1,
 'tr:district:sivas:gemerek': 3,
 'tr:district:sivas:golova': 1,
 'tr:district:sivas:gurun': 1,
 'tr:district:sivas:hafik': 1,
 'tr:district:sivas:imranl': 1,
 'tr:district:sivas:kangal': 1,
 'tr:district:sivas:koyulhisar': 1,
 'tr:district:sivas:merkez': 10,
 'tr:district:sivas:sarksla': 2,
 'tr:district:sivas:susehri': 1,
 'tr:district:sivas:ulas': 1,
 'tr:district:sivas:yldzeli': 3,
 'tr:district:sivas:zara': 1,
 'tr:district:srnak:beytussebap': 1,
 'tr:district:srnak:cizre': 1,
 'tr:district:srnak:guclukonak': 2,
 'tr:district:srnak:idil': 1,
 'tr:district:srnak:merkez': 1,
 'tr:district:srnak:silopi': 2,
 'tr:district:srnak:uludere': 3,
 'tr:district:tekirdag:cerkezkoy': 2,
 'tr:district:tekirdag:corlu': 2,
 'tr:district:tekirdag:ergene': 4,
 'tr:district:tekirdag:hayrabolu': 2,
 'tr:district:tekirdag:kapakl': 2,
 'tr:district:tekirdag:malkara': 4,
 'tr:district:tekirdag:marmaraereglisi': 3,
 'tr:district:tekirdag:muratl': 1,
 'tr:district:tekirdag:saray': 2,
 'tr:district:tekirdag:sarkoy': 3,
 'tr:district:tekirdag:suleymanpasa': 8,
 'tr:district:tokat:almus': 5,
 'tr:district:tokat:artova': 1,
 'tr:district:tokat:basciftlik': 2,
 'tr:district:tokat:erbaa': 4,
 'tr:district:tokat:merkez': 8,
 'tr:district:tokat:niksar': 5,
 'tr:district:tokat:pazar': 2,
 'tr:district:tokat:resadiye': 6,
 'tr:district:tokat:sulusaray': 1,
 'tr:district:tokat:turhal': 2,
 'tr:district:tokat:yesilyurt': 1,
 'tr:district:tokat:zile': 1,
 'tr:district:trabzon:akcaabat': 4,
 'tr:district:trabzon:arakl': 2,
 'tr:district:trabzon:arsin': 4,
 'tr:district:trabzon:besikduzu': 3,
 'tr:district:trabzon:carsbas': 1,
 'tr:district:trabzon:caykara': 1,
 'tr:district:trabzon:dernekpazar': 1,
 'tr:district:trabzon:duzkoy': 2,
 'tr:district:trabzon:hayrat': 2,
 'tr:district:trabzon:koprubas': 1,
 'tr:district:trabzon:macka': 2,
 'tr:district:trabzon:of': 6,
 'tr:district:trabzon:ortahisar': 10,
 'tr:district:trabzon:salpazar': 1,
 'tr:district:trabzon:surmene': 2,
 'tr:district:trabzon:tonya': 2,
 'tr:district:trabzon:vakfkebir': 2,
 'tr:district:trabzon:yomra': 4,
 'tr:district:tunceli:cemisgezek': 1,
 'tr:district:tunceli:hozat': 1,
 'tr:district:tunceli:mazgirt': 1,
 'tr:district:tunceli:merkez': 1,
 'tr:district:tunceli:nazmiye': 1,
 'tr:district:tunceli:ovack': 1,
 'tr:district:tunceli:pertek': 1,
 'tr:district:tunceli:pulumur': 2,
 'tr:district:usak:banaz': 2,
 'tr:district:usak:esme': 2,
 'tr:district:usak:karahall': 1,
 'tr:district:usak:merkez': 6,
 'tr:district:usak:sivasl': 4,
 'tr:district:usak:ulubey': 1,
 'tr:district:van:bahcesaray': 1,
 'tr:district:van:baskale': 1,
 'tr:district:van:caldran': 1,
 'tr:district:van:catak': 1,
 'tr:district:van:edremit': 2,
 'tr:district:van:ercis': 3,
 'tr:district:van:gevas': 1,
 'tr:district:van:gurpnar': 1,
 'tr:district:van:ipekyolu': 7,
 'tr:district:van:muradiye': 2,
 'tr:district:van:ozalp': 3,
 'tr:district:van:saray': 1,
 'tr:district:van:tusba': 3,
 'tr:district:yalova:altnova': 5,
 'tr:district:yalova:armutlu': 1,
 'tr:district:yalova:ciftlikkoy': 1,
 'tr:district:yalova:cnarck': 4,
 'tr:district:yalova:merkez': 3,
 'tr:district:yalova:termal': 1,
 'tr:district:yozgat:akdagmadeni': 1,
 'tr:district:yozgat:aydnck': 1,
 'tr:district:yozgat:bogazlyan': 2,
 'tr:district:yozgat:candr': 1,
 'tr:district:yozgat:cayralan': 1,
 'tr:district:yozgat:cekerek': 1,
 'tr:district:yozgat:kadsehri': 1,
 'tr:district:yozgat:merkez': 2,
 'tr:district:yozgat:saraykent': 1,
 'tr:district:yozgat:sarkaya': 1,
 'tr:district:yozgat:sefaatli': 1,
 'tr:district:yozgat:sorgun': 4,
 'tr:district:yozgat:yenifakl': 1,
 'tr:district:yozgat:yerkoy': 1,
 'tr:district:zonguldak:alapl': 1,
 'tr:district:zonguldak:caycuma': 6,
 'tr:district:zonguldak:devrek': 3,
 'tr:district:zonguldak:eregli': 4,
 'tr:district:zonguldak:gokcebey': 2,
 'tr:district:zonguldak:kilimli': 1,
 'tr:district:zonguldak:kozlu': 2,
 'tr:district:zonguldak:merkez': 12,
}
wrong = [sid for sid, n in exp_counts.items() if have.get(sid, 0) != n]
check('per-district-counts-973', not wrong, str(wrong[:5]))
check('covered-970', sum(1 for sid in exp_counts if have.get(sid, 0) > 0) == 970)
print('ALL PASS' if not fails else f'{len(fails)} FAILURES')
sys.exit(1 if fails else 0)
