K = 'my:subdistrict:district:kedah'
D = 'my:district:kedah'
ADDS = [
 ('kota-setar','bandar-anak-bukit','Bandar Anak Bukit','bandar'),
 ('kota-setar','alor-merah','Alor Merah','bandar'),
 ('kota-setar','bukit-pinang','Bukit Pinang','bandar'),
 ('kota-setar','bandar-langgar','Bandar Langgar','bandar'),
 ('kota-setar','alor-janggus','Alor Janggus','pekan'),
 ('kota-setar','pekan-gunung','Pekan Gunung','pekan'),
 ('kubang-pasu','bandar-tunjang','Bandar Tunjang','bandar'),
 ('kubang-pasu','padang-sera','Padang Sera','bandar'),
 ('kubang-pasu','kuala-sanglang','Kuala Sanglang','pekan'),
 ('kubang-pasu','pekan-sanglang','Pekan Sanglang','pekan'),
 ('kubang-pasu','kerpan','Kerpan','pekan'),
 ('kubang-pasu','sintok','Sintok','pekan'),
 ('kubang-pasu','napoh','Napoh','pekan'),
 ('kubang-pasu','sungai-korok','Sungai Korok','pekan'),
 ('padang-terap','naka','Naka','pekan'),
 ('padang-terap','durian-burung','Durian Burung','pekan'),
 ('padang-terap','lubok-merbau','Lubok Merbau','pekan'),
 ('padang-terap','bukit-tembaga','Bukit Tembaga','pekan'),
 ('padang-terap','padang-sanai','Padang Sanai','pekan'),
 ('padang-terap','kampung-tanjung','Kampung Tanjung','pekan'),
 ('langkawi','bandar-kuah','Bandar Kuah','bandar'),
 ('langkawi','bandar-padang-mat-sirat','Bandar Padang Mat Sirat','bandar'),
 ('langkawi','padang-lalang','Padang Lalang','bandar'),
 ('langkawi','telok-datai','Telok Datai','pekan'),
 ('kuala-muda','teloi-kiri','Teloi Kiri','mukim'),
 ('kuala-muda','bandar-gurun','Bandar Gurun','bandar'),
 ('kuala-muda','sungai-lalang','Sungai Lalang','bandar'),
 ('kuala-muda','bandar-merbok','Bandar Merbok','bandar'),
 ('kuala-muda','bandar-semeling','Bandar Semeling','bandar'),
 ('kuala-muda','bandar-aman-jaya','Bandar Aman Jaya','bandar'),
 ('kuala-muda','bukit-selambau','Bukit Selambau','pekan'),
 ('kuala-muda','tanjung-dawai','Tanjung Dawai','pekan'),
 ('yan','bandar-yan','Bandar Yan','bandar'),
 ('yan','simpang-tiga-sungai-limau','Simpang Tiga Sungai Limau','pekan'),
 ('yan','sungai-limau','Sungai Limau','pekan'),
 ('yan','teroi','Teroi','pekan'),
 ('yan','pekan-singkir','Pekan Singkir','pekan'),
 ('sik','bandar-sik','Bandar Sik','bandar'),
 ('sik','batu-lima-sik','Batu Lima Sik','pekan'),
 ('sik','gulau','Gulau','pekan'),
 ('sik','gajah-puteh','Gajah Puteh','pekan'),
 ('sik','charok-padang','Charok Padang','pekan'),
 ('baling','bandar-kupang','Bandar Kupang','bandar'),
 ('baling','kampung-baru-kejai','Kampung Baru Kejai','pekan'),
 ('baling','pekan-pulai','Pekan Pulai','pekan'),
 ('baling','pekan-tawar','Pekan Tawar','pekan'),
 ('baling','parit-panjang','Parit Panjang','pekan'),
 ('baling','kampung-lalang','Kampung Lalang','pekan'),
 ('baling','malau','Malau','pekan'),
 ('kulim','pekan-junjong','Pekan Junjong','pekan'),
 ('kulim','pekan-karangan','Pekan Karangan','pekan'),
 ('kulim','labu-besar','Labu Besar','pekan'),
 ('kulim','pekan-mahang','Pekan Mahang','pekan'),
 ('kulim','merbau-pulas','Merbau Pulas','pekan'),
 ('kulim','sungai-karangan','Sungai Karangan','pekan'),
 ('kulim','sungai-kob','Sungai Kob','pekan'),
 ('kulim','pekan-padang-meha','Pekan Padang Meha','pekan'),
 ('bandar-baharu','bandar-serdang','Bandar Serdang','bandar'),
 ('bandar-baharu','lubuk-buntar','Lubuk Buntar','pekan'),
 ('bandar-baharu','selama','Selama','pekan'),
 ('bandar-baharu','sungai-kechil-ilir','Sungai Kechil Ilir','pekan'),
 ('bandar-baharu','pekan-relau','Pekan Relau','pekan'),
 ('pendang','bukit-raya','Bukit Raya','mukim'),
 ('pendang','bukit-jenun','Bukit Jenun','pekan'),
 ('pendang','kubur-panjang','Kubur Panjang','pekan'),
 ('pendang','tanah-merah','Tanah Merah','pekan'),
 ('pendang','tokai','Tokai','pekan'),
 ('pendang','kobah','Kobah','pekan'),
 ('pendang','kampung-baru','Kampung Baru','pekan'),
 ('pendang','sungai-tiang','Sungai Tiang','pekan'),
 ('pokok-sena','kebun-500','Kebun 500','pekan'),
]
RETYPES = {
 f'{K}:kubang-pasu:bandar-jitra': 'bandar',
 f'{K}:kuala-muda:bandar-sungai-petani': 'bandar',
 f'{K}:baling:bandar-baling': 'bandar',
 f'{K}:kulim:bandar-kulim': 'bandar',
 f'{K}:kuala-muda:tikam-batu': 'bandar',
}
DELETE_ROWS = [
 f'{K}:kota-setar:bandar-alor-setar',
 f'{K}:pendang:bandar-pendang',
 f'{K}:pokok-sena:pekan-pokok-sena',
 f'{K}:sik:pekan-sik',
]
REPOINTS = [
 ('07000', f'{K}:langkawi:kuah', f'{K}:langkawi:bandar-kuah'),
 ('07007', f'{K}:langkawi:kuah', f'{K}:langkawi:bandar-kuah'),
 ('07009', f'{K}:langkawi:kuah', f'{K}:langkawi:bandar-kuah'),
 ('07100', f'{K}:langkawi:kuah', f'{K}:langkawi:bandar-kuah'),
 ('06500', f'{K}:kota-setar:langgar', f'{K}:kota-setar:bandar-langgar'),
 ('06507', f'{K}:kota-setar:langgar', f'{K}:kota-setar:bandar-langgar'),
 ('08300', f'{K}:kuala-muda:gurun', f'{K}:kuala-muda:bandar-gurun'),
 ('08330', f'{K}:kuala-muda:gurun', f'{K}:kuala-muda:bandar-gurun'),
 ('08800', f'{K}:kuala-muda:gurun', f'{K}:kuala-muda:bandar-gurun'),
 ('08400', f'{K}:kuala-muda:merbok', f'{K}:kuala-muda:bandar-merbok'),
 ('08407', f'{K}:kuala-muda:merbok', f'{K}:kuala-muda:bandar-merbok'),
 ('08409', f'{K}:kuala-muda:merbok', f'{K}:kuala-muda:bandar-merbok'),
 ('06900', f'{K}:yan:yan', f'{K}:yan:bandar-yan'),
 ('06910', f'{K}:yan:yan', f'{K}:yan:bandar-yan'),
 ('08200', f'{K}:sik:sik', f'{K}:sik:bandar-sik'),
 ('08210', f'{K}:sik:sik', f'{K}:sik:bandar-sik'),
 ('08340', f'{K}:sik:sik', f'{K}:sik:bandar-sik'),
 ('09200', f'{K}:baling:kupang', f'{K}:baling:bandar-kupang'),
 ('09700', f'{K}:kulim:karangan', f'{K}:kulim:pekan-karangan'),
 ('09800', f'{K}:bandar-baharu:serdang', f'{K}:bandar-baharu:bandar-serdang'),
 ('09810', f'{K}:bandar-baharu:serdang', f'{K}:bandar-baharu:bandar-serdang'),

 ('05000', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05050', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05100', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05150', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05200', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05250', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05300', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05350', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05400', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05450', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05460', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05500', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05502', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05503', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05504', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05505', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05506', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05508', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05512', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05514', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05516', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05517', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05518', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05520', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05532', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05534', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05536', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05538', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05550', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05551', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05552', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05556', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05558', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05560', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05564', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05576', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05578', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05580', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05582', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05586', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05590', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05592', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05594', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05600', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05604', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05610', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05612', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05614', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05620', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05621', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05622', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05626', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05628', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05630', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05632', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05644', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05660', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05661', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05664', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05670', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05672', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05673', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05674', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05675', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05676', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05680', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05690', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05696', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05700', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05710', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05720', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('05990', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('06250', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('06350', f'{K}:pokok-sena:pekan-pokok-sena', f'{K}:pokok-sena:pokok-sena'),
 ('06400', f'{K}:pokok-sena:pekan-pokok-sena', f'{K}:pokok-sena:pokok-sena'),
 ('06509', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('06550', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('06570', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('06660', f'{K}:kota-setar:bandar-alor-setar', f'{K}:kota-setar:alor-setar'),
 ('06700', f'{K}:pendang:bandar-pendang', f'{K}:pendang:pendang'),
 ('06707', f'{K}:pendang:bandar-pendang', f'{K}:pendang:pendang'),
 ('06709', f'{K}:pendang:bandar-pendang', f'{K}:pendang:pendang'),
 ('06710', f'{K}:pendang:bandar-pendang', f'{K}:pendang:pendang'),
 ('06720', f'{K}:pendang:bandar-pendang', f'{K}:pendang:pendang'),
 ('06750', f'{K}:pendang:bandar-pendang', f'{K}:pendang:pendang'),
 ('06760', f'{K}:pendang:bandar-pendang', f'{K}:pendang:pendang'),
]
ADD_LINKS = [
 # covering-mukim secondaries on the moved main town codes
 ('07000', f'{K}:langkawi:kuah', 'served_by', 'false'),
 ('06500', f'{K}:kota-setar:langgar', 'served_by', 'false'),
 ('08300', f'{K}:kuala-muda:gurun', 'served_by', 'false'),
 ('08400', f'{K}:kuala-muda:merbok', 'served_by', 'false'),
 ('06900', f'{K}:yan:yan', 'served_by', 'false'),
 ('08200', f'{K}:sik:sik', 'served_by', 'false'),
 ('09200', f'{K}:baling:kupang', 'served_by', 'false'),
 ('09700', f'{K}:kulim:karangan', 'served_by', 'false'),
 ('09800', f'{K}:bandar-baharu:serdang', 'served_by', 'false'),
 # shared-code town secondaries (v-swiss / addressed-sighting evidence)
 ('05250', f'{K}:kota-setar:alor-merah', 'served_by', 'false'),
 ('06200', f'{K}:kota-setar:bukit-pinang', 'served_by', 'false'),
 ('06250', f'{K}:kota-setar:alor-janggus', 'served_by', 'false'),
 ('06550', f'{K}:kota-setar:bandar-anak-bukit', 'served_by', 'false'),
 ('06650', f'{K}:pendang:tokai', 'served_by', 'false'),
 ('06660', f'{K}:pendang:tokai', 'served_by', 'false'),
 ('06300', f'{K}:padang-terap:bukit-tembaga', 'served_by', 'false'),
 ('06300', f'{K}:padang-terap:padang-sanai', 'served_by', 'false'),
 ('06300', f'{K}:padang-terap:durian-burung', 'served_by', 'false'),
 ('06350', f'{K}:padang-terap:naka', 'served_by', 'false'),
 ('06400', f'{K}:padang-terap:naka', 'served_by', 'false'),
 ('06400', f'{K}:pokok-sena:kebun-500', 'served_by', 'false'),
 ('06700', f'{K}:pendang:tanah-merah', 'served_by', 'false'),
 ('06750', f'{K}:pendang:sungai-tiang', 'served_by', 'false'),
 ('06800', f'{K}:pendang:kobah', 'served_by', 'false'),
 ('06100', f'{K}:kubang-pasu:padang-sera', 'served_by', 'false'),
 ('06100', f'{K}:kubang-pasu:sintok', 'served_by', 'false'),
 ('06100', f'{K}:kubang-pasu:pekan-sanglang', 'served_by', 'false'),
 ('06150', f'{K}:kubang-pasu:kuala-sanglang', 'served_by', 'false'),
 ('06150', f'{K}:kubang-pasu:kerpan', 'served_by', 'false'),
 ('06150', f'{K}:kubang-pasu:sungai-korok', 'served_by', 'false'),
 ('06000', f'{K}:kubang-pasu:bandar-tunjang', 'served_by', 'false'),
 ('06000', f'{K}:kubang-pasu:napoh', 'served_by', 'false'),
 ('08000', f'{K}:kuala-muda:sungai-lalang', 'served_by', 'false'),
 ('08000', f'{K}:kuala-muda:bandar-aman-jaya', 'served_by', 'false'),
 ('08010', f'{K}:kuala-muda:bukit-selambau', 'served_by', 'false'),
 ('08600', f'{K}:kuala-muda:tikam-batu', 'served_by', 'false'),
 ('09300', f'{K}:kulim:merbau-pulas', 'served_by', 'false'),
 ('09200', f'{K}:baling:parit-panjang', 'served_by', 'false'),
 ('09700', f'{K}:kulim:pekan-mahang', 'served_by', 'false'),
 ('09700', f'{K}:kulim:sungai-kob', 'served_by', 'false'),
 ('09800', f'{K}:bandar-baharu:lubuk-buntar', 'served_by', 'false'),
 ('08800', f'{K}:yan:guar-cempedak', 'served_by', 'false'),
 ('08100', f'{K}:kuala-muda:bandar-semeling', 'served_by', 'false'),
 ('08110', f'{K}:yan:pekan-singkir', 'served_by', 'false'),
 ('08400', f'{K}:yan:pekan-singkir', 'served_by', 'false'),
 ('08200', f'{K}:sik:charok-padang', 'served_by', 'false'),
 ('08210', f'{K}:sik:gulau', 'served_by', 'false'),
 ('08400', f'{K}:kuala-muda:tanjung-dawai', 'served_by', 'false'),
 ('08110', f'{K}:kuala-muda:tanjung-dawai', 'served_by', 'false'),
 ('06710', f'{K}:padang-terap:lubok-merbau', 'served_by', 'false'),
 ('14390', f'{K}:bandar-baharu:sungai-kechil-ilir', 'served_by', 'false'),
 ('09310', f'{K}:baling:pekan-tawar', 'served_by', 'false'),
]
DROP_LINKS = [

 ('05621', f'{K}:kota-setar:alor-setar', 'false'),
 ('05700', f'{K}:kota-setar:alor-setar', 'false'),
 ('05710', f'{K}:kota-setar:alor-setar', 'false'),
 ('05720', f'{K}:kota-setar:alor-setar', 'false'),
 ('05990', f'{K}:kota-setar:alor-setar', 'false'),
 ('06400', f'{K}:pokok-sena:pokok-sena', 'false'),
 ('06700', f'{K}:pendang:pendang', 'false'),
 ('06707', f'{K}:pendang:pendang', 'false'),
 ('06709', f'{K}:pendang:pendang', 'false'),
]
