K = 'my:subdistrict:district:negeri-sembilan'
D = 'my:district:negeri-sembilan'
ADDS = [
 ('jelebu','bandar-kuala-klawang','Bandar Kuala Klawang','bandar'),
 ('jelebu','pekan-kuala-klawang','Pekan Kuala Klawang','pekan'),
 ('jelebu','pekan-pertang','Pekan Pertang','pekan'),
 ('jelebu','titi','Titi','pekan'),
 ('jelebu','petaling','Petaling','pekan'),
 ('jelebu','sungai-muntoh','Sungai Muntoh','pekan'),
 ('kuala-pilah','pekan-johol','Pekan Johol','pekan'),
 ('kuala-pilah','pekan-parit-tinggi','Pekan Parit Tinggi','pekan'),
 ('kuala-pilah','pekan-juasseh','Pekan Juasseh','pekan'),
 ('kuala-pilah','dangi','Dangi','pekan'),
 ('kuala-pilah','gunung-pasir','Gunung Pasir','pekan'),
 ('kuala-pilah','senaling','Senaling','pekan'),
 ('kuala-pilah','bukit-gelugor','Bukit Gelugor','pekan'),
 ('kuala-pilah','melang','Melang','pekan'),
 ('kuala-pilah','air-mawang','Air Mawang','pekan'),
 ('kuala-pilah','dangi-baru','Dangi Baru','pekan'),
 ('port-dickson','bandar-port-dickson','Bandar Port Dickson','bandar'),
 ('port-dickson','pekan-port-dickson','Pekan Port Dickson','pekan'),
 ('port-dickson','teluk-kemang','Teluk Kemang','bandar'),
 ('port-dickson','pekan-teluk-kemang','Pekan Teluk Kemang','pekan'),
 ('port-dickson','pekan-pasir-panjang','Pekan Pasir Panjang','pekan'),
 ('port-dickson','pengkalan-kempas','Pengkalan Kempas','pekan'),
 ('port-dickson','chuah','Chuah','pekan'),
 ('port-dickson','pekan-linggi','Pekan Linggi','pekan'),
 ('port-dickson','bukit-pelanduk','Bukit Pelanduk','pekan'),
 ('port-dickson','air-kuning','Air Kuning','pekan'),
 ('port-dickson','sungai-menyala','Sungai Menyala','pekan'),
 ('port-dickson','bagan-pinang','Bagan Pinang','pekan'),
 ('port-dickson','tanah-merah-utara','Tanah Merah Utara','pekan'),
 ('port-dickson','tanah-merah-selatan','Tanah Merah Selatan','pekan'),
 ('port-dickson','jemima','Jemima','pekan'),
 ('rembau','pekan-chengkau','Pekan Chengkau','pekan'),
 ('rembau','pekan-pedas','Pekan Pedas','pekan'),
 ('rembau','pekan-chembong','Pekan Chembong','pekan'),
 ('rembau','pekan-rembau','Pekan Rembau','pekan'),
 ('rembau','kampong-batu','Kampong Batu','pekan'),
 ('rembau','lubok-china','Lubok China','pekan'),
 ('rembau','seri-kota','Seri Kota','pekan'),
 ('rembau','seri-kendong','Seri Kendong','pekan'),
 ('rembau','merbau-sembilan','Merbau Sembilan','pekan'),
 ('seremban','bandar-seremban-utama','Bandar Seremban Utama','bandar'),
 ('seremban','bandar-mantin-utama','Bandar Mantin Utama','bandar'),
 ('seremban','bandar-baru-kota-sri-mas','Bandar Baru Kota Sri Mas','bandar'),
 ('seremban','bandar-nilai-utama','Bandar Nilai Utama','bandar'),
 ('seremban','bandar-sri-sendayan','Bandar Sri Sendayan','bandar'),
 ('seremban','pekan-labu','Pekan Labu','pekan'),
 ('seremban','pekan-lenggeng','Pekan Lenggeng','pekan'),
 ('seremban','pekan-rantau','Pekan Rantau','pekan'),
 ('seremban','pekan-setul','Pekan Setul','pekan'),
 ('seremban','broga','Broga','pekan'),
 ('seremban','ulu-beranang','Ulu Beranang','pekan'),
 ('seremban','mambau','Mambau','pekan'),
 ('seremban','pajam','Pajam','pekan'),
 ('seremban','tiroi','Tiroi','pekan'),
 ('seremban','pancor','Pancor','pekan'),
 ('seremban','taman-seremban','Taman Seremban','pekan'),
 ('seremban','rahang-baru','Rahang Baru','pekan'),
 ('seremban','paroi','Paroi','pekan'),
 ('seremban','bukit-kepayang','Bukit Kepayang','pekan'),
 ('seremban','dusun-setia','Dusun Setia','pekan'),
 ('seremban','sungai-gadut','Sungai Gadut','pekan'),
 ('seremban','bukti','Bukti','pekan'),
 ('seremban','sikamat','Sikamat','pekan'),
 ('seremban','shah-bandar','Shah Bandar','pekan'),
 ('seremban','ulu-temiang','Ulu Temiang','pekan'),
 ('seremban','paroi-jaya','Paroi Jaya','pekan'),
 ('seremban','rasah-jaya','Rasah Jaya','pekan'),
 ('seremban','seremban-jaya','Seremban Jaya','pekan'),
 ('tampin','bandar-gemas','Bandar Gemas','bandar'),
 ('tampin','pekan-tampin-tengah','Pekan Tampin Tengah','pekan'),
 ('tampin','pekan-air-kuning','Pekan Air Kuning','pekan'),
 ('tampin','pekan-repah','Pekan Repah','pekan'),
 ('tampin','air-kuning-selatan','Air Kuning Selatan','pekan'),
 ('tampin','batang-melaka','Batang Melaka','pekan'),
 ('tampin','gemencheh-bahru','Gemencheh Bahru','pekan'),
 ('tampin','pasir-besar','Pasir Besar','pekan'),
 ('tampin','repah-jaya','Repah Jaya','pekan'),
 ('tampin','repah-permai','Repah Permai','pekan'),
 ('jempol','pekan-bahau','Pekan Bahau','pekan'),
 ('jempol','pekan-rompin','Pekan Rompin','pekan'),
 ('jempol','kuala-jelai','Kuala Jelai','pekan'),
 ('jempol','ladang-geddes','Ladang Geddes','pekan'),
 ('jempol','mahsan','Mahsan','pekan'),
 ('jempol','serting-tengah','Serting Tengah','pekan'),
 ('jempol','serting','Serting','bandar'),
]
RETYPES = {
 f'{K}:rembau:chengkau': 'mukim',
 f'{K}:seremban:bandar-seremban': 'bandar',
 f'{K}:jempol:bandar-seri-jempol': 'bandar',
}
DELETE_ROWS = []
DELETE_ROW = None
REPOINTS = [
 ('71600', f'{K}:jelebu:kuala-klawang', f'{K}:jelebu:bandar-kuala-klawang'),
 ('71609', f'{K}:jelebu:kuala-klawang', f'{K}:jelebu:bandar-kuala-klawang'),
 ('71650', f'{K}:jelebu:kuala-klawang', f'{K}:jelebu:bandar-kuala-klawang'),
 ('71659', f'{K}:jelebu:kuala-klawang', f'{K}:jelebu:bandar-kuala-klawang'),
 ('73100', f'{K}:kuala-pilah:johol', f'{K}:kuala-pilah:pekan-johol'),
 ('73109', f'{K}:kuala-pilah:johol', f'{K}:kuala-pilah:pekan-johol'),
 ('71000', f'{K}:port-dickson:port-dickson', f'{K}:port-dickson:bandar-port-dickson'),
 ('71007', f'{K}:port-dickson:port-dickson', f'{K}:port-dickson:bandar-port-dickson'),
 ('71009', f'{K}:port-dickson:port-dickson', f'{K}:port-dickson:bandar-port-dickson'),
 ('71010', f'{K}:port-dickson:port-dickson', f'{K}:port-dickson:bandar-port-dickson'),
 ('71960', f'{K}:port-dickson:port-dickson', f'{K}:port-dickson:bandar-port-dickson'),
 ('71999', f'{K}:port-dickson:port-dickson', f'{K}:port-dickson:bandar-port-dickson'),
 ('71150', f'{K}:port-dickson:linggi', f'{K}:port-dickson:pekan-linggi'),
 ('71159', f'{K}:port-dickson:linggi', f'{K}:port-dickson:pekan-linggi'),
 ('71900', f'{K}:seremban:labu', f'{K}:seremban:pekan-labu'),
 ('71907', f'{K}:seremban:labu', f'{K}:seremban:pekan-labu'),
 ('71909', f'{K}:seremban:labu', f'{K}:seremban:pekan-labu'),
 ('71100', f'{K}:seremban:rantau', f'{K}:seremban:pekan-rantau'),
 ('71109', f'{K}:seremban:rantau', f'{K}:seremban:pekan-rantau'),
 ('71200', f'{K}:seremban:rantau', f'{K}:seremban:pekan-rantau'),
 ('71209', f'{K}:seremban:rantau', f'{K}:seremban:pekan-rantau'),
 ('73400', f'{K}:tampin:gemas', f'{K}:tampin:bandar-gemas'),
 ('73409', f'{K}:tampin:gemas', f'{K}:tampin:bandar-gemas'),
 ('73410', f'{K}:tampin:gemas', f'{K}:tampin:bandar-gemas'),
 ('73420', f'{K}:tampin:gemas', f'{K}:tampin:bandar-gemas'),
 ('73480', f'{K}:tampin:gemas', f'{K}:tampin:bandar-gemas'),
 ('73500', f'{K}:jempol:rompin', f'{K}:jempol:pekan-rompin'),
 ('73507', f'{K}:jempol:rompin', f'{K}:jempol:pekan-rompin'),
 ('73509', f'{K}:jempol:rompin', f'{K}:jempol:pekan-rompin'),
]
ADD_LINKS = [
 # covering-mukim secondaries on the moved main town codes
 ('71600', f'{K}:jelebu:kuala-klawang', 'served_by', 'false'),
 ('73100', f'{K}:kuala-pilah:johol', 'served_by', 'false'),
 ('71000', f'{K}:port-dickson:port-dickson', 'served_by', 'false'),
 ('71150', f'{K}:port-dickson:linggi', 'served_by', 'false'),
 ('71900', f'{K}:seremban:labu', 'served_by', 'false'),
 ('71100', f'{K}:seremban:rantau', 'served_by', 'false'),
 ('73400', f'{K}:tampin:gemas', 'served_by', 'false'),
 ('73500', f'{K}:jempol:rompin', 'served_by', 'false'),
 # shared-code town secondaries (postcode-dataset area evidence)
 ('71650', f'{K}:jelebu:titi', 'served_by', 'false'),
 ('71659', f'{K}:jelebu:titi', 'served_by', 'false'),
 ('71650', f'{K}:jelebu:sungai-muntoh', 'served_by', 'false'),
 ('71600', f'{K}:jelebu:petaling', 'served_by', 'false'),
 ('73100', f'{K}:kuala-pilah:dangi', 'served_by', 'false'),
 ('73100', f'{K}:kuala-pilah:air-mawang', 'served_by', 'false'),
 ('72000', f'{K}:kuala-pilah:senaling', 'served_by', 'false'),
 ('72000', f'{K}:kuala-pilah:melang', 'served_by', 'false'),
 ('72000', f'{K}:kuala-pilah:pekan-parit-tinggi', 'served_by', 'false'),
 ('72000', f'{K}:kuala-pilah:pekan-juasseh', 'served_by', 'false'),
 ('72500', f'{K}:kuala-pilah:pekan-juasseh', 'served_by', 'false'),
 ('71550', f'{K}:kuala-pilah:gunung-pasir', 'served_by', 'false'),
 ('72200', f'{K}:kuala-pilah:bukit-gelugor', 'served_by', 'false'),
 ('71050', f'{K}:port-dickson:teluk-kemang', 'served_by', 'false'),
 ('71050', f'{K}:port-dickson:sungai-menyala', 'served_by', 'false'),
 ('71150', f'{K}:port-dickson:pengkalan-kempas', 'served_by', 'false'),
 ('71960', f'{K}:port-dickson:chuah', 'served_by', 'false'),
 ('71000', f'{K}:port-dickson:bagan-pinang', 'served_by', 'false'),
 ('71100', f'{K}:port-dickson:jemima', 'served_by', 'false'),
 ('71250', f'{K}:port-dickson:pekan-pasir-panjang', 'served_by', 'false'),
 ('71400', f'{K}:rembau:pekan-pedas', 'served_by', 'false'),
 ('71409', f'{K}:rembau:pekan-pedas', 'served_by', 'false'),
 ('71300', f'{K}:rembau:pekan-chembong', 'served_by', 'false'),
 ('71400', f'{K}:rembau:pekan-chembong', 'served_by', 'false'),
 ('71300', f'{K}:rembau:pekan-chengkau', 'served_by', 'false'),
 ('71350', f'{K}:rembau:pekan-chengkau', 'served_by', 'false'),
 ('71150', f'{K}:rembau:lubok-china', 'served_by', 'false'),
 ('71350', f'{K}:rembau:seri-kendong', 'served_by', 'false'),
 ('71400', f'{K}:rembau:merbau-sembilan', 'served_by', 'false'),
 ('71800', f'{K}:seremban:bandar-baru-kota-sri-mas', 'served_by', 'false'),
 ('71800', f'{K}:seremban:bandar-nilai-utama', 'served_by', 'false'),
 ('71950', f'{K}:seremban:bandar-sri-sendayan', 'served_by', 'false'),
 ('71750', f'{K}:seremban:pekan-lenggeng', 'served_by', 'false'),
 ('71700', f'{K}:seremban:pekan-setul', 'served_by', 'false'),
 ('71750', f'{K}:seremban:broga', 'served_by', 'false'),
 ('71750', f'{K}:seremban:ulu-beranang', 'served_by', 'false'),
 ('70300', f'{K}:seremban:mambau', 'served_by', 'false'),
 ('71700', f'{K}:seremban:pajam', 'served_by', 'false'),
 ('71900', f'{K}:seremban:tiroi', 'served_by', 'false'),
 ('70400', f'{K}:seremban:paroi', 'served_by', 'false'),
 ('70200', f'{K}:seremban:bukit-kepayang', 'served_by', 'false'),
 ('70100', f'{K}:seremban:dusun-setia', 'served_by', 'false'),
 ('71450', f'{K}:seremban:sungai-gadut', 'served_by', 'false'),
 ('70400', f'{K}:seremban:bukti', 'served_by', 'false'),
 ('70400', f'{K}:seremban:sikamat', 'served_by', 'false'),
 ('70400', f'{K}:seremban:shah-bandar', 'served_by', 'false'),
 ('70200', f'{K}:seremban:ulu-temiang', 'served_by', 'false'),
 ('70400', f'{K}:seremban:paroi-jaya', 'served_by', 'false'),
 ('70300', f'{K}:seremban:rasah-jaya', 'served_by', 'false'),
 ('70450', f'{K}:seremban:seremban-jaya', 'served_by', 'false'),
 ('73000', f'{K}:tampin:pekan-tampin-tengah', 'served_by', 'false'),
 ('73200', f'{K}:tampin:pekan-air-kuning', 'served_by', 'false'),
 ('73000', f'{K}:tampin:pekan-repah', 'served_by', 'false'),
 ('73300', f'{K}:tampin:batang-melaka', 'served_by', 'false'),
 ('73200', f'{K}:tampin:gemencheh-bahru', 'served_by', 'false'),
 ('73400', f'{K}:tampin:pasir-besar', 'served_by', 'false'),
 ('72100', f'{K}:jempol:kuala-jelai', 'served_by', 'false'),
 ('72120', f'{K}:jempol:ladang-geddes', 'served_by', 'false'),
 ('72100', f'{K}:jempol:mahsan', 'served_by', 'false'),
 ('72200', f'{K}:jempol:serting-tengah', 'served_by', 'false'),
 ('72120', f'{K}:jempol:serting', 'served_by', 'false'),
]
DROP_LINKS = []
