K = 'my:subdistrict:district:perak'
D = 'my:district:perak'
ADDS = [
 ('batang-padang','bandar-bidor','Bandar Bidor','bandar'),
 ('batang-padang','bandar-chenderiang','Bandar Chenderiang','bandar'),
 ('batang-padang','bandar-sungkai','Bandar Sungkai','bandar'),
 ('batang-padang','ayer-kuning','Ayer Kuning','pekan'),
 ('batang-padang','banir','Banir','pekan'),
 ('batang-padang','bikam','Bikam','pekan'),
 ('batang-padang','sungai-lesong','Sungai Lesong','pekan'),
 ('batang-padang','temoh-station','Temoh Station','pekan'),
 ('manjung','bandar-lumut','Bandar Lumut','bandar'),
 ('manjung','pekan-beruas','Pekan Beruas','pekan'),
 ('manjung','pekan-pengkalan-baharu','Pekan Pengkalan Baharu','pekan'),
 ('manjung','pekan-sitiawan','Pekan Sitiawan','pekan'),
 ('manjung','damar-laut','Damar Laut','pekan'),
 ('manjung','kampong-baharu','Kampong Baharu','pekan'),
 ('manjung','kampong-koh','Kampong Koh','pekan'),
 ('manjung','kampong-sitiawan','Kampong Sitiawan','pekan'),
 ('manjung','pasir-bogak','Pasir Bogak','pekan'),
 ('manjung','gurney','Gurney','pekan'),
 ('manjung','segari','Segari','pekan'),
 ('manjung','sungai-pinang-kechil','Sungai Pinang Kechil','pekan'),
 ('kinta','tronoh','Tronoh','mukim'),
 ('kinta','bandar-tronoh','Bandar Tronoh','bandar'),
 ('kinta','bandar-sungai-raya','Bandar Sungai Raya','bandar'),
 ('kinta','jelapang','Jelapang','bandar'),
 ('kinta','menglembu','Menglembu','bandar'),
 ('kinta','papan','Papan','bandar'),
 ('kinta','seputeh','Seputeh','bandar'),
 ('kinta','kanthan','Kanthan','pekan'),
 ('kinta','simpang-pulai','Simpang Pulai','pekan'),
 ('kinta','pekan-tanjong-tualang','Pekan Tanjong Tualang','pekan'),
 ('kerian','bandar-bagan-serai','Bandar Bagan Serai','bandar'),
 ('kerian','bandar-kuala-kurau','Bandar Kuala Kurau','bandar'),
 ('kerian','bandar-parit-buntar','Bandar Parit Buntar','bandar'),
 ('kerian','bukit-merah','Bukit Merah','pekan'),
 ('kerian','jalan-baru','Jalan Baru','pekan'),
 ('kerian','sungai-gedong','Sungai Gedong','pekan'),
 ('kerian','pekan-tanjong-piandang','Pekan Tanjong Piandang','pekan'),
 ('kuala-kangsar','bandar-sungai-siput','Bandar Sungai Siput','bandar'),
 ('kuala-kangsar','pekan-lubok-merbau','Pekan Lubok Merbau','pekan'),
 ('kuala-kangsar','gunong-pondok','Gunong Pondok','pekan'),
 ('kuala-kangsar','jerlun','Jerlun','pekan'),
 ('kuala-kangsar','karai','Karai','pekan'),
 ('kuala-kangsar','kati','Kati','pekan'),
 ('kuala-kangsar','salak','Salak','pekan'),
 ('larut-matang','bandar-kamunting','Bandar Kamunting','bandar'),
 ('larut-matang','pekan-batu-kurau','Pekan Batu Kurau','pekan'),
 ('larut-matang','pekan-simpang','Pekan Simpang','pekan'),
 ('larut-matang','pekan-terung','Pekan Terung','pekan'),
 ('larut-matang','pondok-tanjong','Pondok Tanjong','pekan'),
 ('hilir-perak','batak-rabit','Batak Rabit','pekan'),
 ('hilir-perak','degong','Degong','pekan'),
 ('hulu-perak','temelong','Temelong','mukim'),
 ('hulu-perak','temengor','Temengor','mukim'),
 ('hulu-perak','bandar-gerik','Bandar Gerik','bandar'),
 ('hulu-perak','bandar-pengkalan-hulu','Bandar Pengkalan Hulu','bandar'),
 ('hulu-perak','lawin','Lawin','bandar'),
 ('hulu-perak','bandar-lenggong','Bandar Lenggong','bandar'),
 ('selama','bandar-selama','Bandar Selama','bandar'),
 ('selama','sungai-bayur','Sungai Bayur','pekan'),
 ('perak-tengah','bota-kanan','Bota Kanan','pekan'),
 ('perak-tengah','kampong-buloh-akar','Kampong Buloh Akar','pekan'),
 ('perak-tengah','pekan-kota-setia','Pekan Kota Setia','pekan'),
 ('perak-tengah','tanjong-belanja','Tanjong Belanja','pekan'),
 ('kampar','bandar-kampar','Bandar Kampar','bandar'),
 ('kampar','kota-baharu','Kota Baharu','pekan'),
 ('muallim','proton','Proton','bandar'),
 ('muallim','pekan-slim','Pekan Slim','pekan'),
 ('bagan-datuk','pekan-bagan-datuk','Pekan Bagan Datuk','pekan'),
 ('bagan-datuk','pekan-hutan-melintang','Pekan Hutan Melintang','pekan'),
 ('bagan-datuk','pekan-sungai-sumun','Pekan Sungai Sumun','pekan'),
 ('bagan-datuk','batu-dua-puloh','Batu Dua Puloh','pekan'),
 ('bagan-datuk','jendarata','Jendarata','pekan'),
 ('bagan-datuk','kampong-sungai-haji-mohamed','Kampong Sungai Haji Mohamed','pekan'),
 ('bagan-datuk','simpang-empat','Simpang Empat','pekan'),
 ('bagan-datuk','simpang-tiga','Simpang Tiga','pekan'),
]
RETYPES = {
 f'{K}:kerian:simpang-lima': 'pekan',
 f'{K}:larut-matang:changkat-jering': 'pekan',
 f'{K}:selama:rantau-panjang': 'pekan',
}
DELETE_ROWS = []
DELETE_ROW = None
REPOINTS = [
 ('35500', f'{K}:batang-padang:bidor', f'{K}:batang-padang:bandar-bidor'),
 ('35300', f'{K}:batang-padang:chenderiang', f'{K}:batang-padang:bandar-chenderiang'),
 ('35600', f'{K}:batang-padang:sungkai', f'{K}:batang-padang:bandar-sungkai'),
 ('32100', f'{K}:manjung:lumut', f'{K}:manjung:bandar-lumut'),
 ('32200', f'{K}:manjung:lumut', f'{K}:manjung:bandar-lumut'),
 ('32700', f'{K}:manjung:beruas', f'{K}:manjung:pekan-beruas'),
 ('32000', f'{K}:manjung:sitiawan', f'{K}:manjung:pekan-sitiawan'),
 ('32010', f'{K}:manjung:sitiawan', f'{K}:manjung:pekan-sitiawan'),
 ('32020', f'{K}:manjung:sitiawan', f'{K}:manjung:pekan-sitiawan'),
 ('32050', f'{K}:manjung:sitiawan', f'{K}:manjung:pekan-sitiawan'),
 ('31800', f'{K}:kinta:tanjong-tualang', f'{K}:kinta:pekan-tanjong-tualang'),
 ('34300', f'{K}:kerian:bagan-serai', f'{K}:kerian:bandar-bagan-serai'),
 ('34310', f'{K}:kerian:bagan-serai', f'{K}:kerian:bandar-bagan-serai'),
 ('34350', f'{K}:kerian:kuala-kurau', f'{K}:kerian:bandar-kuala-kurau'),
 ('34200', f'{K}:kerian:parit-buntar', f'{K}:kerian:bandar-parit-buntar'),
 ('34250', f'{K}:kerian:tanjong-piandang', f'{K}:kerian:pekan-tanjong-piandang'),
 ('31050', f'{K}:kuala-kangsar:sungai-siput', f'{K}:kuala-kangsar:bandar-sungai-siput'),
 ('31100', f'{K}:kuala-kangsar:sungai-siput', f'{K}:kuala-kangsar:bandar-sungai-siput'),
 ('31120', f'{K}:kuala-kangsar:sungai-siput', f'{K}:kuala-kangsar:bandar-sungai-siput'),
 ('34600', f'{K}:larut-matang:kamunting', f'{K}:larut-matang:bandar-kamunting'),
 ('34500', f'{K}:larut-matang:batu-kurau', f'{K}:larut-matang:pekan-batu-kurau'),
 ('34510', f'{K}:larut-matang:batu-kurau', f'{K}:larut-matang:pekan-batu-kurau'),
 ('34520', f'{K}:larut-matang:batu-kurau', f'{K}:larut-matang:pekan-batu-kurau'),
 ('34700', f'{K}:larut-matang:simpang', f'{K}:larut-matang:pekan-simpang'),
 ('34800', f'{K}:larut-matang:trong', f'{K}:larut-matang:pekan-terung'),
 ('33300', f'{K}:hulu-perak:gerik', f'{K}:hulu-perak:bandar-gerik'),
 ('33310', f'{K}:hulu-perak:gerik', f'{K}:hulu-perak:bandar-gerik'),
 ('33320', f'{K}:hulu-perak:gerik', f'{K}:hulu-perak:bandar-gerik'),
 ('33100', f'{K}:hulu-perak:pengkalan-hulu', f'{K}:hulu-perak:bandar-pengkalan-hulu'),
 ('33400', f'{K}:hulu-perak:lenggong', f'{K}:hulu-perak:bandar-lenggong'),
 ('33410', f'{K}:hulu-perak:lenggong', f'{K}:hulu-perak:bandar-lenggong'),
 ('33420', f'{K}:hulu-perak:lenggong', f'{K}:hulu-perak:bandar-lenggong'),
 ('34100', f'{K}:selama:selama', f'{K}:selama:bandar-selama'),
 ('34120', f'{K}:selama:selama', f'{K}:selama:bandar-selama'),
 ('34130', f'{K}:selama:selama', f'{K}:selama:bandar-selama'),
 ('31900', f'{K}:kampar:kampar', f'{K}:kampar:bandar-kampar'),
 ('31907', f'{K}:kampar:kampar', f'{K}:kampar:bandar-kampar'),
 ('31909', f'{K}:kampar:kampar', f'{K}:kampar:bandar-kampar'),
 ('31910', f'{K}:kampar:kampar', f'{K}:kampar:bandar-kampar'),
 ('31920', f'{K}:kampar:kampar', f'{K}:kampar:bandar-kampar'),
 ('31950', f'{K}:kampar:kampar', f'{K}:kampar:bandar-kampar'),
 ('36100', f'{K}:bagan-datuk:bagan-datuk', f'{K}:bagan-datuk:pekan-bagan-datuk'),
 ('36400', f'{K}:bagan-datuk:hutan-melintang', f'{K}:bagan-datuk:pekan-hutan-melintang'),
 ('36300', f'{K}:bagan-datuk:sungai-sumun', f'{K}:bagan-datuk:pekan-sungai-sumun'),
 ('36307', f'{K}:bagan-datuk:sungai-sumun', f'{K}:bagan-datuk:pekan-sungai-sumun'),
 ('36309', f'{K}:bagan-datuk:sungai-sumun', f'{K}:bagan-datuk:pekan-sungai-sumun'),
]
ADD_LINKS = [
 # covering-mukim secondaries on the moved main town codes
 ('35500', f'{K}:batang-padang:bidor', 'served_by', 'false'),
 ('35300', f'{K}:batang-padang:chenderiang', 'served_by', 'false'),
 ('35600', f'{K}:batang-padang:sungkai', 'served_by', 'false'),
 ('32100', f'{K}:manjung:lumut', 'served_by', 'false'),
 ('32700', f'{K}:manjung:beruas', 'served_by', 'false'),
 ('32000', f'{K}:manjung:sitiawan', 'served_by', 'false'),
 ('31800', f'{K}:kinta:tanjong-tualang', 'served_by', 'false'),
 ('34300', f'{K}:kerian:bagan-serai', 'served_by', 'false'),
 ('34350', f'{K}:kerian:kuala-kurau', 'served_by', 'false'),
 ('34200', f'{K}:kerian:parit-buntar', 'served_by', 'false'),
 ('34250', f'{K}:kerian:tanjong-piandang', 'served_by', 'false'),
 ('31050', f'{K}:kuala-kangsar:sungai-siput', 'served_by', 'false'),
 ('34600', f'{K}:larut-matang:kamunting', 'served_by', 'false'),
 ('34500', f'{K}:larut-matang:batu-kurau', 'served_by', 'false'),
 ('34700', f'{K}:larut-matang:simpang', 'served_by', 'false'),
 ('33300', f'{K}:hulu-perak:gerik', 'served_by', 'false'),
 ('33100', f'{K}:hulu-perak:pengkalan-hulu', 'served_by', 'false'),
 ('33400', f'{K}:hulu-perak:lenggong', 'served_by', 'false'),
 ('34100', f'{K}:selama:selama', 'served_by', 'false'),
 ('31900', f'{K}:kampar:kampar', 'served_by', 'false'),
 ('36100', f'{K}:bagan-datuk:bagan-datuk', 'served_by', 'false'),
 ('36400', f'{K}:bagan-datuk:hutan-melintang', 'served_by', 'false'),
 ('36300', f'{K}:bagan-datuk:sungai-sumun', 'served_by', 'false'),
 # gazetted town takes the primary from the common-spelling locality
 ('34800', f'{K}:larut-matang:trong', 'served_by', 'false'),
 # shared-code town secondaries (postcode-dataset area evidence)
 ('31900', f'{K}:batang-padang:ayer-kuning', 'served_by', 'false'),
 ('35400', f'{K}:batang-padang:banir', 'served_by', 'false'),
 ('35600', f'{K}:batang-padang:bikam', 'served_by', 'false'),
 ('35350', f'{K}:batang-padang:temoh-station', 'served_by', 'false'),
 ('32200', f'{K}:manjung:damar-laut', 'served_by', 'false'),
 ('32200', f'{K}:manjung:segari', 'served_by', 'false'),
 ('32000', f'{K}:manjung:kampong-koh', 'served_by', 'false'),
 ('32000', f'{K}:manjung:kampong-sitiawan', 'served_by', 'false'),
 ('32000', f'{K}:manjung:gurney', 'served_by', 'false'),
 ('32300', f'{K}:manjung:pasir-bogak', 'served_by', 'false'),
 ('32300', f'{K}:manjung:sungai-pinang-kechil', 'served_by', 'false'),
 ('34400', f'{K}:kerian:bukit-merah', 'served_by', 'false'),
 ('34300', f'{K}:kerian:sungai-gedong', 'served_by', 'false'),
 ('33000', f'{K}:kuala-kangsar:jerlun', 'served_by', 'false'),
 ('33600', f'{K}:kuala-kangsar:karai', 'served_by', 'false'),
 ('33020', f'{K}:kuala-kangsar:kati', 'served_by', 'false'),
 ('31100', f'{K}:kuala-kangsar:salak', 'served_by', 'false'),
 ('36000', f'{K}:hilir-perak:batak-rabit', 'served_by', 'false'),
 ('36700', f'{K}:hilir-perak:degong', 'served_by', 'false'),
 ('33300', f'{K}:hulu-perak:lawin', 'served_by', 'false'),
 ('32600', f'{K}:perak-tengah:bota-kanan', 'served_by', 'false'),
 ('32800', f'{K}:perak-tengah:kampong-buloh-akar', 'served_by', 'false'),
 ('32800', f'{K}:perak-tengah:tanjong-belanja', 'served_by', 'false'),
 ('35950', f'{K}:muallim:proton', 'served_by', 'false'),
 ('36400', f'{K}:bagan-datuk:jendarata', 'served_by', 'false'),
 ('36400', f'{K}:bagan-datuk:simpang-empat', 'served_by', 'false'),
 ('36400', f'{K}:bagan-datuk:simpang-tiga', 'served_by', 'false'),
 ('35800', f'{K}:muallim:pekan-slim', 'served_by', 'false'),
 ('36810', f'{K}:perak-tengah:pekan-kota-setia', 'served_by', 'false'),
 ('33010', f'{K}:kuala-kangsar:pekan-lubok-merbau', 'served_by', 'false'),
 ('31600', f'{K}:kampar:kota-baharu', 'served_by', 'false'),
 ('31610', f'{K}:kampar:kota-baharu', 'served_by', 'false'),
]
DROP_LINKS = []
