K = 'my:subdistrict:district:selangor'
D = 'my:district:selangor'
ADDS = [
 # Klang (UPI 01): 2 mukims + 4 bandars + 6 pekans
 ('klang','bandar-klang','Bandar Klang','bandar'),
 ('klang','bandar-sultan-sulaiman','Bandar Sultan Sulaiman','bandar'),
 ('klang','bandar-shah-alam','Bandar Shah Alam','bandar'),
 ('klang','pekan-bukit-kemuning','Pekan Bukit Kemuning','pekan'),
 ('klang','pekan-kapar','Pekan Kapar','pekan'),
 ('klang','pekan-telok-menegun','Pekan Telok Menegun','pekan'),
 ('klang','pekan-batu-empat','Pekan Batu Empat','pekan'),
 ('klang','pekan-pandamaran','Pekan Pandamaran','pekan'),
 # Kuala Langat (UPI 02)
 ('kuala-langat','bandar-sijangkang','Bandar Sijangkang','bandar'),
 ('kuala-langat','bandar-telok-panglima-garang','Bandar Telok Panglima Garang','bandar'),
 ('kuala-langat','pekan-batu','Pekan Batu','pekan'),
 ('kuala-langat','pekan-bukit-changgang','Pekan Bukit Changgang','pekan'),
 ('kuala-langat','pekan-chodoi','Pekan Chodoi','pekan'),
 ('kuala-langat','pekan-jenjarom','Pekan Jenjarom','pekan'),
 ('kuala-langat','pekan-kancung','Pekan Kancung','pekan'),
 ('kuala-langat','pekan-kancung-darat','Pekan Kancung Darat','pekan'),
 ('kuala-langat','pekan-kelanang-batu-enam','Pekan Kelanang Batu Enam','pekan'),
 ('kuala-langat','pekan-morib','Pekan Morib','pekan'),
 ('kuala-langat','pekan-permatang-pasir','Pekan Permatang Pasir','pekan'),
 ('kuala-langat','pekan-sijangkang','Pekan Sijangkang','pekan'),
 ('kuala-langat','pekan-simpang-morib','Pekan Simpang Morib','pekan'),
 ('kuala-langat','pekan-sungai-manggis','Pekan Sungai Manggis','pekan'),
 ('kuala-langat','pekan-sungai-raba','Pekan Sungai Raba','pekan'),
 ('kuala-langat','pekan-tanjong-duabelas','Pekan Tanjong Duabelas','pekan'),
 ('kuala-langat','pekan-telok-datok','Pekan Telok Datok','pekan'),
 ('kuala-langat','pekan-telok','Pekan Telok','pekan'),
 ('kuala-langat','pekan-tongkah','Pekan Tongkah','pekan'),
 # Kuala Selangor (UPI 04; mukim code 02 genuinely skipped)
 ('kuala-selangor','bandar-kuala-selangor','Bandar Kuala Selangor','bandar'),
 ('kuala-selangor','bandar-tanjong-karang','Bandar Tanjong Karang','bandar'),
 ('kuala-selangor','pekan-asam-jawa','Pekan Asam Jawa','pekan'),
 ('kuala-selangor','pekan-jeram','Pekan Jeram','pekan'),
 ('kuala-selangor','pekan-kampong-kuantan','Pekan Kampong Kuantan','pekan'),
 ('kuala-selangor','pekan-kuala-sungai-buloh','Pekan Kuala Sungai Buloh','pekan'),
 ('kuala-selangor','pekan-pasir-penambang','Pekan Pasir Penambang','pekan'),
 ('kuala-selangor','pekan-simpang-tiga','Pekan Simpang Tiga','pekan'),
 ('kuala-selangor','pekan-tanjong-karang','Pekan Tanjong Karang','pekan'),
 ('kuala-selangor','pekan-bukit-belimbing','Pekan Bukit Belimbing','pekan'),
 ('kuala-selangor','pekan-bukit-talang','Pekan Bukit Talang','pekan'),
 ('kuala-selangor','pekan-kampong-baru-hulu-tiram-buruk','Pekan Kampong Baru Hulu Tiram Buruk','pekan'),
 ('kuala-selangor','pekan-parit-mahang','Pekan Parit Mahang','pekan'),
 ('kuala-selangor','pekan-simpang-tiga-ijok','Pekan Simpang Tiga Ijok','pekan'),
 ('kuala-selangor','pekan-sungai-sembilang','Pekan Sungai Sembilang','pekan'),
 ('kuala-selangor','pekan-taman-pkns','Pekan Taman PKNS','pekan'),
 ('kuala-selangor','pekan-tambak-jawa','Pekan Tambak Jawa','pekan'),
 ('kuala-selangor','pekan-bestari-jaya','Pekan Bestari Jaya','pekan'),
 # Sabak Bernam (UPI 05; no bandars gazetted)
 ('sabak-bernam','pekan-bagan-terap','Pekan Bagan Terap','pekan'),
 ('sabak-bernam','pekan-parit-enam','Pekan Parit Enam','pekan'),
 ('sabak-bernam','pekan-parit-sembilan','Pekan Parit Sembilan','pekan'),
 ('sabak-bernam','pekan-simpang-lima','Pekan Simpang Lima','pekan'),
 ('sabak-bernam','pekan-sabak','Pekan Sabak','pekan'),
 ('sabak-bernam','pekan-sungai-air-tawar','Pekan Sungai Air Tawar','pekan'),
 ('sabak-bernam','pekan-sungai-sepintas','Pekan Sungai Sepintas','pekan'),
 ('sabak-bernam','pekan-bagan-nakhoda-omar','Pekan Bagan Nakhoda Omar','pekan'),
 ('sabak-bernam','pekan-parit-baru','Pekan Parit Baru','pekan'),
 ('sabak-bernam','pekan-pasir-panjang','Pekan Pasir Panjang','pekan'),
 ('sabak-bernam','pekan-sekinchan-site','Pekan Sekinchan Site','pekan'),
 ('sabak-bernam','pekan-sungai-haji-dorani','Pekan Sungai Haji Dorani','pekan'),
 ('sabak-bernam','pekan-sungai-nibong','Pekan Sungai Nibong','pekan'),
 # Hulu Langat (UPI 06; pekan codes 70/72/74 genuinely absent)
 ('hulu-langat','bandar-cheras','Bandar Cheras','bandar'),
 ('hulu-langat','bandar-hulu-langat','Bandar Hulu Langat','bandar'),
 ('hulu-langat','bandar-kajang','Bandar Kajang','bandar'),
 ('hulu-langat','bandar-semenyih','Bandar Semenyih','bandar'),
 ('hulu-langat','bandar-ampang','Bandar Ampang','bandar'),
 ('hulu-langat','bandar-country-height','Bandar Country Height','bandar'),
 ('hulu-langat','bandar-batu-9-cheras','Bandar Batu 9 Cheras','bandar'),
 ('hulu-langat','bandar-batu-18-semenyih','Bandar Batu 18 Semenyih','bandar'),
 ('hulu-langat','bandar-batu-26-beranang','Bandar Batu 26 Beranang','bandar'),
 ('hulu-langat','pekan-beranang','Pekan Beranang','pekan'),
 ('hulu-langat','pekan-kachau','Pekan Kachau','pekan'),
 ('hulu-langat','pekan-tarun','Pekan Tarun','pekan'),
 ('hulu-langat','pekan-bangi-lama','Pekan Bangi Lama','pekan'),
 ('hulu-langat','pekan-batu-18-hulu-langat','Pekan Batu 18 Hulu Langat','pekan'),
 ('hulu-langat','pekan-batu-23-sungai-lalang','Pekan Batu 23 Sungai Lalang','pekan'),
 ('hulu-langat','pekan-batu-26-beranang','Pekan Batu 26 Beranang','pekan'),
 ('hulu-langat','pekan-bukit-sungai-raya','Pekan Bukit Sungai Raya','pekan'),
 ('hulu-langat','pekan-cheras','Pekan Cheras','pekan'),
 ('hulu-langat','pekan-desa-raya','Pekan Desa Raya','pekan'),
 ('hulu-langat','pekan-dusun-tua-hulu-langat','Pekan Dusun Tua Hulu Langat','pekan'),
 ('hulu-langat','pekan-kajang','Pekan Kajang','pekan'),
 ('hulu-langat','pekan-kampung-pasir-batu-14-semenyih','Pekan Kampung Pasir Batu 14 Semenyih','pekan'),
 ('hulu-langat','pekan-kampung-sungai-tangkas','Pekan Kampung Sungai Tangkas','pekan'),
 ('hulu-langat','pekan-rumah-murah-sungai-lui','Pekan Rumah Murah Sungai Lui','pekan'),
 ('hulu-langat','pekan-semenyih','Pekan Semenyih','pekan'),
 ('hulu-langat','pekan-simpang-balak','Pekan Simpang Balak','pekan'),
 ('hulu-langat','pekan-sri-nanding','Pekan Sri Nanding','pekan'),
 ('hulu-langat','pekan-sungai-kembong-beranang','Pekan Sungai Kembong Beranang','pekan'),
 ('hulu-langat','pekan-sungai-lui','Pekan Sungai Lui','pekan'),
 ('hulu-langat','pekan-sungai-makau','Pekan Sungai Makau','pekan'),
 # Hulu Selangor (UPI 07)
 ('hulu-selangor','bandar-hulu-yam','Bandar Hulu Yam','bandar'),
 ('hulu-selangor','bandar-hulu-yam-baharu','Bandar Hulu Yam Baharu','bandar'),
 ('hulu-selangor','bandar-kalumpang','Bandar Kalumpang','bandar'),
 ('hulu-selangor','bandar-rasa','Bandar Rasa','bandar'),
 ('hulu-selangor','bandar-serendah','Bandar Serendah','bandar'),
 ('hulu-selangor','bandar-batang-kali','Bandar Batang Kali','bandar'),
 ('hulu-selangor','bandar-hulu-bernam-i','Bandar Hulu Bernam I','bandar'),
 ('hulu-selangor','bandar-hulu-bernam-ii','Bandar Hulu Bernam II','bandar'),
 ('hulu-selangor','bandar-sungai-chik','Bandar Sungai Chik','bandar'),
 ('hulu-selangor','pekan-kerling','Pekan Kerling','pekan'),
 ('hulu-selangor','pekan-peretak','Pekan Peretak','pekan'),
 ('hulu-selangor','pekan-simpang-sungai-choh','Pekan Simpang Sungai Choh','pekan'),
 # Petaling (UPI 08)
 ('petaling','bandar-damansara','Bandar Damansara','bandar'),
 ('petaling','bandar-glenmarie','Bandar Glenmarie','bandar'),
 ('petaling','bandar-petaling-jaya-selatan','Bandar Petaling Jaya Selatan','bandar'),
 ('petaling','bandar-sri-damansara','Bandar Sri Damansara','bandar'),
 ('petaling','bandar-sunway','Bandar Sunway','bandar'),
 ('petaling','pekan-batu-tiga','Pekan Batu Tiga','pekan'),
 ('petaling','pekan-merbau-sempak','Pekan Merbau Sempak','pekan'),
 ('petaling','pekan-sungai-penchala','Pekan Sungai Penchala','pekan'),
 ('petaling','pekan-cempaka','Pekan Cempaka','pekan'),
 ('petaling','pekan-country-height','Pekan Country Height','pekan'),
 ('petaling','pekan-desa-puchong','Pekan Desa Puchong','pekan'),
 ('petaling','pekan-hicom','Pekan Hicom','pekan'),
 ('petaling','pekan-kayu-ara','Pekan Kayu Ara','pekan'),
 ('petaling','pekan-kinrara','Pekan Kinrara','pekan'),
 ('petaling','pekan-baru-hicom','Pekan Baru Hicom','pekan'),
 ('petaling','pekan-baru-subang','Pekan Baru Subang','pekan'),
 ('petaling','pekan-baru-sungai-besi','Pekan Baru Sungai Besi','pekan'),
 ('petaling','pekan-baru-sungai-buloh','Pekan Baru Sungai Buloh','pekan'),
 ('petaling','pekan-penaga','Pekan Penaga','pekan'),
 ('petaling','pekan-puchong-jaya','Pekan Puchong Jaya','pekan'),
 ('petaling','pekan-puchong-perdana','Pekan Puchong Perdana','pekan'),
 ('petaling','pekan-subang','Pekan Subang','pekan'),
 ('petaling','pekan-subang-jaya','Pekan Subang Jaya','pekan'),
 # Gombak (UPI 09)
 ('gombak','bandar-rawang','Bandar Rawang','bandar'),
 ('gombak','bandar-hulu-klang','Bandar Hulu Klang','bandar'),
 ('gombak','bandar-kepong','Bandar Kepong','bandar'),
 ('gombak','bandar-sungai-buloh','Bandar Sungai Buloh','bandar'),
 ('gombak','bandar-sungai-pusu','Bandar Sungai Pusu','bandar'),
 ('gombak','pekan-batu','Pekan Batu','pekan'),
 ('gombak','pekan-kuang','Pekan Kuang','pekan'),
 ('gombak','pekan-mimaland','Pekan Mimaland','pekan'),
 ('gombak','pekan-pengkalan-kundang','Pekan Pengkalan Kundang','pekan'),
 ('gombak','pekan-sungai-buloh','Pekan Sungai Buloh','pekan'),
 ('gombak','pekan-templer','Pekan Templer','pekan'),
 # Sepang (UPI 10; pekan code 73 genuinely absent)
 ('sepang','bandar-sepang','Bandar Sepang','bandar'),
 ('sepang','bandar-baru-bangi','Bandar Baru Bangi','bandar'),
 ('sepang','bandar-lapangan-terbang-antarabangsa-sepang','Bandar Lapangan Terbang Antarabangsa Sepang','bandar'),
 ('sepang','bandar-sungai-merab','Bandar Sungai Merab','bandar'),
 ('sepang','pekan-dengkil','Pekan Dengkil','pekan'),
 ('sepang','pekan-salak','Pekan Salak','pekan'),
 ('sepang','pekan-batu-1-sepang','Pekan Batu 1 Sepang','pekan'),
 ('sepang','pekan-bukit-bisa','Pekan Bukit Bisa','pekan'),
 ('sepang','pekan-bukit-prang','Pekan Bukit Prang','pekan'),
 ("sepang","pekan-dato-bakar-baginda","Pekan Dato' Bakar Baginda",'pekan'),
 ('sepang','pekan-baru-salak-tinggi','Pekan Baru Salak Tinggi','pekan'),
 ('sepang','pekan-sungai-merab','Pekan Sungai Merab','pekan'),
 ('sepang','pekan-tanjung-mas','Pekan Tanjung Mas','pekan'),
 ('sepang','pekan-tanjung-mas-1','Pekan Tanjung Mas 1','pekan'),
]
RETYPES = {
 f'{K}:hulu-langat:balakong': 'bandar',
 f'{K}:petaling:serdang': 'pekan',
}
# Consolidations: Sabak Bernam town = Pekan Sabak (45200-set moves);
# Teluk Panglima Garang town = Bandar Telok Panglima Garang (42500 moves).
DELETE_ROWS = [f'{K}:sabak-bernam:sabak-bernam', f'{K}:kuala-langat:teluk-panglima-garang']
DROP_LINKS = []
KLANG_TOWN = ['41000','41050','41070','41100','41150','41160','41200','41205','41250','41299',
 '41300','41301','41400','41500','41506','41560','41586','41600','41670','41672','41700',
 '41710','41720','41730','41750','41780','41900','41902','41904','41906','41908','41910',
 '41912','41914','41916','41918','41990','42100','42150']
REPOINTS = (
 [(pc, f'{K}:klang:klang', f'{K}:klang:bandar-klang') for pc in KLANG_TOWN] +
 [('42200', f'{K}:klang:kapar', f'{K}:klang:pekan-kapar'),
  ('42209', f'{K}:klang:kapar', f'{K}:klang:pekan-kapar'),
  ('42500', f'{K}:kuala-langat:teluk-panglima-garang', f'{K}:kuala-langat:bandar-telok-panglima-garang'),
  ('42425', f'{K}:kuala-langat:telok-panglima-garang', f'{K}:kuala-langat:bandar-telok-panglima-garang'),
  ('42507', f'{K}:kuala-langat:telok-panglima-garang', f'{K}:kuala-langat:bandar-telok-panglima-garang'),
  ('42509', f'{K}:kuala-langat:telok-panglima-garang', f'{K}:kuala-langat:bandar-telok-panglima-garang'),
  ('42600', 'my:district:selangor:kuala-langat', f'{K}:kuala-langat:jenjarom'),
  ('45000', f'{K}:kuala-selangor:kuala-selangor', f'{K}:kuala-selangor:bandar-kuala-selangor'),
  ('45010', f'{K}:kuala-selangor:kuala-selangor', f'{K}:kuala-selangor:bandar-kuala-selangor'),
  ('45500', f'{K}:kuala-selangor:tanjong-karang', f'{K}:kuala-selangor:bandar-tanjong-karang'),
  ('45800', f'{K}:kuala-selangor:jeram', f'{K}:kuala-selangor:pekan-jeram'),
  ('45600', f'{K}:kuala-selangor:bestari-jaya', f'{K}:kuala-selangor:pekan-bestari-jaya'),
  ('45607', f'{K}:kuala-selangor:bestari-jaya', f'{K}:kuala-selangor:pekan-bestari-jaya'),
  ('45609', f'{K}:kuala-selangor:bestari-jaya', f'{K}:kuala-selangor:pekan-bestari-jaya'),
  ('45620', f'{K}:kuala-selangor:bestari-jaya', f'{K}:kuala-selangor:pekan-bestari-jaya'),
  ('45630', f'{K}:kuala-selangor:bestari-jaya', f'{K}:kuala-selangor:pekan-bestari-jaya'),
  ('45200', f'{K}:sabak-bernam:sabak-bernam', f'{K}:sabak-bernam:pekan-sabak'),
  ('45207', f'{K}:sabak-bernam:sabak-bernam', f'{K}:sabak-bernam:pekan-sabak'),
  ('45209', f'{K}:sabak-bernam:sabak-bernam', f'{K}:sabak-bernam:pekan-sabak'),
  ('45100', 'my:district:selangor:sabak-bernam', f'{K}:sabak-bernam:pekan-sungai-air-tawar'),
  ('43200', f'{K}:hulu-langat:cheras', f'{K}:hulu-langat:bandar-cheras'),
  ('43207', f'{K}:hulu-langat:cheras', f'{K}:hulu-langat:bandar-cheras'),
  ('43100', f'{K}:hulu-langat:hulu-langat', f'{K}:hulu-langat:bandar-hulu-langat'),
  ('43000', f'{K}:hulu-langat:kajang', f'{K}:hulu-langat:bandar-kajang'),
  ('43007', f'{K}:hulu-langat:kajang', f'{K}:hulu-langat:bandar-kajang'),
  ('43009', f'{K}:hulu-langat:kajang', f'{K}:hulu-langat:bandar-kajang'),
  ('43558', f'{K}:hulu-langat:kajang', f'{K}:hulu-langat:bandar-kajang'),
  ('43500', f'{K}:hulu-langat:semenyih', f'{K}:hulu-langat:bandar-semenyih'),
  ('68000', f'{K}:hulu-langat:ampang', f'{K}:hulu-langat:bandar-ampang'),
  ('43700', f'{K}:hulu-langat:beranang', f'{K}:hulu-langat:pekan-beranang'),
  ('43701', f'{K}:hulu-langat:beranang', f'{K}:hulu-langat:pekan-beranang'),
  ('44300', f'{K}:hulu-selangor:batang-kali', f'{K}:hulu-selangor:bandar-batang-kali'),
  ('44309', f'{K}:hulu-selangor:batang-kali', f'{K}:hulu-selangor:bandar-batang-kali'),
  ('44330', f'{K}:hulu-selangor:batang-kali', f'{K}:hulu-selangor:bandar-batang-kali'),
  ('44100', f'{K}:hulu-selangor:kerling', f'{K}:hulu-selangor:pekan-kerling'),
  ('44200', f'{K}:hulu-selangor:rasa', f'{K}:hulu-selangor:bandar-rasa'),
  ('48200', f'{K}:hulu-selangor:serendah', f'{K}:hulu-selangor:bandar-serendah'),
  ('48250', f'{K}:hulu-selangor:serendah', f'{K}:hulu-selangor:bandar-serendah'),
  ('48000', f'{K}:gombak:rawang', f'{K}:gombak:bandar-rawang'),
  ('48009', f'{K}:gombak:rawang', f'{K}:gombak:bandar-rawang'),
  ('48010', f'{K}:gombak:rawang', f'{K}:gombak:bandar-rawang'),
  ('48020', f'{K}:gombak:rawang', f'{K}:gombak:bandar-rawang'),
  ('48050', f'{K}:gombak:rawang', f'{K}:gombak:bandar-rawang'),
  ('48300', f'{K}:gombak:rawang', f'{K}:gombak:bandar-rawang'),
  ('48302', f'{K}:gombak:rawang', f'{K}:gombak:bandar-rawang'),
  ('47000', f'{K}:petaling:sungai-buloh', f'{K}:gombak:bandar-sungai-buloh'),
  ('47020', f'{K}:petaling:sungai-buloh', f'{K}:gombak:bandar-sungai-buloh'),
  ('47031', f'{K}:petaling:sungai-buloh', f'{K}:gombak:bandar-sungai-buloh'),
  ('48100', 'my:district:selangor:gombak', f'{K}:gombak:batu-arang'),
  ('43900', f'{K}:sepang:sepang', f'{K}:sepang:bandar-sepang'),
  ('43800', f'{K}:sepang:dengkil', f'{K}:sepang:pekan-dengkil'),
  ('43807', f'{K}:sepang:dengkil', f'{K}:sepang:pekan-dengkil'),
  ('64000', 'my:district:selangor:sepang', f'{K}:sepang:bandar-lapangan-terbang-antarabangsa-sepang'),
 ])
_cover = [
 (KLANG_TOWN, 'klang:klang'),
 (['42200','42209'], 'klang:kapar'),
 (['42425','42507','42509'], 'kuala-langat:telok-panglima-garang'),
 (['45000','45010'], 'kuala-selangor:kuala-selangor'),
 (['45500'], 'kuala-selangor:tanjong-karang'),
 (['45800'], 'kuala-selangor:jeram'),
 (['45600','45607','45609','45620','45630'], 'kuala-selangor:bestari-jaya'),
 (['43200','43207'], 'hulu-langat:cheras'),
 (['43100'], 'hulu-langat:hulu-langat'),
 (['43000','43007','43009','43558'], 'hulu-langat:kajang'),
 (['43500'], 'hulu-langat:semenyih'),
 (['68000'], 'hulu-langat:ampang'),
 (['43700','43701'], 'hulu-langat:beranang'),
 (['44300','44309','44330'], 'hulu-selangor:batang-kali'),
 (['44100'], 'hulu-selangor:kerling'),
 (['44200'], 'hulu-selangor:rasa'),
 (['48200','48250'], 'hulu-selangor:serendah'),
 (['48000','48009','48010','48020','48050','48300','48302'], 'gombak:rawang'),
 (['47000','47020','47031'], 'petaling:sungai-buloh'),
 (['43900'], 'sepang:sepang'),
 (['43800','43807'], 'sepang:dengkil'),
]
ADD_LINKS = (
 [(pc, f'{K}:{slug}', 'served_by', 'false') for pcs, slug in _cover for pc in pcs] +
 [
 # Klang shared
 ('42000', f'{K}:klang:bandar-sultan-sulaiman', 'served_by', 'false'),
 ('42000', f'{K}:klang:pekan-pandamaran', 'served_by', 'false'),
 ('40460', f'{K}:klang:pekan-bukit-kemuning', 'served_by', 'false'),
 ('41000', f'{K}:klang:pekan-telok-menegun', 'served_by', 'false'),
 # Kuala Langat shared
 ('42500', f'{K}:kuala-langat:bandar-sijangkang', 'served_by', 'false'),
 ('42800', f'{K}:kuala-langat:pekan-batu', 'served_by', 'false'),
 ('42700', f'{K}:kuala-langat:pekan-bukit-changgang', 'served_by', 'false'),
 ('42700', f'{K}:kuala-langat:pekan-chodoi', 'served_by', 'false'),
 ('42700', f'{K}:kuala-langat:pekan-kelanang-batu-enam', 'served_by', 'false'),
 ('42700', f'{K}:kuala-langat:pekan-morib', 'served_by', 'false'),
 ('42700', f'{K}:kuala-langat:pekan-permatang-pasir', 'served_by', 'false'),
 ('42700', f'{K}:kuala-langat:pekan-sungai-manggis', 'served_by', 'false'),
 ('42700', f'{K}:kuala-langat:pekan-sungai-raba', 'served_by', 'false'),
 ('42700', f'{K}:kuala-langat:pekan-tanjong-duabelas', 'served_by', 'false'),
 ('42700', f'{K}:kuala-langat:pekan-telok-datok', 'served_by', 'false'),
 # Kuala Selangor shared
 ('45700', f'{K}:kuala-selangor:pekan-asam-jawa', 'served_by', 'false'),
 ('45600', f'{K}:kuala-selangor:pekan-kampong-kuantan', 'served_by', 'false'),
 ('45000', f'{K}:kuala-selangor:pekan-pasir-penambang', 'served_by', 'false'),
 ('45000', f'{K}:kuala-selangor:pekan-bukit-belimbing', 'served_by', 'false'),
 ('45800', f'{K}:kuala-selangor:pekan-simpang-tiga', 'served_by', 'false'),
 ('45800', f'{K}:kuala-selangor:pekan-parit-mahang', 'served_by', 'false'),
 ('45800', f'{K}:kuala-selangor:pekan-sungai-sembilang', 'served_by', 'false'),
 ('45800', f'{K}:kuala-selangor:pekan-tambak-jawa', 'served_by', 'false'),
 ('45600', f'{K}:kuala-selangor:pekan-simpang-tiga-ijok', 'served_by', 'false'),
 ('45500', f'{K}:kuala-selangor:pekan-kampong-baru-hulu-tiram-buruk', 'served_by', 'false'),
 # Sabak Bernam shared
 ('45300', f'{K}:sabak-bernam:pekan-parit-enam', 'served_by', 'false'),
 ('45300', f'{K}:sabak-bernam:pekan-parit-sembilan', 'served_by', 'false'),
 ('45300', f'{K}:sabak-bernam:pekan-simpang-lima', 'served_by', 'false'),
 ('45300', f'{K}:sabak-bernam:pekan-sungai-haji-dorani', 'served_by', 'false'),
 ('45400', f'{K}:sabak-bernam:pekan-sekinchan-site', 'served_by', 'false'),
 ('45400', f'{K}:sabak-bernam:pekan-sungai-nibong', 'served_by', 'false'),
 ('45209', f'{K}:sabak-bernam:pekan-bagan-terap', 'served_by', 'false'),
 ('45200', f'{K}:sabak-bernam:pekan-sungai-sepintas', 'served_by', 'false'),
 ('45100', f'{K}:sabak-bernam:pekan-parit-baru', 'served_by', 'false'),
 # Hulu Langat shared
 ('43000', f'{K}:hulu-langat:bandar-country-height', 'served_by', 'false'),
 ('43200', f'{K}:hulu-langat:bandar-batu-9-cheras', 'served_by', 'false'),
 ('43207', f'{K}:hulu-langat:bandar-batu-9-cheras', 'served_by', 'false'),
 ('43700', f'{K}:hulu-langat:bandar-batu-26-beranang', 'served_by', 'false'),
 ('43500', f'{K}:hulu-langat:pekan-kachau', 'served_by', 'false'),
 ('43500', f'{K}:hulu-langat:pekan-tarun', 'served_by', 'false'),
 ('43500', f'{K}:hulu-langat:pekan-kampung-pasir-batu-14-semenyih', 'served_by', 'false'),
 ('43500', f'{K}:hulu-langat:pekan-batu-23-sungai-lalang', 'served_by', 'false'),
 ('43000', f'{K}:hulu-langat:pekan-bangi-lama', 'served_by', 'false'),
 ('43000', f'{K}:hulu-langat:pekan-kampung-sungai-tangkas', 'served_by', 'false'),
 ('43000', f'{K}:hulu-langat:pekan-simpang-balak', 'served_by', 'false'),
 ('43000', f'{K}:hulu-langat:pekan-sungai-kembong-beranang', 'served_by', 'false'),
 ('43100', f'{K}:hulu-langat:pekan-batu-18-hulu-langat', 'served_by', 'false'),
 ('43100', f'{K}:hulu-langat:pekan-desa-raya', 'served_by', 'false'),
 ('43100', f'{K}:hulu-langat:pekan-dusun-tua-hulu-langat', 'served_by', 'false'),
 ('43100', f'{K}:hulu-langat:pekan-sri-nanding', 'served_by', 'false'),
 ('43100', f'{K}:hulu-langat:pekan-sungai-lui', 'served_by', 'false'),
 # Hulu Selangor shared
 ('44300', f'{K}:hulu-selangor:bandar-hulu-yam', 'served_by', 'false'),
 ('44300', f'{K}:hulu-selangor:bandar-hulu-yam-baharu', 'served_by', 'false'),
 ('44300', f'{K}:hulu-selangor:bandar-sungai-chik', 'served_by', 'false'),
 ('44100', f'{K}:hulu-selangor:bandar-kalumpang', 'served_by', 'false'),
 ('35900', f'{K}:hulu-selangor:bandar-hulu-bernam-i', 'served_by', 'false'),
 ('35900', f'{K}:hulu-selangor:bandar-hulu-bernam-ii', 'served_by', 'false'),
 ('48000', f'{K}:hulu-selangor:pekan-simpang-sungai-choh', 'served_by', 'false'),
 # Petaling shared (all primaries stay on the city rows)
 ('40150', f'{K}:petaling:bandar-glenmarie', 'served_by', 'false'),
 ('40150', f'{K}:petaling:pekan-hicom', 'served_by', 'false'),
 ('40150', f'{K}:petaling:pekan-subang', 'served_by', 'false'),
 ('40150', f'{K}:petaling:pekan-baru-subang', 'served_by', 'false'),
 ('40150', f'{K}:petaling:pekan-batu-tiga', 'served_by', 'false'),
 ('40160', f'{K}:petaling:pekan-merbau-sempak', 'served_by', 'false'),
 ('40160', f'{K}:petaling:pekan-baru-sungai-buloh', 'served_by', 'false'),
 ('46000', f'{K}:petaling:pekan-sungai-penchala', 'served_by', 'false'),
 ('60000', f'{K}:petaling:pekan-sungai-penchala', 'served_by', 'false'),
 ('46000', f'{K}:petaling:pekan-penaga', 'served_by', 'false'),
 ('47400', f'{K}:petaling:pekan-kayu-ara', 'served_by', 'false'),
 ('47100', f'{K}:petaling:pekan-kinrara', 'served_by', 'false'),
 ('47170', f'{K}:petaling:pekan-kinrara', 'served_by', 'false'),
 ('47180', f'{K}:petaling:pekan-kinrara', 'served_by', 'false'),
 ('47190', f'{K}:petaling:pekan-kinrara', 'served_by', 'false'),
 ('47170', f'{K}:petaling:pekan-puchong-jaya', 'served_by', 'false'),
 ('47150', f'{K}:petaling:pekan-puchong-perdana', 'served_by', 'false'),
 ('47500', f'{K}:petaling:bandar-sunway', 'served_by', 'false'),
 ('52200', f'{K}:petaling:bandar-sri-damansara', 'served_by', 'false'),
 ('43300', f'{K}:petaling:pekan-baru-sungai-besi', 'served_by', 'false'),
 # Gombak shared + previously linkless bandars
 ('48020', f'{K}:gombak:kundang', 'served_by', 'false'),
 ('48050', f'{K}:gombak:kundang', 'served_by', 'false'),
 ('68100', f'{K}:gombak:selayang', 'served_by', 'false'),
 ('53100', f'{K}:gombak:gombak-setia', 'served_by', 'false'),
 ('53100', f'{K}:gombak:bandar-sungai-pusu', 'served_by', 'false'),
 ('52100', f'{K}:gombak:bandar-kepong', 'served_by', 'false'),
 ('54200', f'{K}:gombak:bandar-hulu-klang', 'served_by', 'false'),
 ('48050', f'{K}:gombak:pekan-pengkalan-kundang', 'served_by', 'false'),
 ('48000', f'{K}:gombak:pekan-templer', 'served_by', 'false'),
 ('68100', f'{K}:gombak:pekan-templer', 'served_by', 'false'),
 # Sepang shared
 ('43900', f'{K}:sepang:baru-salak-tinggi', 'served_by', 'false'),
 ('43900', f'{K}:sepang:pekan-salak', 'served_by', 'false'),
 ('43900', f'{K}:sepang:pekan-tanjung-mas', 'served_by', 'false'),
 ('43900', f'{K}:sepang:pekan-tanjung-mas-1', 'served_by', 'false'),
 ('43000', f'{K}:sepang:bandar-sungai-merab', 'served_by', 'false'),
 ('43650', f'{K}:sepang:bandar-baru-bangi', 'served_by', 'false'),
 ])
