<?php

declare(strict_types=1);

namespace AIArmada\FilamentEvents\Resources\EventResource\Schemas;

use AIArmada\Events\Data\EventDetailData;
use AIArmada\Events\Data\EventReviewSchemaData;
use AIArmada\Events\Enums\EventModerationStatus;
use AIArmada\Events\Enums\EventStatus;
use AIArmada\Events\Enums\EventVisibility;
use AIArmada\Events\Models\Event;
use AIArmada\Events\Services\EventQueryService;
use AIArmada\Events\Support\Policy\EventModerationPolicy;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

final class EventInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->schema([
                Section::make('Event')
                    ->schema([
                        TextEntry::make('name'),
                        TextEntry::make('slug')
                            ->copyable(),
                        TextEntry::make('status')
                            ->badge()
                            ->formatStateUsing(fn (EventStatus $state): string => $state->label())
                            ->color(fn (EventStatus $state): string => $state->color()),
                        TextEntry::make('moderation_status')
                            ->label('Moderation')
                            ->badge()
                            ->formatStateUsing(fn (EventModerationStatus $state): string => $state->label())
                            ->color(fn (EventModerationStatus $state): string => $state->color()),
                        TextEntry::make('visibility')
                            ->badge()
                            ->formatStateUsing(fn (EventVisibility $state): string => $state->label())
                            ->color(fn (EventVisibility $state): string => $state->color()),
                        TextEntry::make('registration_required')
                            ->label('Registration')
                            ->badge()
                            ->formatStateUsing(fn (bool $state): string => $state ? 'Required' : 'Optional')
                            ->color(fn (bool $state): string => $state ? 'warning' : 'gray'),
                        TextEntry::make('series.name')
                            ->label('Series')
                            ->placeholder('No series'),
                        TextEntry::make('product.name')
                            ->label('Product')
                            ->placeholder('Not linked'),
                        TextEntry::make('default_timezone')
                            ->placeholder('Not set'),
                        TextEntry::make('default_duration_minutes')
                            ->suffix(' minutes')
                            ->placeholder('Not set'),
                        TextEntry::make('published_at')
                            ->dateTime()
                            ->placeholder('Not set'),
                        TextEntry::make('public_starts_at')
                            ->dateTime()
                            ->placeholder('Not set'),
                        TextEntry::make('public_ends_at')
                            ->dateTime()
                            ->placeholder('Not set'),
                        TextEntry::make('summary')
                            ->columnSpanFull()
                            ->placeholder('No summary'),
                        TextEntry::make('description')
                            ->columnSpanFull()
                            ->placeholder('No description'),
                        TextEntry::make('search_keywords')
                            ->columnSpanFull()
                            ->placeholder('No search keywords'),
                        TextEntry::make('media_references')
                            ->label('Media references')
                            ->formatStateUsing(fn (mixed $state): string => self::formatJsonState($state))
                            ->columnSpanFull(),
                        TextEntry::make('taxonomy')
                            ->formatStateUsing(fn (mixed $state): string => self::formatJsonState($state))
                            ->columnSpanFull(),
                    ])
                    ->columns(3),

                Section::make('Read Model Snapshot')
                    ->description('Projections generated by the package EventQueryService from the EventDetailData DTO.')
                    ->schema([
                        TextEntry::make('snapshot.peopleNames')
                            ->label('Featured People')
                            ->state(fn (Event $record): string => self::formatStringList(self::snapshot($record)->peopleNames))
                            ->placeholder('No people linked')
                            ->columnSpanFull(),

                        TextEntry::make('snapshot.references')
                            ->label('Reference Materials')
                            ->state(fn (Event $record): string => self::formatJsonState(self::snapshot($record)->references))
                            ->placeholder('No references')
                            ->columnSpanFull(),

                        TextEntry::make('snapshot.metadata')
                            ->label('Metadata')
                            ->state(fn (Event $record): string => self::formatJsonState(self::snapshot($record)->metadata))
                            ->placeholder('No metadata')
                            ->columnSpanFull(),
                    ])
                    ->columns(1)
                    ->collapsible(),

                Section::make('Review Workflow')
                    ->description('Available actions driven by the package EventReviewSchemaData and EventModerationWorkflow.')
                    ->schema([
                        TextEntry::make('reviewSchema.actions')
                            ->label('Allowed actions for current state')
                            ->state(fn (Event $record): string => self::formatStringList(self::reviewSchema($record)->actions))
                            ->placeholder('No actions available')
                            ->columnSpanFull(),

                        TextEntry::make('reviewSchema.reasonCodes')
                            ->label('Configured reason codes')
                            ->state(function (Event $record): string {
                                $codes = EventModerationPolicy::reasonCodeOptions();
                                $labels = [];
                                foreach ($codes as $key => $label) {
                                    $labels[] = "{$key}: {$label}";
                                }

                                return implode("\n", $labels);
                            })
                            ->placeholder('No reason codes configured')
                            ->columnSpanFull(),
                    ])
                    ->columns(1)
                    ->collapsible(),
            ]);
    }

    private static function snapshot(Event $event): EventDetailData
    {
        return app(EventQueryService::class)->detail($event);
    }

    private static function reviewSchema(Event $event): EventReviewSchemaData
    {
        return app(EventQueryService::class)->reviewSchema($event);
    }

    /**
     * @param  array<int, string>  $items
     */
    private static function formatStringList(array $items): string
    {
        $filtered = array_values(array_filter(
            $items,
            static fn (mixed $item): bool => is_string($item) && mb_trim($item) !== '',
        ));

        return $filtered === [] ? '' : implode(', ', $filtered);
    }

    private static function formatJsonState(mixed $state): string
    {
        if (! is_array($state)) {
            return '';
        }

        return json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) ?: '';
    }
}
